### ISSUE TITLE
i dont know why i can do mapper 2 object without @AutoMap()

### ISSUE THREAD

**Issue by cesc1802** [nartc/mapper#110]
i have two object called user and userDto. 
```
user {
@AutoMap()
name: string;

@AutoMap()
password: string;

@AutoMap()
addrId: number;
}
```
```
Addr {
id: number,
addr: string
}
```
```
userDto {
@AutoMap()
name: string;

@AutoMap()
addr: string
}
```

when i perform sql by using `SELECT user.id, user.passowrd, Addr.addr FROM user LEFT JOIN Addr ON Addr.id = user.addrId`. I receive object  {id, name, addr}

although I don't have any @AutoMap() for addr, but when I do Mapper.map(userObject, userDtoObject, User). i also have value addr for userDTO.

**Comment by nartc** [comment]
I believe this can be closed?
