### ISSUE TITLE
AutoMapper thinks the string "0.00" is an empty value and maps to `null`

### ISSUE THREAD

**Issue by jmplahitko** [nartc/mapper#124]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

AutoMapper thinks the string "0.00" on a source property is an empty value. So, when mapping to the destination, it gets converted to `null`.

## Expected behavior

AutoMapper should preserve this string value and copy it to the destination object's property.

## Minimal reproduction of the problem with instructions

<pre><code>
// Given this model: 
class Product  {
	@AutoMap() price!: string;
}

// map some object:
const dest = mapper.map({ price: '0.00' }, Product, Product)
// dest === { price: null }
</code></pre>

## What is the motivation / use case for changing the behavior?
While 0.00 as a number is an "empty" value, the string "0.00" is not. There is a difference between 0.00 and "0.00", as well as "0.00" and "". 

## Environment

<pre><code>
Version: 6.2.0
 
For Tooling issues:
- Node version: 10.15.3
- Platform:  Mac

Others:

</code></pre>

**Comment by jmplahitko** [comment]
@nartc - The model in the issue description might be too simple. With the actual model I'm working wtth, I can follow the debugger through to around map.ts line 231, and somewhere before that `sourceObj` gets mutated and loses a bunch of properties. I can verify I am not using any beforeMap or afterMap functions.

**Comment by nartc** [comment]
@jmplahitko thanks for reporting. I was about to say that I couldn't reproduce the this error. Can you please provide a little more complex model and its valuee so I can test it out on my end?

**Comment by jmplahitko** [comment]
Ah, here are a couple models that will reproduce. Seems like an issue with nested models, maybe?: 
`
class ProductGood {
	@AutoMap() id!: number;
	@AutoMap() guid!: string;
	@AutoMap() brand!: string;
	@AutoMap() description!: string;
	@AutoMap() name!: string;
	@AutoMap() quantity!: number;
}

class Category {
	@AutoMap() id!: number;
	@AutoMap() guid!: string;
	@AutoMap() name!: string;
	@AutoMap() description!: string;
}
class Product {
	@AutoMap() id!: number;
	@AutoMap() guid!: string;
	@AutoMap() imageUrl!: string;
	@AutoMap() isBundle!: boolean;
	@AutoMap() name!: string;
	@AutoMap() price!: string;
	@AutoMap(() => Category) category!: Category|null;
	@AutoMap() description!: string;
	@AutoMap(() => ProductGood) goods!: ProductGood[];
}

class Cart {
	@AutoMap() id!: number;
	@AutoMap() guid!: string;
	@AutoMap(() => Product) products!: Product[];
	@AutoMap() subTotal!: string;
	@AutoMap() status!: number // TODO: ?
}

const dest = mapper.map({
	id: 0,
	products: [],
	guid: '',
	subTotal: '0.00',
	status: 0
}, Cart, Cart)
`
Hope this helps.

**Comment by nartc** [comment]
Sweet. I'll get back to you asap. Thanks

**Comment by nartc** [comment]
Also, I'd assume the mapping configuration for these models does not have anything special?

**Comment by nartc** [comment]
@jmplahitko Thanks for reporting. That was definitely a bug. It was caused by premature return when `instantiate` runs into a nested array model. Next release should fix the issue.

**Comment by jmplahitko** [comment]
That is correct, just same model-to-model mappings.

**Comment by nartc** [comment]
Please test the latest release out and let me know if it fixes your issues.
