### ISSUE TITLE
Error when try to map two classes

### ISSUE THREAD

**Issue by mohammad-khooie** [nartc/mapper#136]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

I want to try this library so I decide to map this class
`
class CreateProjectDto {
  @IsNotEmpty()
  @AutoMap()
  title: string;

  @IsNotEmpty()
  @AutoMap()
  description: string;

  @IsNotEmpty()
  @AutoMap()
  requestExpireDate: Date;

  @IsNotEmpty()
  @AutoMap()
  deadlineInDay: number;

  @IsNotEmpty()
  @AutoMap()
  deadlineDate: Date;

  @IsNotEmpty()
  @AutoMap()
  managerPhone: string;

  @IsNotEmpty()
  @AutoMap()
  managerName: string;

  @IsNotEmpty()
  @AutoMap()
  tagId: string;

  @IsNotEmpty()
  @AutoMap()
  companyId: string;

  @IsNotEmpty()
  @AutoMap()
  projectOwnerId: string;

  @IsNotEmpty()
  @AutoMap()
  price: number;
}
` 
to this class 
`
class ProjectRoDto {
  @AutoMap()
  id: string;

  @AutoMap()
  title: string;

  @AutoMap()
  description: string;

  @AutoMap()
  requestExpireDate: Date;

  @AutoMap()
  deadlineInDay: number;

  @AutoMap()
  deadlineDate: Date;

  @AutoMap()
  managerPhone: string;

  @AutoMap()
  managerName: string;

  @AutoMap()
  tagId: string;

  @AutoMap()
  companyId: string;

  @AutoMap()
  projectOwnerId: string;

  @AutoMap()
  price: number;
}
`
with this profile
`
@Profile()
export class ProjectProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper
      .createMap(CreateProjectDto, ProjectRoDto)
      .forMember((d) => d.id, ignore());
  }
}
`
but I get this error
`
Error: Mapping not found for source function Object() { [native code] } and destination class ProjectRoDto {
        static _OPENAPI_METADATA_FACTORY() {
            return { id: { required: true, type: () => String }, title: { required: true, type: () => String }, description: { required: true, type: () => String }, requestExpireDate: { required: true, type: () => Date }, deadlineInDay: { required: true, type: () => Number }, deadlineDate: { required: true, type: () => Date }, managerPhone: { required: true, type: () => String }, managerName: { required: true, type: () => String }, tagId: { required: true, type: () => String }, companyId: { required: true, type: () => String }, projectOwnerId: { required: true, type: () => String }, price: { required: true, type: () => Number } };
        }
    }
`
also I use nestjs module of this library("nestjsx-automapper": "3.0.10")
and nestjs version is 7.0.13
## Environment

<pre><code>
node :12.16.3

**Comment by nartc** [comment]
Can you please share the code where you call .map() ?

**Comment by mohammad-khooie** [comment]
this is my service class that use automapper although I do not call this service and this error happens before service call
@Injectable()
export class ProjectService {
  constructor(
    @InjectModel(Project)
    private projectRepo: typeof Project,
    @InjectMapper()
    private readonly mapper: AutoMapper,
  ) {}

  async add(_projectObj: CreateProjectDto): Promise<ProjectRoDto> {
    const projectObj = this.mapper.map(_projectObj, ProjectRoDto);

    return projectObj;
  }
}

**Comment by nartc** [comment]
@mohammad-khooie I am pretty confident that `_projectObj` isn't really an instance of `CreateProjectDto`. Try `this.mapper.map(_projectObj, ProjectRoDto, CreateProjectDto)`?

**Comment by mohammad-khooie** [comment]
I also took this issue with another issue I want to send, so the issue occurred while calling the service
and this.mapper.map(_projectObj, ProjectRoDto, CreateProjectDto) works correctly
thanks for help
