### ISSUE TITLE
Mapping from class that don't have extra properties

### ISSUE THREAD

**Issue by AliYusuf95** [nartc/mapper#147]
## I'm submitting a...
<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
When I try to map from a class that extends another class without having extra property the mapping failed with `Error: Mapping not found for source ...`.

I tried to override a property so I can use `@AutoMap()` on it to create mapping data, but that not work either but the error changed
```
Error: Mapping for {class1} <-- my overridden property
cannot be found. Consider manual map this property with MapWith
```

## Expected behavior
Able to map extended classes without having new extra properties and the ability to override properties without manual mapping for them.

## Minimal reproduction of the problem with instructions
https://github.com/AliYusuf95/ng-automapper/tree/extend

## Environment

<pre><code>
Version: 6.3.9
 
For Tooling issues:
- Node version: 12.13.1
- Platform:  Mac

Others:
- Typescript: 3.8.3
- Angular: 9.1.9
</code></pre>

**Comment by nartc** [comment]
Thanks for reporting. I have not yet to verify but I will this weekend.

**Comment by nartc** [comment]
@AliYusuf95 please test the latest release to see if the problem persists. Thanks again
