### ISSUE TITLE
Null Substitution support

### ISSUE THREAD

**Issue by lqmanh** [nartc/mapper#15]
Hi @nartc,

You state in the README that null substitution feature may not be added, in favor of `fromValue()`. However, as I understand, the use cases of these two are different.

1. In the original library, Jimmy Bogard says:
> Null substitution allows you to supply an alternate value for a destination member if the source value is null anywhere along the member chain. This means that instead of mapping from null, it will map from the value you supply.

It means the mapper will only assign the value you provide if the source member is null. 

2. `fromValue()` allows you to map a raw value to a destination member, regardless of the source member value.

Am I wrong anywhere?

**Comment by nartc** [comment]
Hi,

It seems you are correct. Then it totally makes sense to have “nullSubstitution” added. 

Thanks for pointing that out

**Comment by lqmanh** [comment]
Thank you!
