### ISSUE TITLE
Naming convention does not exist (version 6.3.14)

### ISSUE THREAD

**Issue by ThijmenMaus** [nartc/mapper#165]
## I'm submitting a...

<pre><code>
[   ] Regression 
[ X ] Bug report
[   ] Feature request
[ X ] Documentation issue or request
[ X ] Support request
</code></pre>

## Current behavior

I got two models:
```ts
export class User {
  ID: number;
  Name: string
}
```
and
```ts
export class UserDTO {
   name: string;
}
```

when I try to map them like this:
```ts
mapper.createMap(User, UserDTO, { sourceMemberNamingConvention: PascalCaseNamingConvention });
```
it gives me the following error: `Cannot find name 'PascalCaseNamingConvention'.ts(2304)` - Which (of course) means it's not imported, however I can't seem to import it from anywhere.. I only have a `/dist` folder with the types for it, but I can't use it since they are types..

## Expected behavior

I would expect it to just import it and make the mapping work. It also isn't described in the documentation where to import it from.

## Minimal reproduction of the problem with instructions

See snippet above

## What is the motivation / use case for changing the behavior?

Not applicable

## Environment

<pre>Visual Studio Code 2019<code>
Version: 2019
 
For Tooling issues:
- Node version: 12.16.3 
- Yarn version: 1.22.4 (I use yarn as a PM)
- Platform:  Windows 

Others:

</code></pre>

**Comment by knopki** [comment]
Temporary workaround:
```js
import { PascalCaseNamingConvention } from '@nartc/automapper/dist/conventions';
```
