### ISSUE TITLE
Any way to work with mapped types from `@nestjs/swagger`

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#173]
I want to use utility functions like `OmitType` (provided by [`@nestjs/swagger`](https://github.com/nestjs/swagger) lib) to do something like this:

```ts
import { ApiPropertyOptional, OmitType } from '@nestjs/swagger';

class UserVm { // assuming that each prop can have some kind of ApiProperty decorator
  @AutoMap()
  firstName: string;
  @AutoMap()
  lastName: string;
  @AutoMap()
  about: string;
  @AutoMap()
  @ApiPropertyOptional({ type: String, format: 'date-time' })
  deletedAt?: Date
  @AutoMap()
  deletedBy?: number;
  // ...
}

class NonDeletableUserVm extends OmitType(UserVm, ['deletedAt', 'deletedBy']) {}
// ^ this class will be a swagger schema/model as well
```

but the annotations generated by `@AutoMap()` decorator are not inherited when using these helpers functions, so all props annotated with `@AutoMap()` will not be auto mapped by the mapper (since they're aren't identified).

Maybe this is a limitation of @nestjs/swagger (or TS?) but I'm not sure.

Any thoughts?

Great lib btw :smiling_face_with_three_hearts: 

---

### minimal reproduction

https://codesandbox.io/s/nartcautomapper-issue-173-wv1s0

**Comment by nartc** [comment]
Interesting. I'll have to take a look and will let you know ASAP if it's a go or no-go. Thanks for the issue

**Comment by nartc** [comment]
Not sure if I have time this weekend to look into this. I'm going to put this in the backlog for now.

**Comment by micalevisk** [comment]
> Not sure if I have time this weekend to look into this. I'm going to put this in the backlog for now.

It's fine :+1: 

You can download a minimal reproduction here later: https://codesandbox.io/s/nartcautomapper-issue-173-wv1s0
See `src/app.profile.ts` and the response at http://localhost:3030/docs using the <kbd>Try it out</kbd> button.

**Comment by nartc** [comment]
@micalevisk Looking at `nestjs/mapped-types`, it seems that the mapped types only inherit Validation and Transform metadata (`class-transformer` and `class-validation`). What I can do is to add some mixins to `nestjsx-automapper` (instead of this package) to extend the functionality of the `mapped-types` but with the addition of `@AutoMap()` decorator. Hence, I'm going to open an issue over at `nestjsx/automapper` and close this one.
