### ISSUE TITLE
please disable not map assertion error in inherited classes when the base class not included in createMap function

### ISSUE THREAD

**Issue by farid009** [nartc/mapper#176]
## I'm submitting a...
<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
throw not map assertion error for inherited class although base class not included.
I have this entity
<pre><code>
@Entity()
export class Customer extends BaseEntity {
  @OneToOne(() => User, { eager: true, primary: true })
  @JoinColumn({ name: 'id' })
  @AutoMap(() => User)
  user: User;
}
</pre></code>
that extends BaseEntity 
I want to map this dto to Customer entity
<pre><code>
export class CreateCustomerDto{
  @IsNotEmpty({ always: true })
  @ValidateNested({ always: true })
  @Type(() => CreateUserDto)
  @AutoMap(() => CreateUserDto)
  user: CreateUserDto;
}
</code></pre>
when I try to do that I get assertion error for createdAt and updatedAt (fields of BaseEntity) although I dont include BaseEntity in createMap
<pre><code>
mapper
      .createMap(CreateCustomerDto, Customer);
</code></pre>
## Expected behavior
disable not map assertion error in inherited classes when the base class not included in createMap function
## Environment
<pre><code>
Version: 6.4
 </pre></code>

**Comment by nartc** [comment]
Although .NET AutoMapper (C#) is really strict regarding Unmapped Properties, I get that we shouldn't be that strict in JS/TS world. I'm going to add a global settings to disable assertion. Would that be ok?

**Comment by farid009** [comment]
I think yes 
its very cool

**Comment by nartc** [comment]
It won't be today though. Super busy at work at the moment.

**Comment by farid009** [comment]
ok thanks for now I use version 6.3
