### ISSUE TITLE
name/value pairs are in reverse order in JSON after mapping

### ISSUE THREAD

**Issue by He-Wolf** [nartc/mapper#181]
Hello @nartc ,

I must thank you for the excellent job you do with this module. It fills a huge gap in Nest/Ng context.

I have just started to use the module, and I have a minor issue. Maybe I am doing something wrong.

I am developing a simple todo Nest.js API, and I use Automapper to map entity class to Dto class. Everything works fine, but after mapping something strange happens: the JSON name/value pairs are in reverse order as they were defined in the class. 

Can I somehow get them in the right order?

Todo Entity class:
```
export class TodoEntity {
    @AutoMap()
    id: string;
    @AutoMap()
    name: string;
    @AutoMap()
    description?: string;
}
```
Todo Dto class:
```
export class TodoDto {
    @AutoMap()
    id: string;
    @AutoMap()
    name: string;
    @AutoMap()
    description?: string;
}
```
The profile:
```
@Profile()
export class TodoProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(TodoEntity, TodoDto).reverseMap();
  }
}
```
And the service which is used by the controller:
```
@Injectable()
export class TodoService {
    todos: TodoEntity[] = todos;

    constructor(@InjectMapper() private readonly mapper: AutoMapper) { }
    
    async getAllTodo(): Promise<TodoDto[]>{
        return toPromise(this.mapper.mapArray(this.todos, TodoDto, TodoEntity));
    }
    ...
}
```
The controller part:
```
@Controller("api/todos")export class TodoController {
    constructor(private readonly todoService: TodoService) {}
    
    @Get()
    async findAll(): Promise<TodoListDto> {
      const todos = await this.todoService.getAllTodo();
      return toPromise({ todos });
    }
    ...
}
```
And the response from the API is:
```
{
    "todos": [
        {
            "description": null,
            "name": "Supermarket Todo list",
            "id": "eac400ba-3c78-11e9-b210-d663bd873d93"
        }
    ]
}
```
But is should be: 
```
{
    "todos": [
        {
            "id": "eac400ba-3c78-11e9-b210-d663bd873d93",
            "name": "Supermarket Todo list",
            "description": null,
        }
    ]
}
```
The source can be found on: https://github.com/He-Wolf/NGNestApp/tree/4e9752175c6559bd0433f2a7aa6650e82b10e5bc/server

Thank you for your help in advance!

**Comment by nartc** [comment]
I have an idea to fix this. Thanks for reporting.

**Comment by nartc** [comment]
@He-Wolf Actually, just realize you use nestjsx-automapper so I need to cut a new release for that so it has the latest changes as well.

**Comment by He-Wolf** [comment]
Yes, you are right. I should have opened the issue in nestjsx-automapper repo. :)
Anyway, that you for the quick response and correction!

**Comment by friedScotch** [comment]
@nartc I don't know if I am the only one, but I am experiencing the exact same issue as well. 

I'm using 8.4.1 for classes, core and nestjs

**Comment by nartc** [comment]
@friedScotch please open a new issue and if possible, please attach a simple reproduce.
