### ISSUE TITLE
Mapping uppercase properties and case sensitivity

### ISSUE THREAD

**Issue by AliYusuf95** [nartc/mapper#208]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
**1-** If I have a property key `UpperCase` in both source and destination classes it'll throw an Error
```
Unmapped properties:
-------------------
UpperCase
```

**2-** If I have a property key `upperCase` and `UpperCase` it'll map both properties with `upperCase` value.

## Expected behavior
Ability to mapping properties that started with uppercase letters, and be case sensitivity in properties names

## Minimal reproduction of the problem with instructions
Check this branch [case_sensitivity](https://github.com/AliYusuf95/ng-automapper/tree/case_sensitivity)

## Environment

<pre><code>
Version: 7.0.2
 
For Tooling issues:
- Node version: 12.13.1
- Platform: Mac

Others:

</code></pre>

**Comment by nartc** [comment]
https://automapper.netlify.app/docs/usages/features/naming-convention have you checked out this docs?

**Comment by AliYusuf95** [comment]
@nartc Yes I did, the thing that I have to use a naming convention for the source/distention but in my case I don't have a fixed convention. 

I thing the default behavior should map between the properties that having same name unless we specify a naming convention or the library should ship with it an implementation for such behavior.

**Comment by nartc** [comment]
My initial thought that that would not be possible given that the library needs to ship `Flatten` capability. But I'll think about this a little bit more then I'll get back to you.

**Comment by AliYusuf95** [comment]
@nartc for now I implemented this convention to solve my problem, but I'm not sure if it'll cover all scenarios

```ts
class FlattenConvention implements NamingConvention {
  separatorCharacter: '';
  splittingExpression: RegExp = /(^.+)/i;
  transformPropertyName(sourcePropNameParts: string[]): string {
    return sourcePropNameParts.join();
  }
}

Mapper.withGlobalSettings({
  sourceNamingConvention: FlattenConvention,
  destinationNamingConvention: FlattenConvention,
});
```

**Comment by nartc** [comment]
What exactly does this naming convention do?

**Comment by AliYusuf95** [comment]
In my case, I don't want to use naming conventions for automatically mapping. 
I just want to map whatever key on the source to its corresponding key in destination and if I have customization I'll use `forMember` to do it.
For example if I have these classes:
```
class Company {
  @AutoMap()
  camelCase: string;
  @AutoMap()
  PascalCase: string;
  @AutoMap()
  snake_case: string;
  @AutoMap()
  ['Some_Complex.Key| string']: string;
}
class CompanyVm {
  @AutoMap()
  camelCase: string;
  @AutoMap()
  PascalCase: string;
  @AutoMap()
  snake_case: string;
  @AutoMap()
  ['Some_Complex.Key| string']: string;
}
```
I expect that mapping will work without any extra configration.
That's what I'm trying to achieve with my `FlattenConvention`, and it works fine unless there is `.` in the keys.

**Comment by nartc** [comment]
@AliYusuf95 I see. I might be able to provide a `MixedConvention` mode for cases like yours. But it's gotta be a configuration because I need to keep the CamelCaseNamingConvention as default.

**Comment by nartc** [comment]
Closing this due to #243 . I won't be adding this to the current `@nartc/automapper` as stated in the announcement. That said, this will be available in the new version. Sorry for any inconvenience.
