### ISSUE TITLE
Generic Mapping

### ISSUE THREAD

**Issue by santhoshprogrammer94** [nartc/mapper#219]
How to map generic classes

For example:

`mapper(PagedModel<GetCustomerBase>,GetCustomerResponse)`

;

**Comment by nartc** [comment]
It's not possible because this syntax `PagedModel<GetCustomerBase>` isn't available at runtime. I know what you want to achieve but it'd be helpful if you can provide your specific use-case then we can come up with workaround.

**Comment by santhoshprogrammer94** [comment]
![Screenshot 2020-10-23 at 9 26 50 AM](https://user-images.githubusercontent.com/44298661/96954896-0147a800-1512-11eb-8c54-bfd1b548a9be.png)
![Screenshot 2020-10-23 at 9 26 07 AM](https://user-images.githubusercontent.com/44298661/96954904-04429880-1512-11eb-9333-86400618b7a6.png)
![Screenshot 2020-10-23 at 9 25 44 AM](https://user-images.githubusercontent.com/44298661/96954905-04db2f00-1512-11eb-853e-1532e600d01c.png)
![Screenshot 2020-10-23 at 9 24 09 AM](https://user-images.githubusercontent.com/44298661/96954906-0573c580-1512-11eb-8ba7-18db1f26badc.png)


Am .Net Core Developer. I just switched to Nodejs.  I want to archive the same thing Nestjs. Is this Possible?

Thank you

**Comment by nartc** [comment]
@santhoshprogrammer94 I'll take a look and will get back to you.

**Comment by leandro-manifesto** [comment]
The difference to .NET is that there generic classes are bound to their generic parameters to generate the `Type`s used in runtime, so `PagedModel<Something>` and `PagedModel<SomethingElse>` are different `Type`s and Automapper has access to all involved types through reflection.

In TypeScript, the compilation to JavaScript erases the generic information, kinda like Java. At runtime, `PagedModel<Something>` and `PagedModel<SomethingElse>` will use the exact same class, `PagedModel`, although I'm not sure if using the decorator metadata it would be possible to get those extra types.

**Comment by nartc** [comment]
@leandro-manifesto Reflection might be able to get the type but what about the syntax of generics models when using the API like `createMap()` since `PagedModel<Generic>` is syntactically wrong :)

**Comment by leandro-manifesto** [comment]
Unfortunately it's not available.

Check https://github.com/Microsoft/TypeScript/issues/3015#issuecomment-128149650 and https://github.com/microsoft/TypeScript/issues/3628.

The alternative is to use some kind of compile-time generation.

**Comment by leandro-manifesto** [comment]
@santhoshprogrammer94 basically the `createMap(PagedModel<GetCustomerBase>, GetCustomerResponse)` syntax is invalid because the generic portion isn't available during runtime.

The correct one would be `createMap(PagedModel, GetCustomerResponse)`, but that is pretty much useless.

**Comment by nartc** [comment]
Closing this due to #243 . I won't be adding this to the current @nartc/automapper as stated in the announcement. This still be an area where I'd like to investigate further in the future. Sorry for any inconvenience.

**Comment by renatoargh** [comment]
Hey, @nartc 👋  
Did you get to any conclusion after investigating this issue more?

**Comment by nartc** [comment]
@renatoargh Unfortunately, I didn't have time to investigate much into this. My thought would be it's currently impossible, at least without some sort of compiler API (aka during compilation time). If someone could come up with a proposal, I'm all ears.

**Comment by renatoargh** [comment]
Thanks again for your quick reply. Right now I have one single case where I am mapping a generic class manually but using automapper for the rest, so not a blocker. Thanks again for the work in this useful library

**Comment by nartc** [comment]
@renatoargh it would help if you could share that manual case.

**Comment by renatoargh** [comment]
It is actually no big deal. I have a generic `Envelope` wrapper like this:

```typescript
export class Envelope<T> {
  public readonly grid: string

  constructor(public readonly metadata: Metadata, public readonly data: T) {
    this.grid = metadata.grid.toString()
  }

  toJSON(): EnvelopeData {
    return {
      grid: this.grid,
      metadata: this.metadata.toJSON(),
      data: this.data,
    }
  }
}
```

And because automapper doesn't work for generic classes I have to manually parse Envelope to/from the database format, but then I use automapper to map the contents of `data`, so it is actually minimal manual work.

So I end up doing something like this when I need to persist it to the database:

```typescript
@Injectable()
export class ContactDbSerializer implements Serializer<Contact, DbContact> {
  toJSON(contact: Envelope<Contact>): Envelope<DbContact> {
    const dbContact = mapper.map(contact.data, DbContact, Contact) // <-- this is the automatic part
    return new Envelope<DbContact>(contact.metadata, dbContact).toJSON() // <-- this is manual
  }
}
```

Because `Envelope` and `Metadata` are not deeply nested not have a lot of fields the manual work is minimal
