### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object.

### ISSUE THREAD

**Issue by apascual-ish** [nartc/mapper#229]
Hi, I've encountered issue on `Object.getOwnPropertyNames(node)` under `getPathRecursive` function when the node is null or undefined. Here is the screenshot.

![image](https://user-images.githubusercontent.com/60680092/100577978-4f737680-331c-11eb-99a1-670ebccbf672.png)

It happens when trying to map, FormControl to String Type variable.

```
class TestDto {
   public id: string
}

class TestVm {
   public formControlId = new FormControl('');
}

/// Mapping TestDto <=> TestVm
Mapper.createMap(TestDto, TestVm).reverseMap();
```

I think it might be better if you would check first if the `node` is `null` or `undefined`? and ignore it if its the case?

**Comment by nartc** [comment]
Thanks for reporting.

**Comment by nartc** [comment]
This should be fixed in `@automapper/core@1.0.0-beta.3`. Please consider giving the migrations guide a look: https://automappertr.netlify.app

I'm happy to support migrating in any way I can.

**Comment by nartc** [comment]
Closing. Please open a new issue if you still run into problems.

**Comment by rajneeshmith** [comment]
This is still reproduceable in `@automapper/core": "4.2.2"`
