### ISSUE TITLE
Can't build project with Automapper imported in --prod

### ISSUE THREAD

**Issue by Codevanger** [nartc/mapper#24]
When you're trying to build project in Production, the following error will occur: 
`ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@nartc/automapper/dist/automapper' in 'D:\test\Automapper\src\app'
resolve '@nartc/automapper/dist/automapper' in 'D:\test\Automapper\src\app'`

How to reproduce:

1. Create a new project with 'ng new'
2. Import Automapper
3. Create 2 models and a mapping profile for it
4. Initialize it in app.module constructor
5. Try to build project 

But at last - It building good with 'ng build'.

Full error bellow:

`
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@nartc/automapper/dist/automapper' in 'D:\test\Automapper\src\app'
resolve '@nartc/automapper/dist/automapper' in 'D:\test\Automapper\src\app'
  Parsed request is a module
  using description file: D:\test\Automapper\package.json (relative path: ./src/app)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in D:/test/Automapper/
        using description file: D:\test\Automapper\package.json (relative path: .)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\test\Automapper\package.json (relative path: ./@nartc/automapper/dist/automapper)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\@nartc\automapper\dist\automapper doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\@nartc\automapper\dist\automapper.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\@nartc\automapper\dist\automapper.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\@nartc\automapper\dist\automapper.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\@nartc\automapper\dist\automapper.js doesn't exist
            as directory
              D:\test\Automapper\@nartc\automapper\dist\automapper doesn't exist
      D:\test\Automapper\src\app\node_modules doesn't exist or is not a directory
      D:\test\Automapper\src\node_modules doesn't exist or is not a directory
      D:\test\node_modules doesn't exist or is not a directory
      D:\node_modules doesn't exist or is not a directory
      looking for modules in D:\test\Automapper\node_modules
        using description file: D:\test\Automapper\package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: D:\test\Automapper\node_modules\@nartc\automapper\package.json (relative path: ./dist/automapper)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.tsx doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.js doesn't exist
            as directory
              D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper doesn't exist
[D:\test\Automapper\@nartc\automapper\dist\automapper]
[D:\test\Automapper\@nartc\automapper\dist\automapper.ts]
[D:\test\Automapper\@nartc\automapper\dist\automapper.tsx]
[D:\test\Automapper\@nartc\automapper\dist\automapper.mjs]
[D:\test\Automapper\@nartc\automapper\dist\automapper.js]
[D:\test\Automapper\src\app\node_modules]
[D:\test\Automapper\src\node_modules]
[D:\test\node_modules]
[D:\node_modules]
[D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper]
[D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.ts]
[D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.tsx]
[D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.mjs]
[D:\test\Automapper\node_modules\@nartc\automapper\dist\automapper.js]
 @ ./src/app/app.module.ngfactory.js 13:0-56 14:2665-2678
 @ ./src/main.ts
 @ multi ./src/main.ts
`

**Comment by Codevanger** [comment]
Nevermind, I figured out what's going on here. I created the angular package and put your codebase in it and it worked. I created npm package here: 
https://www.npmjs.com/package/ngx-automapper/access
and GitHub project here: 
https://github.com/Codevanger/ngx-automapper

If you don't mind

**Comment by nartc** [comment]
@Codevanger is this Angular 8 or 9? Or is this new project Ivy? I'd love to look into it.

**Comment by Codevanger** [comment]
Angular 8

**Comment by Codevanger** [comment]
How I see it - it's missing some files that Angular CLI needed. When you creating a new angular library it's okay, so it's what I did. It's missing some angular-related files or whatsoever

**Comment by nartc** [comment]
@Codevanger What I'm getting at is it shouldn't matter because `automapper` is just another typescript library: like `lodash`, like `moment`, like `rxjs`. I don't think those libraries are Angular specific. 

Thanks for the investigation. I'll take a look at the bug as soon as possible.

**Comment by nartc** [comment]
@Codevanger  can you provide a reproducible repository? I can't seem to reproduce the issue at all.

```
@angular/core: 9.0.0-rc6
@nartc/automapper: 2.0.3
```

![image](https://user-images.githubusercontent.com/25516557/70855224-23ea4880-1e8d-11ea-9e55-704db5df32d9.png)
![image](https://user-images.githubusercontent.com/25516557/70855226-29e02980-1e8d-11ea-8cf6-96669ac044d9.png)
![image](https://user-images.githubusercontent.com/25516557/70855227-2f3d7400-1e8d-11ea-8712-c75089983421.png)
![image](https://user-images.githubusercontent.com/25516557/70855229-3795af00-1e8d-11ea-9d01-db1fcfdc13cd.png)

**Comment by Codevanger** [comment]
Sorry for a long answer.

`Angular CLI: 8.3.20
Node: 12.4.0`

![image](https://user-images.githubusercontent.com/36956445/70973047-e583a200-20b5-11ea-9825-eaaf01207452.png)

![image](https://user-images.githubusercontent.com/36956445/70973051-eae0ec80-20b5-11ea-90e7-9e9a638fb8f3.png)

![image](https://user-images.githubusercontent.com/36956445/70973093-03e99d80-20b6-11ea-9613-5165f67e479c.png)

**Comment by nartc** [comment]
You can’t have mapper in the constructor of AppModule. AppModule is initialized by Angular when it bootstraps the app. 

Try using Mapper singleton. Remove the mapper in the constructor, then use Mapper.initialize()

**Comment by Codevanger** [comment]
Okay, now it's building and working. 
I guess I can close it now.
