### ISSUE TITLE
Announcement: Changes and Project status

### ISSUE THREAD

**Issue by nartc** [nartc/mapper#243]
Hi all,

Thank you all for using/giving `@nartc/automapper` a try. I have some announcement to make regarding the project status.

First and foremost, the updates for the project have been slow. The reason is I've just changed job recently and I'm still adapting to the new workplace so there's less time on my part to work on personal projects like `@nartc/automapper`. Also, my wife and I are expecting our first baby so there's been a lot of preparations around the house to welcome our baby.

Second, I have some visions for the project. Currently, `@nartc/automapper` works well for my use-cases (and some others' use-cases) as I built it based on my needs about a year ago. That said, it's not very extensible. Almost the fixes I put in `@nartc/automapper` have been more like patches rather than actual fixes.

To counter this (and also to welcome more contributors), I've decided to rework on the core of `@nartc/automapper` with the following list of upcoming changes:

- AutoMapper will be a monorepo and will be plugin-based. A side note on plugins, I don't envision there's a lot of extensibility to AutoMapper because the concept itself is very opinionated. However, plugin-based model allows me (or contributors) to stay focus on specific areas of the library when problem arises.
- There will be documentation on how to create your own Custom Plugin
- AutoMapper will provide the following libraries:
   - `core`: This is the core of AutoMapper which will handle the actual mapping configurations and operations. Core will not dictate how it will store Mappings, Metadata like it's doing now with `@nartc/automapper`. Plugins will do so on their own and provide the Mappings when Core asks for them.
   - `classes` (plugin): This is a plugin that would make AutoMapper work with Classes. This is exactly like how AutoMapper works today but with improvements to typings and overall performance. `classes` plugin provides its own way of storing the Mapping and Metadata.
   - `interfaces` (plugin, name is subject to change): This is a plugin that would allow AutoMapper to work with Interfaces. With the plugin providing its own Metadata storing mechanism, making interfaces work is an easier feat than the current state of `@nartc/automapper`.
   - `nest` (wrapper for NestJS): As the name said, it will be a wrapper for NestJS, with improvements to usability.
- AutoMapper Transformer Plugin's status is TBD. I'm not sure how I want to provide this as of the moment
- About `NamingConvention` and a couple of **default settings** that `@nartc/automapper` currently sets right now, I'll be addressing these to be less opinionated and less strict as well. This is to address #208 and #215 
- AutoMapper will provide a way to map a `sourceObj` to a `destinationObj`. This is to address #244 
- AutoMapper will provide the `core` and its official plugins via `@automapper/*` npm scope following Semantic Versioning for all provided packages. This is to give consumers a sense of somewhat **official**. And I really want to welcome other contributors.

With all of these in mind, I'll not be adding new features to current `@nartc/automapper` as of the moment. I'll still try to address bugs and help out with issues (in terms of usage) if my availability permits. Once again, thank you all and I'll see you around.

**Comment by AliYusuf95** [comment]
Thanks for your awesome effort￼ @nartc, creating this library and continue supporting it.￼￼ I wish you good luck in your job and may god bless the new baby 😄.

It's good plan to have a core and plugins to do the work, which might make thing easier and cleaner specially when using [class-transformer](https://github.com/typestack/class-transformer) at the same time -a plugin to make both auto-mapper and transformer works out-of-the-box or replace it. I'm ready to contribute￼ if it's needed.

**Comment by nartc** [comment]
@AliYusuf95 Thanks for the kind words.

**Comment by nartc** [comment]
Update: https://github.com/nartc/mapper/tree/main the refactor is on this branch if anyone is interested to check out.
 
I'll be working on docs and nestjs integration tomorrow. Hopefully I can be in a state where I can release a beta version :)

**Comment by nartc** [comment]
`1.0.0-beta.2` has been released. Please give these a go. Check out the documentation as well.
PS: migration docs is in the work
![image](https://user-images.githubusercontent.com/25516557/103498447-7258e500-4e0a-11eb-899a-46a479bde45d.png)

**Comment by nartc** [comment]
https://www.npmjs.com/package/@automapper/core has been released and I also wrote a blog post: https://nartc.me/blog/automapper-typescript-1.
