### ISSUE TITLE
How to use getMapperToken in jest/nestjs test module?

### ISSUE THREAD

**Issue by boy51** [nartc/mapper#245]
Hi, so far the only way I've been getting unit tests to work is importing AutomapperModule, and mocking Automapper with ts-mockito

```

 const mockMapper = mock(AutoMapper)
 const module: TestingModule = await Test.createTestingModule({
      imports: [AutomapperModule.withMapper()],
      providers: [
        ...
        {
          provide: AutoMapper,
          useValue: instance(mockMapper),
        },
      ],
```

Thats pretty slow. I noticed there is a getMapperToken method, but I don't know how to use it. It doesn't seem to work.

Thanks!

**Comment by nartc** [comment]
@boy51 Hi, `getMapperToken()` returns the token that `@InjectMapper()` uses so in theory, you can have the following:

```ts
{
   provide: getMapperToken(),
   useValue: new AutoMapper()
}
```

If it didn't work, please provide a simple repro which would help me track the issue easier.

Also, please consider migrating over to `@automapper/nestjs` with this guide: https://automapperts.netlify.app/docs/migrations I am happy to support the migration in any way I can. There's also an example of testing a profile (for `@automapper/nestjs`) here: https://github.com/nartc/mapper/blob/main/packages/nestjs-integration-test/src/app/profiles/address.profile.spec.ts

**Comment by boy51** [comment]
Hi @nartc , thanks! Using a new instance with the token works. And indeed, I need to move to the new library, I didnt know you already moved repos.

Do you have any examples for testing profiles?

Cheers

**Comment by nartc** [comment]
@boy51 Awesome. Glad that worked. And the new packages are beta right now but they're pretty much ready. There's one last thing I want to explore with the nestjs wrapper before I press the official release button. What do you think of:

```ts
export class Controller {
   
   @Get('some')
   @UseInterceptors(AutomapInterceptor(SomeDto))
   someHandler() {
   
   }
}
```

Basically, it's an interceptor to map automatically.

**Comment by pascalkania** [comment]
@nartc hey great feature. can i use it for requests and responses? or only for requests? and how can i tell the interceptor the source type?

**Comment by boy51** [comment]
In the project I'm working on we do all the mapping in services, so I wouldnt use an interceptor for mapping responses personally. Also, its not very expressive. Its a good feature, but it wouldnt be my suggested approach personally, but I might be wrong and many people out there are mapping in their controllers.

**Comment by nartc** [comment]
@pascalkania something like

```ts
@UseInterceptor(MapInterceptor(SomeDto, Some, {isArray: boolean, mapperName?: string}))
```

@boy51 thanks for the feedback. Yeah, I don't usually use an Interceptor like this in my project either but it's just an extra feature for people who want it. Like the `CacheInterceptor` where you can use `cacheManager` or you can use `UseInteceptor(CacheInterceptor)`
