### ISSUE TITLE
[nestjs] MapInceptor returns empty response for Promise

### ISSUE THREAD

**Issue by VladDobrovolskiy** [nartc/mapper#247]
I tried to follow this guide https://automapperts.netlify.app/docs/nestjs

But it feels like MapInterceptor does not work with promises.

Here're my two code samples:

1) This one works like a charm:
```typescript
  @Get()
  async get(@User() firebaseUser: FirebaseUser): Promise<UserProfileVM> {
    try {
      const foundUser = await this.userProfilesService.getUserProfileByFireID(
        firebaseUser.uid,
      );

      return this.mapper.map(foundUser, UserProfileVM, UserProfileDto); 
    } catch (exception) {
      this.throwHttpException(exception);
    }
  }
  ```
  
2) This one does not work:
```typescript
  @Get()
  @UseInterceptors(MapInterceptor(UserProfileVM, UserProfileDto))
  async get(@User() firebaseUser: FirebaseUser): Promise<UserProfileDto> {
    try {
      return await this.userProfilesService.getUserProfileByFireID(
        firebaseUser.uid,
      );
    } catch (exception) {
      this.throwHttpException(exception);
    }
  }
  ```
**The endpoint returns empty body in http response.**

I really like the new approach with interceptors but I don't know how to use them here.
Help me please.

**Comment by nartc** [comment]
Would you be able to provide a sample reproduce repo? I can't seem to reproduce this with my setup.

**Comment by notmedia** [comment]
@VladDobrovolskiy I think you should use MapInterceptor as follows (first argument is "TO", and the second argument is "From":
```ts
@UseInterceptors(MapInterceptor(UserProfileDto, UserProfileVM))
```

By the way, @nartc is it possible (or can be a future request) to use MapInterceptor before route handle?
In case when I get DTO object and want convert it to something different. Or it's a bat pattern and I should do it on service layer?

**Comment by notmedia** [comment]
Created an issue - https://github.com/nartc/mapper/issues/275 :)
