### ISSUE TITLE
[nestjs] ESLint error: `@typescript-eslint/no-useless-constructor` on Profile code example

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#248]
Hi!

When trying to fix this lint error by removing the "useless" constructor (like the one bellow)
https://github.com/nartc/mapper/blob/618745362e1252ac4a105d28ec79abcc279bc8f8/packages/nestjs-integration-test/src/app/profiles/user.profile.ts#L8-L11
I'm getting this TypeScript error:
```
Type 'typeof UserProfile' is not assignable to type 'Provider<any>'.
  Type 'typeof UserProfile' is not assignable to type 'Type<any>'.
    Cannot assign a 'protected' constructor type to a 'public' constructor type.ts(2322)
```
when passing the profiler class to the `providers` array, due to `protected` on:
https://github.com/nartc/mapper/blob/6a0774b6889f211e6af46067385ac49b530556ea/packages/nestjs/src/lib/abstracts/automapper-profile.abstract.ts#L6

To fix both these errors I just add the `readonly` modifier to the `mapper` member on my profile code.

Is this expected to happen?

thanks in advance!

**Comment by nartc** [comment]
In NestJS, it is very common to have an abstract base class and pass injected (via dependency injection) services down to the base class (the same could apply to Angular as well). I’d suggest turning this rule to “off” for NestJS/Angular.

**Comment by micalevisk** [comment]
Got it!

I'm fine with that. Thank you.
