### ISSUE TITLE
Use mapper.map throw error Mapping not found 

### ISSUE THREAD

**Issue by zieglar** [nartc/mapper#249]
**Is your feature request related to a problem? Please describe.**
I create MappingProfile with DoctorEntity and DoctorInfoDto in nestjs project
When I use `this.mapper.mapArray(records, DoctorInfoDto, DoctorEntity)`
result is ok,
But When I use `this.mapper.map(record, DoctorInfoDto, DoctorEntity)`
throw error `Mapping not found for source function Array() { [native code] } and destination function Array() { [native code] }`

```
TypeError: mapping is not iterable
    at map (/Users/zieglar/Code/project/node_modules/@automapper/core/src/lib/map/map.js:99:85)
    at mapReturn (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:68:12)
    at mapArray (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:199:31)
    at map (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:152:27)
    at Object.mapReturn (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:68:12)
    at Object.map (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/create-mapper/create-mapper.js:48:30)
    at DoctorV1Service.buildDoctorDetail (/Users/zieglar/Code/jkys-api/dist/api/v1/doctor-v1.service.js:143:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DoctorV1Controller.getDoctorDetail (/Users/zieglar/Code/jkys-api/dist/api/v1/doctor-v1.controller.js:56:16)
```
use `this.mapper.mapArray([record], DoctorInfoDto, DoctorEntity)` is ok...

**Describe the solution you'd like**
fix this error

**Comment by nartc** [comment]
Hi @zieglar , can you please provide DoctorInfo and DoctorInfoDto models? It’d be awesome if you could provide a simple reproduce repo as well. Thanks

**Comment by zieglar** [comment]
```
@ChildEntity('doctor')
export class DoctorEntity extends EmployeeEntity {
  @AutoMap()
  @Column({ default: '' })
  expert: string;

  @AutoMap()
  @Column({ type: 'simple-array', default: [] })
  titleTags: string[];

  @Column({ type: 'simple-array', default: [] })
  serviceTags: string[];

  @Column({ default: '' })
  description: string;

  @AutoMap()
  @Column({ default: 0 })
  totalPatients: number;

  @AutoMap()
  @Column({ default: 0, type: 'float' })
  ratingRate: number;

  constructor(item?: Partial<DoctorEntity>) {
    super();
    if (item) Object.assign(this, item);
  }
}
```

```
export class EmployeeEntity extends BaseUIDWithEnabledEntity {
  @AutoMap()
  @Column({ length: 50 })
  name: string;

  @AutoMap()
  @Column({
    enum: GenderType,
    default: GenderType.MALE,
    type: 'enum',
  })
  gender: GenderType;

  @AutoMap()
  @Column({ default: '', length: 200 })
  avatar: string;
}
```

```
export class DoctorInfoDto {
  @AutoMap()
  id: string;

  @AutoMap()
  name: string;

  rank: string;

  @AutoMap()
  avatar: string;

  @AutoMap()
  titleTags: string[];

  departmentName: string;

  hospitalName: string;

  @AutoMap()
  expert: string;

  serviceTags: ServiceTag[];

  @AutoMap()
  totalPatients: number;

  @AutoMap()
  ratingRate: number;

  price: number;
}
```

```
      mapper
        .createMap(DoctorEntity, DoctorInfoDto)
        .forMember((d) => d.departmentName, fromValue('null'))
        .forMember((d) => d.hospitalName, fromValue('null'))
        .forMember(
          (d) => d.rank,
          mapFrom((s) => DoctorRankName.get(s.rank)),
        )
        .forMember(
          (d) => d.serviceTags,
          mapFrom((s) =>
            s.serviceTags.map((tag) => {
              return {
                name: BaseServiceNames.get(tag),
                ...BaseServiceConf.get(tag),
              };
            }),
          ),
        );
```

**Comment by nartc** [comment]
Can I also have a sample `record` as the source object to map?

**Comment by zieglar** [comment]
```
DoctorEntity {
  id: '1e91d2be-e191-41ac-a0ad-83cc77283f5c',
  createdAt: '2021-01-21 15:45:04',
  updatedAt: '2021-01-21 15:45:04',
  enabled: true,
  name: 'aaa',
  gender: 'male',
  mobilePhone: '11111111111',
  username: '11111111111',
  idNumber: null,
  isRealNameAuth: false,
  avatar: '',
  birthday: '',
  age: 48,
  middleStageUserId: null,
  type: 'doctor',
  level: '',
  expert: 'abc',
  rank: 'deputyChiefPhysician',
  titleTags: [ 'aaa', 'ccc' ],
  serviceTags: [ 'aa', 'vv', 'cc' ],
  description: 'description',
  totalPatients: 0,
  ratingRate: 0,
  recommendedRating: 100,
  index: 1,
  showOnIndex: true
}
```

**Comment by zieglar** [comment]
> The stacktrace
> 
> ```
> TypeError: mapping is not iterable
>     at map (/Users/zieglar/Code/project/node_modules/@automapper/core/src/lib/map/map.js:99:85)
>     at mapReturn (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:68:12)
>     at mapArray (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:199:31)
>     at map (/Users/zieglar/Code/jkys-api/node_modules/@automapper/core/src/lib/map/map.js:152:27)
> ```
> 
> tells me that it errors out at this line:
> 
> ```ts
> setMember(mapArray(mapInitializedValue, nestedDestinationMemberKey, nestedSourceMemberKey, undefined, mapper, errorHandler));
> ```
> 
> which means that Automapper is trying to map an Array of Object that **wasn't configured** with `forMember()` (hint: `mapInitializedValue`). Looking at the models you provide, I don't see any properties that have a type of `SomeModel[]`. So, can I also have a sample `record` (that you used to produce this bug) as the source object to map?
> 
> PS: I can also see that the error message isn't that helpful which I can try to make that better in the next release.

But why mapArray can map it?

**Comment by nartc** [comment]
Are you available for a video call so I can take a closer look at your current implementation? `DoctorEntity` does not look complicated at all so it should map fine. I've no idea why `map` does not work and `mapArray` works.

**Comment by zieglar** [comment]
send you mail :)
