### ISSUE TITLE
[classes] mapping throwing `TypeError: Cannot read property 'toString' of undefined` error

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#250]
Hey!

what I got:

```
(node:165517) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.getMapping (x/node_modules/@automapper/classes/src/lib/classes.js:61:76)
    at map (x/node_modules/@automapper/core/src/lib/map/map.js:157:46)
    at Object.mapReturn (x/node_modules/@automapper/core/src/lib/map/map.js:68:12)
```

L102 bellow throws this error when I invoke `this.mapper.map` (or `this.mapper.mapAsync`) on some Nestjs's `Injectable`  
but I'm still figuring out why this happen so then I'll make a minimal reproduction if needed

https://github.com/nartc/mapper/blob/705cbecee34d935669de4f1678eb980ef7af4fd4/packages/classes/src/lib/classes.ts#L95-L102

I'm open this issue just so you can take a note or something (:

---

- `@automapper/*`: v1.0.4
- Nodejs: v14.15.1

**Comment by nartc** [comment]
`source` and `destination` should not be `undefined` when invoking `getMapping`. Can you provide a minimal reproduction?

**Comment by micalevisk** [comment]
I have this field on my source class:

```ts
@Column({ type: 'varchar', nullable: true, default: () => 'NULL' })
@AutoMap()
username: string | null
```
(which has a non-null value in `sourceObj`)

this error doens't happen if:
- I remove the `@Column(...)` decorator
- or I remove the `| null` type

But I'm struggling to reproduce this here: https://codesandbox.io/s/nestjsautomapper-idin1 so I think I'm missing something.

**Comment by nartc** [comment]
@micalevisk I have a feeling this is the case where `tsconfig` plays a role here. For debugging this (or any error in AutoMapper), you can open `node_modules/@automapper/*` and putting breakpoints in relevant `*.js` files. For example, when you invoke `this.mapper.map(...)`, you want to put a breakpoint in `create-mapper.js` where `map()` is defined and also `map.js` is the actual `map` function. 

`createMapper` (https://github.com/nartc/mapper/blob/main/packages/core/src/lib/create-mapper/create-mapper.ts#L47)
`map` (https://github.com/nartc/mapper/blob/main/packages/core/src/lib/map/map.ts#L196)

**Comment by nartc** [comment]
`string | null` works in [integration-tests](https://github.com/nartc/mapper/blob/main/packages/integration-test/src/lib/with-classes/with-union.spec.ts)

**Comment by micalevisk** [comment]
You were right! I just update the `tsconfig.json` in the minimal reproduction [here](https://codesandbox.io/s/nestjsautomapper-idin1) then this error manifests due to `"strictNullChecks": true`

**Comment by nartc** [comment]
Did you update the reproduction? I wasn't able to see the error in the reproduction. Can you double-check?

If this is the case, there's really nothing I can do from the library stand-point because of Reflection depending on `tsconfig`. If you do `@AutoMap(() => String)`, would it work? If yes, I'd consider adding this note to the documentations as an action item for this issue. What's your suggestion?

**Comment by micalevisk** [comment]
> Did you update the reproduction? I wasn't able to see the error in the reproduction. Can you double-check?

Yes
![demo](https://user-images.githubusercontent.com/13461315/106374425-e29b4d80-6359-11eb-81a6-85bc694d6416.png)

> If this is the case, there's really nothing I can do from the library stand-point

Got it. So this implementation differs from `@narct/autommer` right?

> `@AutoMap(() => String)`, would it work?

No :/
This happen for any kind of union with `null`

**Comment by nartc** [comment]
@micalevisk https://codesandbox.io/s/nestjsautomapper-forked-3kids?file=/src/user.model.ts can you double check again? `() => String` should make it work.

**Comment by micalevisk** [comment]
Oh I see. I tested this only on destination class before but I just need to put this on source class, my bad.

There's no way to Automapper do this automatically for us?

**Comment by nartc** [comment]
Unfortunately no. If you annotate a property with `string | null`, `Reflect.getMetadata()` will return `Object {}`. Same thing applies to `number | null`, `boolean | null`.

```
number | null -> Object {}
boolean | null -> Object {}
```

Automapper cannot determine the correct metadata for this property. The old `@nartc/automapper` assigns `undefined` to the metadata which "magically makes this work" but that is not technically correct.

**Comment by micalevisk** [comment]
I got it! thank you.
