### ISSUE TITLE
What is the best way to map all `null` values to `undefined`?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#251]
Hi!

I need to transform `null` to `undefined` for every property regardless of the source and destination objects.
 
Should I create a plugin to do *only* this for me, or do you recommend that I stay with [`nullSubstitution(undefined)`](https://automapperts.netlify.app/docs/mapping-configuration/null-substitution)?

**Comment by nartc** [comment]
A custom plugin would work but the docs on creating a custom plugin is a little lacking as of this moment so I wouldn't recommend it. Basically in this case, the custom plugin behaves exactly the same as `classes` plugin with a custom `preMap()` function. If you'd like to venture in this more, reach out to me via email and I can walk you through this.

Another solution is to use `afterMap()` instead. 

```ts
mapper.createMap(Child, ChildDto)
   .afterMap((source, destination) => {
      // run your custom logic to turn all `null` to `undefined`
      // you can make this a reusable function to use on all `afterMap()`
   })
```

**Comment by nartc** [comment]
I just tested with a custom plugin that extends `classes` plugin like following:

```ts
const customClasses = (errorHandler: ErrorHandler) => {
    function nullify(srcObj: Record<string, unknown>) {
      for (const srcKey in srcObj) {
        if (srcObj[srcKey] === null) {
          srcObj[srcKey] = undefined;
        }

        if (
          typeof srcObj[srcKey] === 'object' &&
          !Array.isArray(srcObj[srcKey])
        ) {
          nullify(srcObj[srcKey] as Record<string, unknown>);
        }
      }
    }

    const originalClasses = classes(errorHandler);

    const originalPreMap = originalClasses.preMap;
    originalClasses.preMap = (...args) => {
      const originalPreMapResult = originalPreMap(...args);
      nullify(originalPreMapResult[0]);
      return originalPreMapResult;
    };

    return originalClasses;
  };

  const mapper = createMapper({
    name: 'customClasses',
    pluginInitializer: customClasses,
  });
```

It works for my simple models but maybe give this a try for your case?

**Comment by micalevisk** [comment]
I like your solution but it didn't work for `mapArray` :confused:

**Comment by nartc** [comment]
Just realized I didn't have mapArray to run through the preMap which is an easy fix.

**Comment by nartc** [comment]
Try 1.2.0 out and also check out the updated [with-extend-plugin.spec.ts](https://github.com/nartc/mapper/blob/main/packages/integration-test/src/lib/with-classes/with-extend-plugin.spec.ts#L37)

**Comment by micalevisk** [comment]
I just face an issue regarding that plugin. If the source obj has a field with the value `null` when calling `mapper.map`, inside of `mapFrom`'s callback I'll get  
`s.nullableField === undefined` instead due to the `preMap` that is ran prior `mapFrom`'s callback, I guess

But then, if I I write some manual mapping that should map `null` to any other thing rather than `undefined`, the `source` parameter of `mapFrom`'s callback won't tell me that that field could be `undefined` (of course), thus I might end up checking `isNull(s.nullableField)` instead of checking if it is `null` or `undefined`, which will lead to wrong mappings

Do you know any workaround? I tried `preCondition` and `mapDefer` but every callback runs after the logic made on that custom plugin, so I'm always getting `undefined` instead of `null`

My goal here is to make the manual mapping run before the custom plugin somehow. Not sure if this will remain the same in the next major version

**Comment by nartc** [comment]
@micalevisk can you provide some sample profiles? It's hard to visualize :D (and I can test your use-case against the new version as well)

**Comment by micalevisk** [comment]
there you go: https://replit.com/@micalevisk/automapper#index.ts

I'll problably drop the custom plugin and write those mapping from `null` to `undefined` manually, tho
