### ISSUE TITLE
[core] How can I use `mapWith` with arrays?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#253]
Hey!

I'm trying to use [`mapWith`](https://automapperts.netlify.app/docs/mapping-configuration/map-with) when the `source` and `destination` values are arrays. Is there a way to do this?

What I've done: 

```typescript
mapper.createMap(User, UserDto).forMember(
  (d) => d.someArrayField,
  mapWith(
    () => XDto,
    (s) => [], // the mapper will return an XDto instance instead of this value
    () => X
  )
)
```

I see that is a limitation due to these lines:
https://github.com/nartc/mapper/blob/1331bbf39457103415e64ef399837addca321328/packages/core/src/lib/member-map-functions/map-with.ts#L24-L26
since if I use `mapper.mapArray` instead, it will work as I expected.

To test that you could use this:
https://github.com/nartc/mapper/blob/618745362e1252ac4a105d28ec79abcc279bc8f8/packages/integration-test/src/lib/with-classes/fixtures/profiles/user-profile.profile.ts#L21-L25
but changing `.avatar` to `.addresses`, `AvatarVm` to `AddressVm` and `Avatar` to `Address` _(I didn't test this tbh)_

---

My use case is basically like this:

```typescript
class A {
  // ...
  @AutoMap(() => B)
  b: B[]
}

class B {
  // ...
  @AutoMap(() => C)
  c: C
}

class C {}

class AVm {
  @AutoMap(() => CVm)
  c: CVm[] // I want to extract this from B[]
}

class CVm {}
```

**Comment by micalevisk** [comment]
I've managed to do this kind of mapping with `@nartc/automapper` so the [migration guide](https://automapperts.netlify.app/docs/migrations#migrate-from-nartcautomapper) should have some thoughts about that, right? :confused:

**Comment by nartc** [comment]
@micalevisk Thanks for reporting. Please try 2.0.1 out

**Comment by micalevisk** [comment]
@nartc it works now! ty
