### ISSUE TITLE
Is there any way to initialize/define destination members using external (runtime) data and its source obj?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#255]
Hi!

What I want to achieve in my Nestjs app is somehow like this:

```typescript
class User { // instances of this class will come from database layer
  @Automap()
  id: number
}
class UserVm {
  @Automap()
  id: number
 
  something: number
}

// at UserController class 
requestHandler(valueFromReqUser) {
  // ...
  // const users = db.findAll()
  this.mapper.mapArray(users, UserVm, User, {
    afterMap: (source, destination) => {
      destination.forEach((userVm, idx) => {
        userVm.something = this.userService.computeSomething(
          source[idx],
          valueFromReqUser,
        );
      })
    },
  })
}
```

but without the [map action](https://automapperts.netlify.app/docs/misc/callbacks#map-actions) part since this implies in, among other things, iterating twice over `users` array :confused: 

I know that this problem does not follows [.NET AutoMapper's Design Philosophy](https://jimmybogard.com/automappers-design-philosophy) since `UserVm` is not a subtype of `User` anymore, but what you think about this feature?

Maybe adding some sort of `mapElement` map action that will be called for each `sourceArray[i]` below before passing it to `mapReturn` like `mapReturn( mapElement(sourceArray[i]),...` :p idk

https://github.com/nartc/mapper/blob/a062a7774f8c1ecc9463f408f5a7c8d6c73c9e3d/packages/core/src/lib/map/map.ts#L384-L388

Note that I "can't" embed `valueFromReqUser` (and so add a computed property in `User`) due to design constraints of my application.

**Comment by nartc** [comment]
I see what you mean. It's not impossible. Here's what I'd propose:

## Proposal
Ability to map with runtime data as parameters then use the passed-in parameters in the map configuration `forMember()`

## API
Either one of the following:
- Reuse `mapDefer` map function
   - pros: simplify public API because there's no new function. 
   - cons:

**Comment by micalevisk** [comment]
This is what I'm looking for!

I like the `mapParams` approach :smile:

**Comment by nartc** [comment]
@micalevisk I'm thinking `extraArguments` but feel free to keep throwing suggestions to this issue. I might not respond but I do read them all from my phone.

**Comment by nartc** [comment]
@micalevisk Please check out 2.2.0
The docs is here: https://automapperts.netlify.app/docs/mapping-configuration/map-with-arguments

**Comment by micalevisk** [comment]
This operation covers well my needs, ty! But it didn't work with `mapArray` -- `extraArguments` is `undefined` instead :confused:

**Comment by nartc** [comment]
Well looks like I was hasty. Lemme push a fix real quick

**Comment by nartc** [comment]
@micalevisk 2.2.1 published.
