### ISSUE TITLE
Two project same repo - @automapper/* and @nartc/automapper

### ISSUE THREAD

**Issue by m4ss1m0g** [nartc/mapper#257]
## Scenario
When I browse the GitHub repo I found a link to docs 
https://automapperts.netlify.app/

Looking for getter map on issue I found  

> Can this work with getter/setter? #51

Which send to version **3**, navigate to npm repository I found 
https://www.npmjs.com/package/@nartc/automapper

Which bounce to https://automapper.netlify.app/

## Solution 1
Clarify on GitHub README.md the different code and docs

## Solution 2
Split the current GitHub repo. Current GitHub README point to version 2.2.1 without mention version 7

**Comment by nartc** [comment]
Thanks for bringing this up. I'll update all references accordingly.
