### ISSUE TITLE
namingConventions doesn't work

### ISSUE THREAD

**Issue by m4ss1m0g** [nartc/mapper#258]
## Scenario  

I have a class with only getter (DDD approach) and I want to map all of my gets to TypeORM entity, since my RootAggregate has getter the name of private properties starts with  `_` character. 

## What I want to achieve  
I would to map source properties `_myProperty` to `myProperty`. 
I wrote a new NamingConvention class and applied to the mapper but it doesn't work. I don't know if there any alternative to achieve what I want.

## Repro code

``` typescript
import { NamingConvention } from "@automapper/types";

export class UnderscoreCaseNamingConvention implements NamingConvention {
    separatorCharacter = "";
    splittingExpression = /_/;

    public transformPropertyName(sourcePropNameParts: string[]): string {
        return "_" + sourcePropNameParts.join();
    }
}

// ---------

export class FooDTO {
    name: string;
}

export class Foo {
    _name: string;
}

const foo = new Foo();
foo._name = "hello";

const mapper = createMapper({
    name: "mymapper",
    pluginInitializer: classes
});

mapper.createMap(Foo, FooDTO, {
      namingConventions: {
          source: new UnderscoreCaseNamingConvention(),
          destination: new CamelCaseNamingConvention(),
      },
});

const dto = mapper.map(foo, FooDTO, Foo);
console.log(dto);
```

## Expected output

``` json

FooDTO {
    "name": "hello"
}
```

## Actual output

`FooDTO {}`

**Comment by micalevisk** [comment]
It will do work if you add `@AutoMap()` in your `name` prop on these classes

**Comment by m4ss1m0g** [comment]
Thanks for your response, unfortunately I cannot modify the Aggregate class, there's a plan to support the described scenario without the `@Automap()` attribute ?

**Comment by micalevisk** [comment]
It was possible to do that with the old automapper lib made by @nartc (`@nartc/automapper`) by using a _transformer plugin_ as described [here](https://automapper.netlify.app/docs/plugin). I don't know if @nartc is planning to add this feature here as well :confused:

**Comment by nartc** [comment]
@micalevisk It depends. The transformer plugin might work if the `Aggregate` class is in the code base. But if it's in an external library, then the plugin wouldn't work. I do plan on adding a plugin to the `classes` package.
@m4ss1m0g Thanks for reporting the issue. Unfortunately, AutoMapper needs to know the metadata (properties) of `Aggregate` class to be able to **automap** things. 
> there's a plan to support the described scenario without the @Automap() attribute ?
It is possible (but not implemented yet) by providing a method from `classes` for the consumers to provide metadata for a certain class. Eg: `extraMetadata(Aggregate, { ... })` with `{...}` being an object with the properties and the data type. This is essentially how `pojos` work atm (https://automapperts.netlify.app/docs/plugins-system/introduce-to-pojos). Regardless of the solution, you'd still need to do some **manual** work to provide the metadata of the classes for AutoMapper to work.

**Comment by nartc** [comment]
Please track #261 in regards to **auto-decorate** members with a transformer plugin.

**Comment by nartc** [comment]
3.0.5 has been released with the transformer plugin. https://github.com/nartc/mapper/releases/tag/3.0.5
