### ISSUE TITLE
POJOs createMetadataMap does not support enum type

### ISSUE THREAD

**Issue by johnpankowicz** [nartc/mapper#262]
I modified the sample in the POJOs Introduction to add an enum type to User & UserDto:

```
export enum GenderType {
  unspecified = 0,
  male = 1,
  female = 2,
}

export interface User {
  // skip
  gender: GenderType;
}

export interface UserDto {
  // skip
  gender: GenderType;
}

```

I then try to store metadata for User:

```
createMetadataMap<User>("User", {
   // skip,
   gender: GenderType
});
```
Intellisense gives me the following error:

`'typeof GenderType' is not assignable to type 'string | StringConstructor | DateConstructor | NumberConstructor | BooleanConstructor'`

Are enums not supported for POJOs? Is there a way around this?

[ I am using POJOs because my DTOs are auto-generated by swagger, so I can't manually add "@AutoMap()" decorators. ]

**Comment by nartc** [comment]
Enum is either String or Number. AutoMapper does not care if a property is an Enum type because at rubtime, it is either string or number. Please try either one of them for Enum.

**Comment by johnpankowicz** [comment]
Yes, thanks. that worked. I could leave the field as a enum in User  & UserDto, change it in createMetadataMap, and it mapped OK.
