### ISSUE TITLE
[nestjs] How can I use `this` inside `mapProfile` method in some profile class

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#264]
Hey!

Let's say I've this profile:

```typescript
@Injectable()
export class UserProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper)
  }

  mapProfile() {
    return (mapper) => {
      mapper.createMap(User, UserDto)
    }
  }
}
```

Since I can inject dependencies via constructor like:

```typescript
  constructor(@InjectMapper() mapper: Mapper, @Inject(token) appConfig: AppConfig) {
    super(mapper)
    console.assert(this.appConfig !== undefined) // ✅
  }
```

What is the proper way (if any) to use my `this.appConfig` prop in `mapProfile` while creating mappings? **(AKA how to create mappings dynamically(?))**

I'm trying to create a mapping only if it is in development mode (`this.appConfig.isDev`), but inside `mapProfile` method, `this.appConfig` is `undefined` :confused:

```typescript
  mapProfile() {
    return (mapper) => {
      console.assert(this.appConfig !== undefined) // ❌
      mapper.createMap(User, UserDto)
    }
  }
```

I understand that `mapProfile` is called by `AutomapperProfile` (when doing `super(mapper)`)

**Comment by nartc** [comment]
You can assign it to a variable in mapProfile. 

```ts
mapProfile() {
   const appConfig = this.appConfig;
   return mapper => {
      console.assert(appConfig !== undefined)
   }
}
```

**Comment by micalevisk** [comment]
I'm still getting `undefined`

I've reproduced this [here](https://codesandbox.io/s/nestjsautomapper-issue-264-g3tsb?file=/src/user.profile.ts)

**Comment by nartc** [comment]
@micalevisk Check out 3.0.7 
I have to delay the `addProfile()` call to the micro task queue. Tbh, I'm not sure if it affects anything :) So please give it a try and lemme know. Thanks

**Comment by micalevisk** [comment]
It works now, ty :)

**Comment by nartc** [comment]
@micalevisk feel free to submit a PR to change it :D
