### ISSUE TITLE
Basic implementation of Transform Plugin not working

### ISSUE THREAD

**Issue by isaackearl** [nartc/mapper#267]
Hello again!

I'm attempting to use the Transform Plugin, so I can avoid using AutoMap() while still doing most non-standard transformations in the fluent syntax.  I've added the plugin as such:

```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@automapper/classes/experimental/transformer-plugin",
        "options": {
          "modelFileNameSuffix": [".dto.ts", ".entity.ts"]
        }
      }
    ]
  }
}
```

in the project I posted previously here: https://github.com/isaackearl/sequelize-automapper-nestjs (I made a new commit)

I ran ```npm run build``` and ```npm run start:prod``` so I would use the dist files.

in the javascript versions of the classes I can see the metadata markup added that is described in the docs.  
```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FooDto = void 0;
class FooDto {
    static __AUTOMAPPER_METADATA_FACTORY__() {
        return [["id", { typeFn: () => Number }], ["bar", { typeFn: () => String }]];
    }
}
exports.FooDto = FooDto;
//# sourceMappingURL=foo.dto.js.map
```
The "bar" property is manually mapped in the fluent syntax, but "id" is not.

the Foo (model) has similar markup and also has an id property at the same level.  Here is my service method where I'm mapping
```
  findOne(id: number) {
    const foo = new Foo();
    foo.bar = 'baz';
    foo.id = 1;
    return this.mapper.map(foo, FooDto, Foo);
  }
```
and here is the output
```
{
    "bar": "baz"
}
```

I would expect the id to appear as well.  Am I using the plugin incorrectly?

**Comment by nartc** [comment]
Thanks for submitting this issue. It was a bug. Please try updating to 3.0.10 and let me know

**Comment by isaackearl** [comment]
@nartc just tested it out and it seems to work great now.  Thanks!
