### ISSUE TITLE
Ability to map multiple sources to 1 destination

### ISSUE THREAD

**Issue by Yagorundy** [nartc/mapper#269]
I couldn't find a good way to map 2 sources to 1 destination object.

There exists a way to do this but it logs that there are unmapped properties, because it expects each source object to contain all of the destination object properties.
Another thing you can do is merge all small source objects into 1 big source object. This approach solves most simple use cases, but let's say your source objects have one common prop `value` and each source object has a different mapping configuration for the destination object. Merging the source objects would be a bad idea.

I would love a solution where you can map multiple source objects into one destiation object. The possible errors I can think of after mapping all source objects to the destionation object could be:
- there are unmapped properties in the destination object
- there is a property in the destination object that was being assigned value multiple times

Let's say we have 3 classes - `A`, `B` and `Full`. Here are some uses that this new solution could bring:

Example 1
```
class A {
    @AutoMap()
    a: string
}

class B {
    @AutoMap()
    b: string
}

class Full {
    @AutoMap()
    a: string

    @AutoMap()
    b: string
}

mapper.createMap(A, Full)
mapper.createMap(B, Full)

// Just an example
const result = mapper.mapMany(Full, [{ sourceObj: sourceA, source: A }, { sourceObj: sourceB, source: B }])

// result should contain both 'a' and 'b' from 'A' and 'B' and there shouldn't be any logs
```

Example 2
```
class A {
    @AutoMap()
    value: string
}

class B {
    @AutoMap()
    value: string
}

class Full {
    @AutoMap()
    a: string

    @AutoMap()
    b: string
}

mapper.createMap(A, Full)
    .forMember(
        destination => destination.a,
        mapFrom(source => source.value)
    )

mapper.createMap(B, Full)
    .forMember(
        destination => destination.b,
        mapFrom(source => source.value)
    )

// Just an example
const result = mapper.mapMany(Full, [{ sourceObj: sourceA, source: A }, { sourceObj: sourceB, source: B }])

// result should contain both 'a' and 'b' and their values should be equal to A.value and B.value
```

**Comment by nartc** [comment]
Hi @Yagorundy , thanks for opening this issue. 

This is an interesting feature. In fact, it has been requested multiple times in the original .NET AutoMapper but it was never implemented. There is a reason. Let me explain why I am hesitant to implement this feature

AutoMapper flow has always been: `sourceObj` to a `Destination`. This request suggests the opposite way: a `Destination` from `multiple sources`. Although that sounds reasonable, but there are multiple problems to solve. Assume class `Full` here with `{a, b}` that need to be mapped. When multiple sources are used, AutoMapper cannot determine which source to map to which property of `Full`. Another problem is if `A` and `B` have overlapping properties that are going to be mapped to `Full`, then AutoMapper cannot determine which model to get the value from to map. 

The feature isn't impossible to implement, but it's very tricky and there's also no guarantee that it works properly or in a performant way.

>Another thing you can do is merge all small source objects into 1 big source object. This approach solves most simple use cases, but let's say your source objects have one common prop value and each source object has a different mapping configuration for the destination object. Merging the source objects would be a bad idea.

I would love to hear more about this issue you bring up. Normally, if I ran into the cases with `A`, `B`, and `Full` here, I would create something like:

```ts
class SomeFull {
   a: A;
   b: B;
}

mapper.createMap(SomeFull, Full)
   .forMember(d => d.a, mapFrom(s => s.a.value))
   .forMember(d => d.b, mapFrom(s => s.b.value))
   
   
const full = mapper.map({a: someA, b: someB}, Full, SomeFull);
```

**Comment by Yagorundy** [comment]
Hi again @nartc! I agree that the `multiple sources` idea is tricky to implement. I just thought it was a cool idea to mention 😄.

Regarding your solution for `A`, `B` and `Full` - I don't really like it, because you have to manually map each prop of `A` and `B` to `Full` when creating the map and this becomes frustrating if you have multiple props. (you can't use the goodness of `@AutoMap()`)

Thankfuly, my use case isn't very complicated. I just need to map some objects to one destination and the `sources` don't have overlapping props. I managed to solve it by creating a new map for a new class using the `extends` option.

```
class Full {
    @AutoMap()
    a1: string

    @AutoMap()
    a2: string

    @AutoMap()
    aCombined: string

    @AutoMap()
    b1: string

    @AutoMap()
    b2: string
}

class A {
    @AutoMap()
    a1: string

    @AutoMap()
    a2: string
}

class B {
    @AutoMap()
    b1: string

    @AutoMap()
    b2: string
}

// ...

mapper.createMap(A, Full)
    .forMember(
        dest => dest.aCombined,
        mapFrom(souce => souce.a1 + souce.a2)
    )
mapper.createMap(B, Full)

class ABtoFull { }
mapper.createMap(ABtoFull, Full, { extends: [mapper.getMapping(A, Full), mapper.getMapping(B, Full)] })

// ...

const result = mapper.map({ ...sourceA, ...sourceB }, Full, ABtoFull)
```

I am not really a fan of the fact that you need to create a new class just to merge `A` and `B` but this is how things work and you gotta do what you gotta do.

Anyways, you can close this issue whenever you feel like. Wish you all the best!

**Comment by Yagorundy** [comment]
Hi @nartc. Nah 😀
