### ISSUE TITLE
What about mapping destination to a subclass of destination?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#270]
Hi!

Basically, I need to perform this mappings:

```
A → AVm
    AVm → SubAVm
```

```ts
class A {
  @AutoMap()
  id: number

  // ... many others props with AutoMap here

  @AutoMap()
  internal: string
}

class AVm {
  @AutoMap()
  id: number

  @AutoMap()
  internal: string

  // ... many others props with AutoMap here

  // Something that cannot (or should not) be defined by Automapper
  foo: boolean
}

class SubAVm {
  @AutoMap()
  id: number

  @AutoMap()
  foo: boolean
}

//
mapper.createMap(A, AVm)
mapper.createMap(AVM, SubAVm)
```

If I add `@AutoMap()` to `foo` prop of `Avm` class I'll get `Unmapped properties` error when mapping `A` to `AVm` (but it will works well when mapping `AVm` to `SubAVm`, of course)

Do you have any tips for me to circumvent this somehow? :confused:

**Comment by nartc** [comment]
If you have a lot of properties like `AVm#foo`, I guess it would make the most sense if AutoMapper had like a `Ignore()` decorator. However, I am very hesitant to add another decorator. Reusing `AutoMap` with some options like `AutoMap({ignore: true})` is also troublesome, eg: ignore for what model, keep for what model etc...

The best way right now is, unfortunately, manually configure `foo` 

```ts
mapper.createMap(A, AVm)
mapper.createMap(AVM, SubAVm)
   .forMember(d => d.foo, mapFrom(s => s.foo))
```

If you think of a proposal, feel free to submit a RFC, I'm more than happy to discuss solutions.

**Comment by micalevisk** [comment]
unfortunately in my case `AVm#foo` cannot be defined by automapper. Maybe the way that I'm using it with autommaper is not that good. I'll try to improve this things here and I'll rethink about this, ty!

---

Basically I'm using Automapper to create the object that will be saved on my session store _(retrived by, lets say, `req.session.user` from Express)_. But I need to expose this same object but without some fields, this is where the mapping `AVm` to `SubAVm` arise.

**Comment by nartc** [comment]
Ah, if the properties cannot be in the metadata at all then your next best bet would be to use an `afterMap`
