### ISSUE TITLE
MapPipe for NestJS applications

### ISSUE THREAD

**Issue by notmedia** [nartc/mapper#275]
**Is your feature request related to a problem? Please describe.**
In https://github.com/nartc/mapper/issues/247#issuecomment-793155152 we have conversation about case when you need to map incoming objects instead of outgoing.

**Describe the solution you'd like**
I have and idea with use Interceptor for this, @nartc says that this can be done with pipe something like MapPipe

**Comment by nartc** [comment]
Released in 3.4.0 https://automapperts.netlify.app/docs/nestjs#mappipe

**Comment by notmedia** [comment]
Wow! Thank you 🔥

**Comment by nartc** [comment]
Please open new issues if you run into any problems 👍
