### ISSUE TITLE
Objects are surrounded by angular brackets instead of curly brackets. Many compile errors are thrown.

### ISSUE THREAD

**Issue by i-kapri** [nartc/mapper#286]
After I have installed all the four packages under `@automapper` following the [installation instructions](https://automapperts.netlify.app/docs/getting-started/installation) I receive the following error message a great deal of times during compilation of my project:

`ERROR in node_modules/@automapper/types/src/plugin.d.ts:27:94 - error TS1005: ',' expected.`

in the code line 27 of your file `plugin.d.ts` : 

`instantiate<TModel extends Dictionary<TModel> = any>(model: any, obj?: TModel): [instance: TModel, nestedMetadata?: any[]];`

I have tried many things including: `"skipLibCheck": true,` in the `tsconfig.json` file as well as `"exclude": "./node_modules/*"` etc. etc. but the errors are still being thrown.

Maybe I should target "ES6" because my actual target is "ES2015"

Do you have any idea about why this is happening?

Thank you in advance!
Kapri

**Comment by nartc** [comment]
Are you using this in an Angular project? What Angular version you’re running? Can you provide more information about the environment? Can you provide a reproduce?

**Comment by i-kapri** [comment]
> Are you using this in an Angular project? What Angular version you’re running? Can you provide more information about the environment? Can you provide a reproduce?

Yes, an Angular project. The version of my Angular CLI is 10.2.0 and I am using it with TypeScript v3.9.5 as well as a target to es2015. This is read as an erroneous: `instantiate<TModel extends Dictionary<TModel> = any>(model: any, obj?: TModel): [instance: TModel, nestedMetadata?: any[]];` maybe because it prefers it as `... : { instance: TModel, nestedMetadata?: any[] }`.

**Comment by nartc** [comment]
@i-kapri Thanks for providing this info. Can you try upgrading Typescript to 4.0?

**Comment by i-kapri** [comment]
Problem solved! Thank you Mr. Tran!
