### ISSUE TITLE
Why did using a simple computed property name doesn't map properly?

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#289]
Hi!

Basically this, for instance:

```js
      mapper
        .createMap(User, UserVm)
        .forMember(
          (d) => d.first, // works ✅
          mapFrom((s) => s.firstName)
        )
//
      mapper
        .createMap(User, UserVm)
        .forMember(
          (d) => d['first'], // this does not ❌
          mapFrom((s) => s.firstName)
        )
```

the later will result in an empty string as prop key `''`

I'm trying to create a mapping to `"en-us"` property name. I can circumvent the usage of manual mapping by adding a getter method `get ['en-us'](){ return this['en-us'] }` in the source class, and with `SnakeCaseNamingConvention` naming convention.

---

- `@automapper/*`: `v3.5.2`

**Comment by nartc** [comment]
https://github.com/nartc/mapper/blob/c159560e839397327d74b93397f6dc6f64dcaf0f/packages/core/src/lib/create-mapper/get-member-path.util.ts#L4 this is a limitation atm. Feel free to poke around with `getMemberPathUtil` to see if you can come up with a better implementation to support that property.

**Comment by micalevisk** [comment]
oh I see this behavior documented here https://github.com/nartc/mapper/blob/c159560e839397327d74b93397f6dc6f64dcaf0f/packages/core/src/lib/create-mapper/specs/get-member-path.spec.ts#L64-L67

**Comment by micalevisk** [comment]
@nartc I'm thinking of supporting the following usages:

- for completeness:
  + `d => d['someThing']` (just like TypeORM does allow) But not the real computed property name ones like `d => d['some' + 'Thing']` because I think those usages are pretty complex to handle properly ATM _(I didn't understand how TypeORM support this but I'll probably take a look at it)_
  + nested mixed ones like `d => d['odd-prop'].foo` and `d => d.foo['odd-prop']`  
  Because currently `d => d['bar'].baz` is returning `"baz"`  
  And `d => d.bar['baz']` is returning `"bar['baz']"` 
  while `d => d.bar.baz` returns `"bar.baz"`
- `d => d['odd-prop']` and
- `d => d['odd_prop']` ones, to avoid polluting the source class with a bunch of getter methods. Thus fixing the [odd-property name limitation](https://automapperts.netlify.app/docs/misc/limitations/#odd-property-name) 

Is it worth it or nah? _(note that I'm not sure if I'll succeed implementing all of above but I can try)_

**Comment by nartc** [comment]
@micalevisk That works for me. One question on the 2nd bullet there: what would be your expected return value for `d => d.bar.baz`?

**Comment by micalevisk** [comment]
> One question on the 2nd bullet there: what would be your expected return value for `d => d.bar.baz`?

I expect `"bar.baz"`

which is already done https://github.com/nartc/mapper/blob/c159560e839397327d74b93397f6dc6f64dcaf0f/packages/core/src/lib/create-mapper/specs/get-member-path.spec.ts#L34

**Comment by nartc** [comment]
Cool. Just want to confirm. Feel free to submit the PR anytime, I'll review it.

**Comment by micalevisk** [comment]
I'm trying one solution locally. This is what I've got so far:

- for now, I'll treat only arrow functions for `fn: Selector`
- to the output of [`cleanseAssertionOperators`](https://github.com/nartc/mapper/blob/c159560e839397327d74b93397f6dc6f64dcaf0f/packages/core/src/lib/create-mapper/get-member-path.util.ts#L40) I'll apply [this regex](https://regexr.com/5shbb) to grab all prop names as an array of strings and them join with `.` to produces the output of [`getMemberPath`](https://github.com/nartc/mapper/blob/c159560e839397327d74b93397f6dc6f64dcaf0f/packages/core/src/lib/create-mapper/get-member-path.util.ts#L4)
- I'll try my best to optimize space and time to not penalize the users that doesn't care about that limitation 

<details>
<summary>my test suite</summary>

```js
describe('all allowed ones', () => {
  // all bellow are passing ✅
  const cases = [
   // ____ input ________  __ output __
   , [ s=>s["aaa"]        , ['aaa'] ]
   , [ s=>s['aaa']        , ['aaa'] ]
   , [ s=>s['ab-cd']      , ['ab-cd'] ]
   , [ s=>s['bad[foo]']   , ['bad[foo]'] ]
   , [ s=>s['aa']['bo"o'] , ['aa', 'bo\"o'] ]
   , [ s=>s['foo=>s[bar'] , ['foo=>s[bar'] ]
   , [ s=>s['.foo.bar']   , ['.foo.bar'] ]

   , [ s=>s['bbb'].bar , ['bbb', 'bar'] ]
   , [ s=>s.bbb['bar'] , ['bbb', 'bar'] ]

   , [ s=>s['aaa']['ddd']     , ['aaa', 'ddd'] ]
   , [ s=>s['aaa'].ccc['ddd'] , ['aaa', 'ccc', 'ddd'] ]

   , [ s=>s.bar['bad[foo]'] , ['bar', 'bad[foo]'] ]

   , [ s=>s.foo.bar , ['foo', 'bar'] ]
   , [ s=>s.foo     , ['foo'] ]

   , [ s=>s['á'] , ['á'] ]
  ].map(([fn, expected]) => [fn.toString(), expected])

  it('should return the expected members list', () => {
    cases.forEach(( [fnSelector, expected] ) => {
      assert.deepEqual(getMembers(fnSelector), expected)
    })
  })
})

describe('cases that are disallowed', () => {
  const cases = [
   , [ s=>s.á      , null ]
   , [ s=>s[`a`]   , null ]
   , [ s=>s.good.á , null ] // ❌ this is one is not passing yet
  ].map(([fn, expected]) => [fn.toString(), expected])

  it('should return the expected output', () => {
    cases.forEach(( [fnSelector, expected] ) => {
      assert.deepEqual(getMembers(fnSelector), expected)
    })
  })
})
```

</details>

<details>
<summary>my WIP solution</summary>

```js
/**
 * (not the final solution but it works)
 * @param {string} fnSelector Clean seralized arrow function expression.
 * @retuns {string[]}
 */
function getMembers(fnSelector) {
  const RE_HAS_COMPUTED_PROP = /(^\w+=>\w\[)|(\]$)/;

  if (!RE_HAS_COMPUTED_PROP.test(fnSelector)) {
    const re1 = /(?<=\.)\w+/g;
    return fnSelector.match(re1)
  }

  const re2 = /(?:(?<=\[)(['"]).+?\1)|(?:(?<=\.)(\w+))/g;
  let matches;
  // Maybe I could optimize the following by using `re2.exec`
  // instead to prevent doing `.map` and `.match`
  if (matches = fnSelector.match(re2)) {
    const RE_HAS_QUOTES = /^(['"]).+\1$/;
    return matches.map(match => {
      return match.match(RE_HAS_QUOTES)
          ? match.slice(1, -1) // drop the first and the last quotes
          : match
    })
  }
}
```

</details>

(you can explore the last used regex here: https://regexr.com/5shbb)

@nartc any thoughts about this approach?

**Comment by micalevisk** [comment]
@nartc nvm I just open the PR #293 ^^ few free to change anything
