### ISSUE TITLE
[Question] How to use the profile in nestjs properly

### ISSUE THREAD

**Issue by morishjs** [nartc/mapper#295]
Hi. I'm pretty new to use this library. I ran into the problem like below the screenshot.
I am currently using the mapper with nestjs but I have no idea how to use the profile.

Here is my `global-config.profile.ts` file
```typescript
import { Injectable } from '@nestjs/common';
import { AutomapperProfile, InjectMapper } from '@automapper/nestjs';
import { Mapper } from '@automapper/types';
import {
  CamelCaseNamingConvention,
  SnakeCaseNamingConvention,
} from '@automapper/core';
import { createMetadataMap } from '@automapper/pojos';

export interface IGlobalConfig {
  priceMarginRate: number;
}
export interface IGlobalConfigDAO {
  price_margin_rate: number;
}

@Injectable()
export class GlobalConfigProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
  }

  mapProfile() {
    createMetadataMap<IGlobalConfig>('GlobalConfig', {
      priceMarginRate: Number,
    });
    createMetadataMap<IGlobalConfigDAO>('GlobalConfigDAO', {
      price_margin_rate: Number,
    });

    return (mapper: Mapper) => {
      mapper.createMap<IGlobalConfig, IGlobalConfigDAO>(
        'GlobalConfig',
        'GlobalConfigDAO',
        {
          namingConventions: {
            source: new CamelCaseNamingConvention(),
            destination: new SnakeCaseNamingConvention(),
          },
        },
      );
    };
  }
}
```

The application always complains about the error when the app starts.

![image](https://user-images.githubusercontent.com/6479241/119065642-f659e500-ba18-11eb-9388-e598647523c6.png)

---

I try to use the mapper in a service like

```typescript
// Do something

    let configDAO: IGlobalConfig;
    try {
      const configDAO = this.mapper.map<IGlobalConfigDAO, IGlobalConfig>(
        globalConfig.value,
        'GlobalConfig',
        'GlobalConfigDAO',
      );
    } catch (e) {
      console.error(e);
    }
```

Do you give me a right suggestion for a configuration?

**Comment by nartc** [comment]
Hi @morishjs, that looks like a runtime error. Can you provide a reproduce repo?

**Comment by morishjs** [comment]
The code is managed in private repository so I invited you into the repository.

First code snippet resides in `src/global-config/global-config.ts` and the second is in `src/coupang/coupang.service.ts:46-55 lines` I commented code lines to run the application.

**Comment by nartc** [comment]
Thanks. I got the invite. Will take a look over the weekend.
