### ISSUE TITLE
Fields decorated with @AutoMap() are not mapped in Angular project

### ISSUE THREAD

**Issue by robsonhermes** [nartc/mapper#307]
Hi

I created a small angular sample project to try `@automapper`. However, I cannot get `@AutoMap()` to work. I can only map between types (classes) if I either manually define the mapping with `forMember` or if I initialize the fields in the destination class.

Using:
```
    "@automapper/classes": "^4.2.0",
    "@automapper/core": "^4.2.0",
```

Destination and source types:

```
import { AutoMap } from '@automapper/classes';

export class Foobar {
  @AutoMap()
  name: string;
}

export class FoobarDTO {
  @AutoMap()
  name: string;
}
```

Creating mapper
```
import { CamelCaseNamingConvention, createMapper } from '@automapper/core';
import { classes } from '@automapper/classes';

export const mapper = createMapper({
  name: 'foobarMapping',
  pluginInitializer: classes
});
```

Using the mapper:

```
mapper.createMap(FoobarDTO, Foobar);

const dto = new FoobarDTO();
dto.name = 'dude';

const user = mapper.map(dto, Foobar, FoobarDTO);
console.log(user)
```

Basically the destination user (of type Foobar) is empty. `name` attribute is undefined.

It works if I:

1. Manually map the field. But that kills the whole purpose of `@automapper`
```
mapper.createMap(FoobarDTO, Foobar).forMember(
       (destination) => destination.name,
       mapFrom((source) => source.name)
);
```

2. Or initialize the field in the destination class
```
export class Foobar {
  @AutoMap()
  name: string = '';
}
```

**Comment by nartc** [comment]
![image](https://user-images.githubusercontent.com/25516557/123271051-0d7f6d00-d4c6-11eb-96e8-7afbd1376ea9.png)
Make sure to turn on `emitDecorator: true` in `tsconfig`

**Comment by robsonhermes** [comment]
Thanks a lot for the quick reply, @nartc 
This did the trick indeed.

**Comment by robsonhermes** [comment]
Ops, sorry, I just read now your suggestion for a PR.
Will raise one soon.
