### ISSUE TITLE
Bump peerDeps for nestjs package

### ISSUE THREAD

**Issue by notmedia** [nartc/mapper#313]
Hi, nest released v8, can you bump it in peer deps?

**Comment by nartc** [comment]
@notmedia Trying to get #318 in before I cut a new release that have nestjs bump. FYI, it's working greay

**Comment by notmedia** [comment]
@nartc yeeeah, great 🚀

**Comment by notmedia** [comment]
@nartc I see you bumped nest packages in devDeps, but in peerDeps there are still ^7.0.0 versions

**Comment by nartc** [comment]
@notmedia well there goes my fast finger again. Releaseing 5.0.1 to bump the peerDeps :( sorry for the inconvenience
