### ISSUE TITLE
Nest can't resolve dependencies of the SectionsProfile (?)

### ISSUE THREAD

**Issue by jbeckton** [nartc/mapper#314]
Not sure why I am seeing this issue. I am using NestJs 8.

I have two modules AppModule and SectionsModule.

AppModule imports AutoMapperModule.forRoot() & SectionsModule.
SectionsModule imports AutoMapperModule and provides SectionsProfile.

When I try and start my app it fails. Any ideas as to why?

`export class SectionsProfile extends AutomapperProfile  {

  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
  }

  public mapProfile(): MappingProfile {
`

**Comment by micalevisk** [comment]
Hi! this snippet looks fine. Can you share the error message?

Also, the app works with Nest v7?

**Comment by jbeckton** [comment]
I upgraded to Nest v8 before installing Automapper. Should I try Nest v7?


`[Nest] 31452  - 07/16/2021, 12:50:47 PM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the SectionsProfile (?). Please make sure that the argument automapper:nestjs:default at index [0] is available in the SectionsModule context.

Potential solutions:
- If automapper:nestjs:default is a provider, is it part of the current SectionsModule?
- If automapper:nestjs:default is exported from a separate @Module, is that module imported within SectionsModule?
  @Module({
    imports: [ /* the Module containing automapper:nestjs:default */ ]
  })

Error: Nest can't resolve dependencies of the SectionsProfile (?). Please make sure that the argument automapper:nestjs:default at index [0] is available in the SectionsModule context.

Potential solutions:
- If automapper:nestjs:default is a provider, is it part of the current SectionsModule?
- If automapper:nestjs:default is exported from a separate @Module, is that module imported within SectionsModule?
  @Module({
    imports: [ /* the Module containing automapper:nestjs:default */ ]
  })

    at Injector.lookupComponentInParentModules (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:189:19)
    at Injector.resolveComponentInstance (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:145:33)
    at resolveParam (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:99:38)
    at async Promise.all (index 0)
    at Injector.resolveConstructorParams (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:114:27)
    at Injector.loadInstance (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:47:9)
    at Injector.loadProvider (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/injector.js:69:9)
    at async Promise.all (index 7)
    at InstanceLoader.createInstancesOfProviders (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
    at /Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/instance-loader.js:29:13
    at async Promise.all (index 7)
    at InstanceLoader.createInstances (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/instance-loader.js:28:9)
    at InstanceLoader.createInstancesOfDependencies (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/injector/instance-loader.js:18:9)
    at /Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/nest-factory.js:93:17
    at Function.asyncRun (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/errors/exceptions-zone.js:22:13)
    at NestFactoryStatic.initialize (/Users/Jesse/Projects/GCP/BasinsList/Backend/api/node_modules/@nestjs/core/nest-factory.js:91:13)`

**Comment by micalevisk** [comment]
> Should I try Nest v7?

Please.

But I think I know what's going on. I'd say that `@automapper/nestjs@4.2.2` is not compatible with nest v8.

**Comment by nartc** [comment]
automapper/nestjs has not been upgraded to use with v8. I'll do that over the weekend. The error seems straightforward, the `AutoMapperModule` should have the Mapper provided so it could be a bug here. I'll investigate further. Not being able to use v8 is not good at all.

**Comment by jbeckton** [comment]
ok so I downgraded to Nest v7 and got the same error. Then I changed the constructor on my Profile class to include the mapper name and now the app will run. Maybe it does work with v8 but the Profile constructor needed more info?


`export class SectionsProfile extends AutomapperProfile  {

  constructor(@InjectMapper('section') mapper: Mapper) {
    super(mapper);
  }

  public mapProfile(): MappingProfile {`

**Comment by jbeckton** [comment]
ok so I upgraded back to Nest v8 and it still works.

I think the issue may just be with the documentation, I just started using AutoMapper and it was not clear to me that when using...

`AutomapperModule.forRoot({
      options: [{ name: 'section', pluginInitializer: classes }],
      singular: false,
    }),`

that the Profile class constructor needed the additional info.

`@Injectable()
export class SectionsProfile extends AutomapperProfile  {

  constructor(@InjectMapper('section') mapper: Mapper) {
    super(mapper);
  }

  public mapProfile(): MappingProfile {`

**Comment by nartc** [comment]
https://automapperts.netlify.app/docs/nestjs#singular I would love to hear suggestions for this. I'm not a native speaker so my explanation might be confusing. You want to submit a PR to adjust the docs? And I assume you solved the issues?

**Comment by micalevisk** [comment]
The comment lines on this snippet taken from the docs is pretty clear to me. Did you read this part @jbeckton?

```typescript
// without singular

@Module({
  imports: [
    AutomapperModule.forRoot({
      options: [{ name: 'blah', pluginInitializer: classes }],
    }),
  ],
})
export class AppModule {}

@Injectable()
export class Service {
  // have to pass in the name of the mapper to InjectMapper
  constructor(@InjectMapper('blah') private blahMapper: Mapper) {}
  //                       ^^^^^^^^
}
```

---

but maybe it could be more explicit, like this:

```typescript
// without singular

@Module({
  imports: [
    AutomapperModule.forRoot({
      options: [{ name: 'blah', pluginInitializer: classes }],
      //                ^^^^^^
    }),
  ],
})
export class AppModule {}

@Injectable()
export class Service {
  // have to pass in the name of the mapper to InjectMapper
  constructor(@InjectMapper('blah') private blahMapper: Mapper) {}
  //                       ^^^^^^^^
}
```

**Comment by nartc** [comment]
@micalevisk ah that could help. Also emojis like 👇 / 👆 can also help in these cases.

**Comment by jbeckton** [comment]
@micalevisk I did see that part of the docs, But when I was implementing the Profile I was using this page. https://automapperts.netlify.app/docs/nestjs#profile

so I guess the previous slipped my mind.

Likely AutoMapper is unable to influence the Nest DI error to be more descriptive so it might be a better recommendation to always use the profile name in the injector?

**Comment by nartc** [comment]
@jbeckton That’d be very repetitive to do since InjectMapper is probably injected in a lot of places. That said, I’ll make it clearer in the docs. Thanks again for reporting
