### ISSUE TITLE
Skip undefine destination value when map mutate

### ISSUE THREAD

**Issue by huybn5776** [nartc/mapper#316]
For PATCH api, I only want to take the not null/undefined field from source to destination but not update all missing fields to undefined.

```typescript
const user = {
  firstName: 'foo',
  lastName: 'bar',
} as User;
const userDto = {
  lastName: 'what',
} as UserDto;

mapper.map(userDto, User, UserDto, user);

console.log(user);
// expected tobe { firstName: 'foo', lastName: 'what' } but { firstName: undefined, lastName: 'what' } 
```

This may implementation by add an `predicateFn` to `setMember()` of the `map.ts`, and add an option to enable this feature.
```typescript
// mapper/packages/core/src/lib/map/map.ts

const setMember = (valFn: () => unknown, predicateFn?: (destinationFieldValue: unknown) => boolean) => {
  try {
    const val = valFn();
    if (!predicateFn || predicateFn?.(val)) {
      setMemberFn(destinationFieldValue, destination)(val);
      return;
    }
  } catch (originalError) {
    // ...
  }
  // ...
  setMember(
    () =>
      mapMember(
        transformationMapFn,
        sourceObj,
        destination,
        destinationMemberPath,
        extraArguments,
        mapper,
      ),
    (destinationFieldValue) => destinationFieldValue !== undefined,
  )
}
```

I know this may be an unreasonable feature for AutoMapper, that it should map all fields from source to destination, but just to make patch process more simple.

**Comment by nartc** [comment]
Hi, thanks for reporting the issue. That seems like a bug for sure. And it seems like this is only applicable to `mapMutate` which means a `predicateFn` isn't necessarily needed in this case. We can adjust this directly for `mapMutate` https://github.com/nartc/mapper/blob/main/packages/core/src/lib/map/map.ts#L173 to check `destinationFieldValue` before running `setMutate()`. 

```ts
export function mapMutate<
  TSource extends Dictionary<TSource> = any,
  TDestination extends Dictionary<TDestination> = any
>(
  sourceObj: TSource,
  mapping: Mapping<TSource, TDestination>,
  options: MapOptions<TSource, TDestination>,
  mapper: Mapper,
  errorHandler: ErrorHandler,
  destinationObj: TDestination
): void {
  map(
    sourceObj,
    mapping,
    options,
    mapper,
    errorHandler,
    (destinationMember: string[]) => (value: unknown) => {
      // logic to check for undefined
      // this function has access to 
      // - value: the value on SourceObject
      // - sourceObj: the sourceObject itself
      // - destinationObj: the destinationObject itself
      setMutate(destinationObj, destinationMember, value);
    }
  );
}
```

Does it make sense? Would you like to submit a PR?

**Comment by huybn5776** [comment]
Is that a bug? I tried .NET version of AutoMapper and it give me the same result, that is mapping null value to destination.

If that is really an bug, then we can directly modify the behavior without add option to enable it. I will take over this part and make a PR.

**Comment by nartc** [comment]
@huybn5776 I've never used map mutably in .NET before so I'm not aware of its behavior. If that's the case, what would you do in .NET?

**Comment by huybn5776** [comment]
Still for PATCH request, this is the behavior of .NET version of AutoMapper.
```c#
public class User
{
    public string FirstName { get; set; } = default!;
    public string LastName { get; set; } = default!;
}
    
public class UserDto
{
    public string FirstName { get; set; } = default!;
    public string LastName { get; set; } = default!;
}

var user = new User
{
    FirstName = "foo",
    LastName = "bar"
};
var userDto = new UserDto
{
    FirstName = "Kung"
};
_mapper.Map<UserDto, User>(userDto, user);
// user = { FirstName = "Kung" }

```
In order to patch value, i write another method on my c# project to do this without using AutoMapper because it's hard to find out how to only patch non-null property when mapping with AutoMapper.

And for js version of AutoMapper, i think we can make it better without to do some workaround when someone need it.

**Comment by nartc** [comment]
@huybn5776 Yes. I think the proposed solution up there would be good to have as a default aka to ignore the value if the value is falsy. In the future, if other devs need to configure that, we can always add an option later. Please feel free to go ahead and submit a PR if you can. Thank you!

**Comment by huybn5776** [comment]
@nartc Did you expected to also apply patch for nested object?

```typescript
const user: User = {
  firstName: 'foo',
  profile: {
    bio: 'Introvert-ish',
    birthday: new Date('10/14/1991'),
  },
};
const userVm: UserVm = {
  profile: {
    bio: 'Outgoing-ish',
  },
};

mapper.map(userVm, User, UserVm, user);
console.log(user);

// current behavior: 
// { firstName: 'foo', profile: { bio: 'Outgoing-ish' } }
// nested patch:
// { firstName: 'foo', profile: { bio: 'Outgoing-ish', birthday: new Date('10/14/1991') } }
```

**Comment by nartc** [comment]
![image](https://user-images.githubusercontent.com/25516557/126076043-cb445b48-d2a7-466c-81a7-aac9859fe0a0.png)
I guess we need to consider this for nested object as well.
