### ISSUE TITLE
[feature] Custom Constructors

### ISSUE THREAD

**Issue by notmedia** [nartc/mapper#319]
Hi, when I have `book` in constructor I'm getting an error
```ts
@Entity({ tableName: 'user' })
export class User {
  @PrimaryKey({ type: 'uuid', defaultRaw: 'uuid_generate_v4()' })
  @AutoMap()
  uuid!: string;

  @OneToOne({
    entity: () => Book,
    owner: true,
    eager: true,
    fieldName: 'book_uuid',
    wrappedReference: true,
  })
  book!: IdentifiedReference<Book>;

  constructor(book: Book) {
    this.book = Reference.create(book);
  }
}
```

error:
```
.../node_modules/@mikro-orm/core/entity/Reference.js:71
        Object.defineProperty(this, '__meta', { value: this.entity.__meta, writable: true });
                                                                   ^
TypeError: Cannot read property '__meta' of undefined
    at Reference.set (.../node_modules/@mikro-orm/core/entity/Reference.js:71:68)
    at new Reference (.../node_modules/@mikro-orm/core/entity/Reference.js:8:14)
    at Function.create (.../node_modules/@mikro-orm/core/entity/Reference.js:30:16)
    at new User (.../dist/users/user.entity.js:37:45)
    at Object.instantiate (.../node_modules/@automapper/classes/src/lib/utils/instantiate.util.js:19:11)
    at Object.instantiate (.../node_modules/@automapper/classes/src/lib/classes.js:21:28)
    at Object.initializeMapping (.../node_modules/@automapper/classes/src/lib/classes.js:43:70)
    at Object.createMap (.../node_modules/@automapper/core/src/lib/create-mapper/create-mapper.js:24:36)
    at .../dist/users/user.profile.js:28:18
    at Object.addProfile (.../node_modules/@automapper/core/src/lib/create-mapper/create-mapper.js:30:13)

```

If I create constructor like this, it works: 
```ts
  constructor(book: IdentifiedReference<Book>) {
    this.book = book;
  }
```

Another hack is create method like setBook and remove book init inside constructor - it also works.

But I think, that it's not a good idea, I want to control this inside my constructor.

**Comment by notmedia** [comment]
Maybe whe can pass with AutoMap decorator property like `ignore`?

**Comment by notmedia** [comment]
I think this related to https://github.com/nartc/mapper/issues/311

**Comment by nartc** [comment]
Can you provide a sample reproduce with MikroORM?

**Comment by notmedia** [comment]
No problem, I'll do it tomorrow)

**Comment by notmedia** [comment]
@nartc created sample to reproduce - https://github.com/notmedia/automapper-mikroorm/blob/main/src/user/user.entity.ts

**Comment by nartc** [comment]
Thank you. I'll take a look tomorrow

**Comment by notmedia** [comment]
@nartc Hi, any news?

**Comment by nartc** [comment]
@notmedia Sorry for the delay. I have just got back from vacation. I'll take a look at the issue sometimes next week

**Comment by nartc** [comment]
@notmedia This is a limitation atm. AutoMapper does not support custom constructor right now (https://github.com/nartc/mapper/blob/f765bb4877dc03a2b102f6be6f0927d0aad013a4/packages/classes/src/lib/utils/instantiate.util.ts#L31). There are a couple of concerns

- If there was an API to customize the constructors, and if the constructors accept arguments, when and how do the consumers provide the arguments to AutoMapper so that AutoMapper could execute the custom constructor?

```ts
mapper.addCustomConstructor(User, () => new User(book)); // where does "book" come from?
mapper.addCustomConstructor(User, (book) => new User(book)); // at what point do you provide book to call this method?
```

To be honest, I'm not sure what would be a clean solution here? I'm willing to discuss further if you have any ideas.

**Comment by andzno1** [comment]
I think I have the same problem when trying to create a mapping for an external class (that I don't have control over) as source that doesn't have a default constructor:

```typescript
class Foo {
  bar: string;

  constructor(boppedy: Boppedy) {
    this.bar = boppedy.bar;
  }
}
```

When I try to create a mapping with `Foo` as source I am getting the error
> Cannot read property 'bar' of undefined

Minimal working example: https://stackblitz.com/edit/nartc-mapper-issue-319?file=index.ts

**Comment by andzno1** [comment]
@nartc Could something like this be done, similar to your proposal?
https://docs.automapper.org/en/stable/Queryable-Extensions.html?highlight=ConstructUsing#custom-destination-type-constructors

**Comment by nartc** [comment]
@andzno1 I think it could work but the public API needs to be easy to use. Now, let's analyze the example from .NET AutoMapper

```csharp
cfg.CreateMap<Source, Dest>()
    .ConstructUsing(src => new Dest(src.Value + 10));
```

This custom `Dest` constructor is customized with value from `Source` upon mapping. Where does `boppedy` come from in your case? from `Source` or from somewhere else? It is messy to come up with a clean API for custom constructors with arbitrary customization (arguments). 

Setting up a custom constructor is usually done on the Mapping level (when you invoke `createMap()`) but your examples seem like the custom constructor needs different argument value upon Map operation. It would be really messy and hard to pass around the custom constructor for a specific class/model.

That said, I'm open to suggestion, even RFC if you could come up with one.

**Comment by nartc** [comment]
Another workaround would be to have `map()` (and other map methods) to accept constructor arguments 
```ts
mapper.map(sourceObj, Destination, Source, {
   constructorArgs: {
      Destination: [/* args go here */],
      Source: [/* args go here */]
   }
})
```

**Comment by daramasala** [comment]
I just started using automapper and bumped into a similar problem.

```
class Source {  ​
 ​@AutoMap()
 ​public get prop(): {
   ​return this.o.prop;
 ​ }
  constructor(private o: Other) { ​}
}

class Dest {
  public prop: string;
}

mapper.createMap(Source, Dest); // <-- this throws exception when it tries to instantiate Source
```

In my case, the source model has a custom constructor. The destination has a default constructor.

I am not sure why the classes plugin creates an instance of the source when creating the mapping. Maybe for reflecting the metadata? 

If this is the case maybe internally the mapping could be created lazily on the first time we try to map the source to destination?

**Comment by nartc** [comment]
@daramasala it is indeed for reflecting the metadata. Creating the mapping lazily would probably be a potential solution but that'd change a lot of internal implementations. Not sure if I have enough time to work that out at the moment, any PRs would be most definitely welcomed here. I am willing to pair with whoever taking up this task :)

**Comment by Ealenn** [comment]
Any update since Oct 2021 👀 ?

**Comment by nartc** [comment]
@Ealenn unfortunately no progress :(. This issue is quite hard and I haven't had time to sit down and really think about it.

**Comment by nartc** [comment]
This is implemented in AutoMapper v8 https://automapperts.netlify.app/docs/mapping-configuration/construct-using
