### ISSUE TITLE
customClasses plugin example from documentation not working

### ISSUE THREAD

**Issue by grahamcrackers** [nartc/mapper#320]
I was trying to implement the customClasses extension of the plugin but [the example in the documentation](https://automapperts.netlify.app/docs/plugins-system/extend-plugin) doesn't work (with typescript at least). I thought I was typing it incorrectly and eventually came across this error once the type errors were solved.
```bash
.../node_modules/@automapper/classes/src/lib/classes.js:78
            const [sourceInstance] = this.instantiate(source, sourceObj);
                                          ^

TypeError: Cannot read property 'instantiate' of undefined
```

The correct way to extend the plugin is [here in the tests file](https://github.com/nartc/mapper/blob/main/packages/integration-test/src/lib/with-classes/with-extend-plugin.spec.ts#L12).

If you notice in the preMap function the extension is overriding, the documentation looks like this:
```ts
    // grab the original preMap
    const originalPreMap = originalClasses.preMap;

    // customize the preMap
    originalClasses.preMap = (...args) => {
        const originalPreMapResult = originalPreMap(...args);
        nullify(originalPreMapResult[0]);
        return originalPreMapResult;
    };
```

but you will actually need to bind the originalPreMap to your instantiated classes function in the custom plugin extension
```ts
    const originalPreMap = originalClasses.preMap;
    originalClasses.preMap = (...args) => {
        // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
        const originalPreMapResult = originalPreMap!.bind(originalClasses)(...args);
        nullify(originalPreMapResult[0]);
        return originalPreMapResult;
    };
```

I just wanted to document the differences here since I figured out my problem. Not sure if others have come across this but hopefully it helps. I can make a PR to update the doc site later if need be.

**Comment by micalevisk** [comment]
Hi! you're right!

> I can make a PR to update the doc site later if need be.

I'm pretty sure that you can go ahead.

**Comment by nartc** [comment]
@grahamcrackers Thank you for pointing that out. Since I wrote that in the docs, I literally didn't test it so it's fully my fault. 

For the snippet, the one you provided would work fine. However, we can leverage the correct syntax of `bind()`

```ts
const originalPreMapResult = originalPreMap.bind(originalClasses, ...args);
// or use apply()
const originalPreMapResult = originalPreMap.apply(originalClasses, args);
```

We can also drop the `!` non null assertion since it will be confusing if leave in the docs.
