### ISSUE TITLE
Nested array property doesn't get currect element type when mapping

### ISSUE THREAD

**Issue by huybn5776** [nartc/mapper#324]
For example, if user have profile and multiple jobs, and both add `@AutoMap` decorator without `typeFn`.
```typescript
export class User {
  // ...
  @AutoMap()
  profile!: UserProfile;
  @AutoMap()
  jobs!: Job[];
}
```

And AutoMapper will throw exception, that mean [it can't found the mapping from `undefined` to `undefined`](https://github.com/nartc/mapper/blob/05344d9b1ebe36b331a7486f8178f3358a935679/packages/classes/src/lib/classes.ts#L104)
```
Error at "jobs" on {"profile":{"bio":"I...
---------------------------------------------------------------------
Original error: TypeError: mapping is not iterable
```
> also, we may need a clearer error message when mapping not found

We can resolve this issue by adding `typeFn` to `jobs` property, but for the `profile` property, we didn't need to add `typeFn` for it and it will also work.
```typescript
export class User {
  // ...
  @AutoMap()
  profile!: UserProfile;
  @AutoMap({ typeFn: () => Job })
  jobs!: Job[];
}
```

Dig deeper into this and I found out that when no `typeFn` specific, it will failback to use [`Reflect.getMetadata()`](https://github.com/nartc/mapper/blob/05344d9b1ebe36b331a7486f8178f3358a935679/packages/classes/src/lib/decorators/automap.decorator.ts#L69) to get the the property type.
```typescript
// packages/classes/src/lib/decorators/automap.decorator.ts
// Getting Type
if (typeFn) {
  newMetadata.typeFn = typeFn;
} else {
  const meta = Reflect.getMetadata('design:type', target, propertyKey);
  if (meta) {
    newMetadata.typeFn = () => meta;
  }
}
```

But it will return `Array` instead of `Job[]` when getting the type of `job` property, and there is also an [issue about Reflect cannot get array element type](https://github.com/microsoft/TypeScript/issues/7169).

So, that mean this maybe an unresolvable issue for AutoMapper, I think we may need to note on the [Classes Limitations ](https://automapperts.netlify.app/docs/plugins-system/classes-limitations/) page, to let user know that for array property we MUST specify the `typeFn`.

**Comment by nartc** [comment]
Yes, this is a Reflect limitation. You'd have to provide a `typeFn` for Array properties, even if those properties are primitive array. Would you like to submit a PR to update the docs?

**Comment by huybn5776** [comment]
PR submitted. #326 
Please help me to check if there is any "Syntax Error" of english ;)

**Comment by nartc** [comment]
@huybn5776 https://github.com/nartc/mapper/runs/3214245186?check_suite_focus=true can you fix this build issue?

**Comment by huybn5776** [comment]
> @huybn5776 https://github.com/nartc/mapper/runs/3214245186?check_suite_focus=true can you fix this build issue?

#327
