### ISSUE TITLE
Cannot set property fullName of #<User> which has only a getter

### ISSUE THREAD

**Issue by abouroubi** [nartc/mapper#325]
**Describe the bug**
I have a getter in my model class, and when I try to map from my Model to my DTO, I have the error : `Cannot set property fullName of #<User> which has only a getter`

**Models/DTOs**
Model:
```typescript
export class User {
  @AutoMap()
  id: string;

  @AutoMap()
  first: string;

  @AutoMap()
  last: string;

  get fullName(): string {
    return this.first + this.last;
  }
}
```

DTO:
```typescript
export class UserDto {

  @AutoMap()
  id: string;

  @AutoMap()
  first: string;

  @AutoMap()
  last: string;
}
```

**Mapping Configuration**
```typescript
this.mapper.createMap(User, UserDto);
```

I don't understand why it's trying to set fullName, event if it's not annotated with `@AutoMap`, and also it's the source object.

**Comment by huybn5776** [comment]
Have you tired with the tests under this repo? I add `get fullName()` to [`User`](https://github.com/nartc/mapper/blob/main/packages/integration-test/src/lib/with-classes/fixtures/models/user.ts) class, and it pass all tests without any exception.
```typescript
export class User {
  @AutoMap()
  firstName!: string;
  @AutoMap()
  lastName!: string;
  @AutoMap()
  profile!: UserProfile;
  @AutoMap()
  job!: Job;

  get fullName(): string {
    return this.firstName + this.lastName;
  }
}

export class UserVm {
  @AutoMap()
  first!: string;
  @AutoMap()
  last!: string;
  @AutoMap()
  full!: string;
  @AutoMap()
  profile!: UserProfileVm;
  @AutoMap()
  jobTitle!: string;
  @AutoMap()
  jobAnnualSalary!: number;
}

```

Another way to debug it is clone this repo and let your project install package with local project via `file:` like `"@automapper/classes": "file:../mapper/packages/classes"`

**Comment by abouroubi** [comment]
The repo is on version 5, but I'm using version 4.2.2 because I'm still on nestjs 7

**Comment by nartc** [comment]
@abouroubi are you able to provide a reproduce? I have added a getter here in my `User` model in this repo (https://github.com/nartc/ng-mapper-bench/blob/master/src/app/models/models.ts#L20) and everything still works.

**Comment by abouroubi** [comment]
I checked your repo and it works indeed.

I tried to debug my version and the issue appears here: https://github.com/nartc/mapper/blob/f765bb4877dc03a2b102f6be6f0927d0aad013a4/packages/classes/src/lib/utils/instantiate.util.ts#L31-L33

it's the `Object.assign(new model(), defaultValue)` that raises the exception.

Out of curiosity why the source needs to be instantiated again in the mapping process ? I'm already sending a User class to the mapping function, no need to instantiate it again.

**Comment by nartc** [comment]
@abouroubi Since AutoMapper needs to make sure all the nested models are instantiated with the saved metadata, and it also needs to make sure that the `instance` is truly an instance and not a plain object (TypeScript can be tricked). With that said, this could be an overlook as well so if you could provide a reproduce, I can dig deeper and make decision regarding the `instantiate` method.

**Comment by abouroubi** [comment]
I found the error, I was trying to map my User that I got from mongoose, and with the default behavior virtuals are set to true, so when I call `mongooseUser.toJSON()` the getters are inlined as properties, and when `Object.assing` tries to copy a property into a getter the error arise.

I disabled virtuals, and everything is working now.

**Comment by nartc** [comment]
@abouroubi oh nice, glad that you found the cause. Though, do you think that it's a common use-case for Mongoose that AutoMapper should be aware about? Should we put something in the documentations regarding this?

**Comment by abouroubi** [comment]
That's a good question, I'm not aware of the popularity of mongoose among automapper user base, maybe this case can be added to a common issues section, or maybe just having it here as an issue in Github is enough.

P.S: Maybe virtuals are not set to true by default, to be honest I started from your blog post (https://nartc.me/blog/nestjs-typegoose), as a base for all my repositories, without knowing exactly how it was configured, now I know better

**Comment by nartc** [comment]
Oh I didn't know that. So you're saying if your model is:

```ts
class User {
   @prop()
   firstName: string;
   
   @prop()
   lastName: string;

   get fullName() {
      return this.firstName + ' ' + this.lastName;
   }
}
```

if I query for this `User` from MongoDB and then run `toJSON()` with `virtuals: true`, I'd see 

```
{ firstName: 'Chau', lastName: 'Tran', fullName: 'Chau Tran' }
```
as the result?

**Comment by abouroubi** [comment]
Yes that's what I've got

**Comment by nartc** [comment]
@abouroubi what we can do is to check for writable on the property name in instantiate() to escape assigning for that property. However, one concern I have is instantiate is invoked quite often as it is essential for mapping operations, not sure if it's worth it to add additional checks in instantiate()

**Comment by abouroubi** [comment]
I think it's too much overhead, maybe just adding it to the doc is enough.
Or the best solution is to have a dedicated module like sequelize plugin.
