### ISSUE TITLE
Sequelize Typescript - Cannot map from DTO to sequelize model

### ISSUE THREAD

**Issue by llecorguille** [nartc/mapper#332]
**Describe the bug**
Hello,

I am building an API using typescript, express, sequelize and automapper.
When i try to create a map from UserDto to User, the typescript compiler output an error.
```

 No overload matches this call. Overload 1 of 2, '(source: new (...args: unknown[]) => UserVm, destination: new (...args: unknown[]) => User, options?: CreateMapOptions<any, any> | undefined): CreateMapFluentFunction<UserVm, User>', gave the following error.
    Argument of type 'typeof User' is not assignable to parameter of type 'new (...args: unknown[]) => User'.
      Types of construct signatures are incompatible.
        Type 'new (values?: User | undefined, options?: BuildOptions | undefined) => User' is not assignable to type 'new (...args: unknown[]) => User'.
          Types of parameters 'values' and 'args' are incompatible.
            Type 'unknown' is not assignable to type 'User | undefined'.
              Type 'unknown' is not assignable to type 'User'.
  Overload 2 of 2, '(source: string, destination: string, options?: CreateMapOptions<any, any> | undefined): CreateMapFluentFunction<Dictionary<unknown>, Dictionary<unknown>>', gave the following error.
    Argument of type 'typeof UserVm' is not assignable to parameter of type 'string'.
```

**Models/DTOs**
```
class User extends Model<User> {
    @AutoMap()
    @Column
    name!: string
}

class UserVm {
    @AutoMap()
    name!: string
}
```

**Mapping Configuration**

```

const test = createMapper({
     ...,
    pluginInitializer: sequelize()
})
```

Here is the line where the compilation error occured

`
test.createMap(UserVm, User);
`

Here is my package.json

```
{
  ...
  "devDependencies": {
    "@automapper/types": "6.0.1",
    "@types/node": "^13.13.52",
    "@types/sequelize": "^4.28.10",
    "@types/validator": "^13.6.3",
    "pg": "^8.6.0",
    "sequelize-cli": "^6.2.0",
    "typescript": "^4.3.5"
  },
  "dependencies": {
    "@automapper/classes": "6.0.1",
    "@automapper/core": "6.0.1",
    "@automapper/sequelize": "6.0.1",
    "@types/express": "^4.17.6",
    "express": "^4.17.1",
    "reflect-metadata": "^0.1.13",
    "rxjs": "^7.2.0",
    "sequelize": "6.6.2",
    "sequelize-typescript": "^2.1.0",
    "tslint": "^6.1.3"
  }
}
```

Any ideas ? 
Thanks

**Comment by huybn5776** [comment]
Seems like AutoMapper require a contractor with no args
`new (...args: unknown[]) => User`
but not 
`new (values?: User | undefined, options?: BuildOptions | undefined) `

> Type 'new (values?: User | undefined, options?: BuildOptions | undefined) => User' is not assignable to type 'new (...args: unknown[]) => User'.

You may need to convert your db model `class User extends Model<User>` to `User` first.

**Comment by huybn5776** [comment]
Seems like it only happen when `strictFunctionTypes` is set to `true`(or `strict:true`) in tsconfig.
And it can resolve by replace all `new (...args: unknown[])`  to `new (...args: any[])` in AutoMapper, or create a `type Constructor<TModel> = new (...args: any[]) => TModel;` to do it.
But i can't make sure this will cause any side effects or not. @nartc

**Comment by nartc** [comment]
Sequelize changes the shape of the model so it's been on hiatus for quite a while :( I don't personally work with Sequelize so I really don't have neither the motivation nor the knowledge to create a working plugin for sequelize. Anyone want to help? I'm happy to guide you how to create a plugin in AutoMapper.

**Comment by nartc** [comment]
Related: #268

**Comment by llecorguille** [comment]
I managed to fix the compilator error by creating a constructor in a generic BaseModel class which extends sequelize's Model.

BaseModel.ts
`@Table
export class BaseModel<T> extends Model<T> {
    @AutoMap()
    @PrimaryKey
    @AutoIncrement
    @Column
    id!: number

    @AutoMap()
    @CreatedAt
    @Column
    createdAt!: Date

    @AutoMap()
    @Column
    updatedAt!: Date

    constructor(...args: any[]){
        super(args[0])
    }
}`

UserModel.ts
`
class User extends BaseModel<User> { @AutoMap() @Column name!: string }
`

**Comment by quinnturner** [comment]
@llecorguille I know it's been a while, but any particular reason why you went with `super(args[0])` instead of `super(..args)`?
