### ISSUE TITLE
mapAsync : Instructions executed in the wrong order

### ISSUE THREAD

**Issue by llecorguille** [nartc/mapper#333]
**Describe the bug**
Hello everyone,
I am struggling with the mapAsync function. 
I am trying to map a sync source to a async destination
The mapAsync function is not waiting the afterMap function to complete before resolving the promise.

**Models/DTOs**

I want to map a "IdOnlyDto" class to a "Dalle" class.
The Dalle class is a sequelize model.

```
export class IdOnlyDto{
    @AutoMap()
    @IsNumber()
    id!: number;

    constructor(...args: any[]){
        this.id = args[0];
    }
}
```

```
@Table
export class Dalle extends BaseModel<Dalle> {
     @AutoMap()
    id!: number

    @AutoMap()
    idBatiment!: number

    @AutoMap()
    idSalle?: string

    @AutoMap()
    idBande?: number

    @AutoMap()
    cote!: number

    @AutoMap()
    distance!: number

    @AutoMap()
    longueur!: number
}
```

**Mapping Configuration**

```
mapper.createMap(IdOnlyDto, Dalle)
        .afterMap(async (source, destination) => {
            console.log("2")
            // dalleService.getById(id) returns an Observable<Dalle>
            const res = await firstValueFrom(dalleService.getById(source.id))
            Object.assign(destination, res);
            console.log("3")
        });
```

**Test**

```
async test(){
     console.log("1");
    const myDalle = await mapper.mapAsync({id: 1}, Dalle, IdOnlyDto);
    console.log("4");
}
```

**Expected behavior**
Output : 1,2,3,4

**Actual behavior**
Output : 1,2,4,3

**Comment by llecorguille** [comment]
Is it related to the "fake async" support ? ([docs](https://automapper.netlify.app/docs/introduction/async))

**Comment by nartc** [comment]
Fake async is using `Promise.resolve()` to schedule the task as a microtask, which should work correctly. I'll look into this. Thanks!

**Comment by nartc** [comment]
Well, turns out this has never worked correctly. I'll be investigating this further. But it's gonna be slow as I'm a bit busy these days.

**Comment by micalevisk** [comment]
With `Mapper#map` it should outputs `1,2,4,3`  
while with `Mapper#mapAsync` it should outputs `1,2,3,4`
@llecorguille?

**Comment by nartc** [comment]
This specific issue has been addressed with AutoMapper v8. However, the TRUE underlying issue with "Fake" async is still there. Complex async flow with AutoMapper isn't recommended for now. If you have a complex async flow to map from one object to another, do not use AutoMapper for that object pairs.
