### ISSUE TITLE
Bidirectional mapping with getter & setter

### ISSUE THREAD

**Issue by andzno1** [nartc/mapper#334]
**Describe the bug**
This issue is related to issue #51.

I am not sure if the behavior I am expecting is actually the expected behavior. Looking at issue #51 lets me believe that it is.

When mapping an instance of a class `Foo` with a private property `_foo` that is being accessed via getter and setter to class `FooDto` that has a simple property `foo`, the mapping is done correctly. Mapping back from `FooDto` to `Foo` does not work with the `@AutoMap()` annotation, though.

**Models/DTOs**
```TypeScript
class Foo {
  private _foo: number = NaN;

  @AutoMap()
  public get foo(): number {
    return this._foo;
  }

  public set foo(value: number) {
    this._foo = value;
  }
}

class FooDto {
  @AutoMap()
  public foo?: number;
}
```

**Mapping Configuration**
```TypeScript
const mapper = createMapper({
  name: 'autoMapper',
  pluginInitializer: classes,
  namingConventions: new CamelCaseNamingConvention()
});

mapper.createMap(Foo, FooDto);
mapper.createMap(FooDto, Foo);
```

**To Reproduce**
```TypeScript
const foo = new Foo();
foo.foo = 1337;

const fooDto = mapper.map(foo, FooDto, Foo);
const foo2 = mapper.map(fooDto, Foo, FooDto);
```

**Expected behavior**
Property `foo2._foo` is set to `1337`.

**Actual behavior**
Property `foo2._foo` is set to `null`.

**Minimal running example**
https://stackblitz.com/edit/typescript-4jqllg?devtoolsheight=33&file=index.ts

**Comment by nartc** [comment]
This has been fixed in 6.0.2
