### ISSUE TITLE
Support for Nest 7?

### ISSUE THREAD

**Issue by ehaynes99** [nartc/mapper#337]
In https://github.com/nartc/mapper/issues/313 (https://github.com/nartc/mapper/commit/11fbc5cc3a4838792920874a956bad9ebc4eaec9), the `peerDependencies` were updated to Nest 8. Was there a particular need to disallow Nest 7, or was this just adding support for 8? We have a large number of projects, so haven't gotten around to the nest upgrade yet. Would you consider allowing both versions?

```json
"peerDependencies": {
  "@nestjs/common": "^7.0.0 || ^8.0.0",
  "@nestjs/core": "^7.0.0 || ^8.0.0"
}
```

**Comment by nartc** [comment]
Hey @ehaynes99 , yes, that'd be fine.

**Comment by nartc** [comment]
v6.1.2 is being released :) Thank you
