### ISSUE TITLE
'No overload matches' TS error when typing casting `extraArguments` of `Mapper#map` options 

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#346]
I'm trying enforcing `extraArguments` value using the `<>` operator:

```ts
interface MyInterface {
  foo: number
}

mapper.map(..., {
  extraArguments: <MyInterface>{
    foo
  }
})

// or even
const extra: MyInterface = { foo }
mapper.map(..., {
  extraArguments: extra
})
```

but I'm getting this typescript error:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'typeof DestinationDTO' is not assignable to parameter of type 'string'.ts(2769)
```
in `node_modules/@automapper/types/src/core.d.ts:71:5`

I'm not sure if this a limitation due to how TS works or just something missing in AutoMapper itself.

My goal is to gain autocompletion while writing the literal object `extraArguments` (not using a variable)

---

btw

https://github.com/nartc/mapper/blob/b1ff198f4540badca5301ce3510effe7d39ffdcf/packages/types/src/options.ts#L16

When I changed the `unknown` above to `any`, it works.

**Comment by micalevisk** [comment]
Looks like this is something to how TS works. If I do the following, it works. Thus maybe AutoMapper don't need to change anything, but I could be wrong.

```ts
interface Foo extends Record<string, unknown> {}
```

**Comment by nartc** [comment]
![image](https://user-images.githubusercontent.com/25516557/133802425-c737607f-3eca-4b78-a673-796494e0fe90.png)
This is because `extraArguments` type is fixed to `Record<string, unknown>`. Depending on the strict options of your tsconfig, it might or might not work at all. 

One thing that we can do from AutoMapper side of things is to have this:

```ts
export interface MapOptions<
  TSource extends Dictionary<TSource> = any,
  TDestination extends Dictionary<TDestination> = any,
   TExtraArguments extends Record<string, unknown> = Record<string, unknown>
> {
  beforeMap?: MapAction<TSource, TDestination>;
  afterMap?: MapAction<TSource, TDestination>;
  extraArguments?: TExtraArguments;
}
```

**Comment by micalevisk** [comment]
but since the constraint `extends Record<string, unknown>` is still there, we'll get this error when using interfaces:

```
Type 'MyInterface' does not satisfy the constraint 'Record<string, unknown>'.
  Index signature is missing in type 'MyInterface'.ts(2344)
```

From your knowledge regarding TS and AutoMapper's codebase, is it too bad if you change `Record<string, unknown>` to `Record<string, any>`?

---

btw this issue is related to this one from TS repo: https://github.com/microsoft/TypeScript/issues/15300

**Comment by nartc** [comment]
@micalevisk no if `Record<string, unknown>` does not work, feel free to use `Record<string, any>`. I'd like to get rid of all the any's but probably it's for later :D

**Comment by nartc** [comment]
@micalevisk I ended up enhance the `extraArguments` a bit more than just your PR. Check out `types/core.ts`
