### ISSUE TITLE
This Package is compatible with Angular?

### ISSUE THREAD

**Issue by GustavoEmanuel901** [nartc/mapper#350]
I would like to know if this package is compatible with Angular.

**Comment by nartc** [comment]
It should be. However, the packages are built to `commonjs` so you might see some warnings about tree-shaking in the console with Angular. Nx only supports building Node libraries to `commonjs` for now (this can be customized with custom webpack but I haven't had time to look into it).

**Comment by GustavoEmanuel901** [comment]
@nartc  I understand, in my case the following errors occurred, it seems that angular is not understanding the types
![remmina_cek-dev_192 168 100 11:33040_2021920-14291](https://user-images.githubusercontent.com/62678551/134020520-b129fa10-2c2d-428a-9854-f9144df3aae6.png)
.

**Comment by nartc** [comment]
Oh no, what Angular version are you on? Unfortunately, this library is only compatible with TypeScript 4.0+ (https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/#labeled-tuple-elements)

**Comment by GustavoEmanuel901** [comment]
@nartc I'm using a lower version even I'll try to switch, thanks.
