### ISSUE TITLE
[core] custom type converters do not work with typescript lookup types

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#369]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When using [custom type converters](https://automapperts.netlify.app/docs/mapping-configuration/custom-type-converter) along with [TS lookup types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html#keyof-and-lookup-types), the converter callback is never called.

### Models/DTOs/VMs

![image](https://user-images.githubusercontent.com/13461315/139517713-ac0fac94-fb76-4b02-8f06-f2d0e6eeed34.png)

---

`@AutoMap({ typeFn: () => String })` is an workaround

### Expected behavior

Using `Mapper#addTypeConverter` must works for lookup type on destination class as well

### Screenshots

![image](https://user-images.githubusercontent.com/13461315/139517613-1958b54f-564a-498a-bfa1-4bc953c5069b.png)

### Minimum reproduction code

in `packages/integration-test/src/lib/with-classes/fixtures/models/type-converter.ts` add

```ts
interface Foo {
  str: string;
}
```

and then change below to `value1!: Foo['str']`

https://github.com/nartc/mapper/blob/c6ac45752bfc8363243b5548c547d84fecaff27f/packages/integration-test/src/lib/with-classes/fixtures/models/type-converter.ts#L4-L5

and run

```bash
nx run-many --projects=integration-test --target=test
```

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [x] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

6.3.1

### Additional context

- TypeScript v4.0
- Node v16.13.0

---

`typeConverter` below is always `undefined`

https://github.com/nartc/mapper/blob/02ecd24a66d3e2ce1e2c529f53ba785e27412cda/packages/core/src/lib/create-mapper/apply-type-converters.util.ts#L37-L39

**Comment by micalevisk** [comment]
I guess this is a limitation not a bug, as the `destinationType` will be `Object` class instead of `String` class if we use lookup types on destination class

https://github.com/nartc/mapper/blob/c6ac45752bfc8363243b5548c547d84fecaff27f/packages/core/src/lib/create-mapper/apply-type-converters.util.ts#L40-L41

If so, we should need to add this on https://automapperts.netlify.app/docs/mapping-configuration/custom-type-converter#limitations

**Comment by nartc** [comment]
@micalevisk Yep it is a limitation for sure. Though, you can workaround it with: `@Automap({typeFn: () => String})`

**Comment by micalevisk** [comment]
ok I will.

Do you have any resources regarding this TS limitation?

**Comment by nartc** [comment]
@micalevisk just Reflection cannot get the type. Though I only tried with an interface which is compiled away during runtime (I doubt class would work)
