### ISSUE TITLE
[types] Improve type inference of `convertUsing`

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#371]
### Is your feature request related to a problem? Please describe.

Taking this code as an example:

https://github.com/nartc/mapper/blob/c6ac45752bfc8363243b5548c547d84fecaff27f/packages/integration-test/src/lib/with-classes/fixtures/profiles/user-profile.profile.ts#L115-L124

![image](https://user-images.githubusercontent.com/13461315/139593369-3b7eae55-87a2-4007-bc1d-f75de86cd9e7.png)

`source` parameter type is `any` instead of `Date` (`SnakeUserProfile['birthday']`)

![image](https://user-images.githubusercontent.com/13461315/139593394-818310b8-989a-4fa5-8480-a63cd37c4fe8.png)

This is frustating because in my project this will trigger errors on [`@typescript-eslint/no-unsafe-member-access`](https://github.com/typescript-eslint/typescript-eslint/blob/43b1201a73687e29f19a16b0b26f68569f3c7a2e/packages/eslint-plugin/docs/rules/no-unsafe-member-access.md?_pjax=%23js-repo-pjax-container) and [`@typescript-eslint/no-unsafe-return`](https://github.com/typescript-eslint/typescript-eslint/blob/43b1201a73687e29f19a16b0b26f68569f3c7a2e/packages/eslint-plugin/docs/rules/no-unsafe-return.md) rules

<details>
<summary>As you can see here</summary>

![image](https://user-images.githubusercontent.com/13461315/139593942-2dcb65f0-a622-45e6-886a-79276afda707.png)

To circumvent that error I need to write all typings explicity like

![image](https://user-images.githubusercontent.com/13461315/139593993-c7edc605-eec2-49f9-a82f-0861a9d371fe.png)

but I can't use the right type of `s.start` (above), I must use `any`. Which make this type-unsafe.

</details>

If I changed that to

```ts
convertUsing<SnakeUserProfile, PascalUserProfileVm, string, Date>
  (dateToStringConverter, (s) => s.birthday)
```

![image](https://user-images.githubusercontent.com/13461315/139593846-e1c29e4c-16a5-401d-a31b-f83620968fd5.png)

I got

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'ConvertUsingReturn<SnakeUserProfile, Date>' is not assignable to parameter of type 'MapDeferReturn<SnakeUserProfile, PascalUserProfileVm, unknown>'.
      Type 'TransformationType.ConvertUsing' is not assignable to type 'TransformationType.MapDefer'.ts(2769)
```

### Describe the solution you'd like

In the above example, the type of `source` parameter on **Selector** arg must be inferred as source class's type instead of `any`

### Additional context

- `@automapper/*` v6.3.1
- `typescript` v4.0

</details><details>
<summary><code>tsconfig.json</code></summary>

```json
{
  "compilerOptions": {
    "declaration": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "removeComments": true,
    "sourceMap": true,

    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,

    "strictNullChecks": true,
    "noImplicitAny": true,
    "noImplicitThis": true,
    "noImplicitReturns": true,
    "resolveJsonModule": true,

    "allowJs": true,
    "checkJs": false,
    "importsNotUsedAsValues": "remove",
    "incremental": true,
    "skipLibCheck": true,
    "typeRoots": ["node_modules/@types", "src/@types"],
    "types": ["node"],

    "lib": ["ESNext"],
    "target": "ES2019",
    "module": "commonjs",
    "moduleResolution": "node",
  }
}

```

</details>

**Comment by micalevisk** [comment]
actually this happens even when there's no selector

![image](https://user-images.githubusercontent.com/13461315/139599441-4992cea9-9225-496e-9ad4-61a86830a2d9.png)

`convert` parameter is always `any`

**Comment by nartc** [comment]
This one is a little tricky :(

Workaround would be:

```ts
forMember(
   d => d.Birthday,
   convertUsing(<Converter<UserProfile, string>{
      convert: source => source.birthday.toDateString()
   }>)
)
```

**Comment by nartc** [comment]
@micalevisk can you check if this is still an issue with v8?

**Comment by micalevisk** [comment]
it is not :smiley: 

![image](https://user-images.githubusercontent.com/13461315/161475417-99252933-c416-4d20-b2b7-9d1f67f16c3d.png)
