### ISSUE TITLE
Cannot map a property that is of type string or null

### ISSUE THREAD

**Issue by donnyroufs** [nartc/mapper#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I have a DTO with an imageUrl property which can be either a string or null but auto-mapper cannot seem to find a way to map it. So instead I duct-taped it by using the map-from utility but that also caused unwanted behavior... It would return me an object with the value of a character e.g.

imageUrl value: "htt"

maps to: 

```ts
{
  1: "h",
  2: "t",
  3: "t"
}
```

### Models/DTOs/VMs

```ts
import { AutoMap } from '@automapper/classes';
import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsString } from 'class-validator';

export class UserDto {
  @AutoMap()
  @IsString()
  @ApiProperty({
    default: 'John Doe',
  })
  fullName: string;

  @AutoMap()
  @IsString()
  @ApiProperty()
  id: string;

  @AutoMap()
  @IsString()
  @ApiProperty({
    default: 'John',
  })
  firstName: string;

  @AutoMap()
  @IsString()
  @ApiProperty({
    default: 'Doe',
  })
  lastName: string;

  @AutoMap()
  @IsString()
  @ApiProperty({
    default: 'john@zzapps.nl',
  })
  email: string;

  // Breaking property
  @AutoMap()
  @IsOptional()
  @IsString()
  @ApiProperty({
    default: 'https://image-uploader.com/r/john.jpg',
    nullable: true,
  })
  imageUrl: string | null;
}
```

### Mapping configuration

```typescript
import { Injectable } from '@nestjs/common';
import { AutomapperProfile, InjectMapper } from '@automapper/nestjs';
import { Mapper, MappingProfile } from '@automapper/types';

import { UserDto } from '../user/dtos';
import { User } from './user.entity';
import { mapFrom } from '@automapper/core';

@Injectable()
export class UserProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
  }

  mapProfile(): MappingProfile {
    return (mapper) => {
      mapper
        .createMap(User, UserDto)
        .forMember(
          (s) => s.fullName,
          mapFrom((o) => o.firstName + ' ' + o.lastName),
        )
        .forMember(
          (s) => s.imageUrl,
          mapFrom((o) => {
            // @ts-expect-error (bug?) Turns a string into an object where each key is 1 char long.
            return Object.values(o.imageUrl).join(''); // temporary fix.
          }),
        );
    };
  }
}
```

```ts
// actual entity
import { User as PrismaUser } from '@prisma/client';
import { AutoMap } from '@automapper/classes';

export class User implements PrismaUser {
  constructor(raw: any = {}) {
    Object.assign(this, raw);
  }

  @AutoMap()
  id: string;

  @AutoMap()
  firstName: string;

  @AutoMap()
  lastName: string;

  @AutoMap()
  email: string;

  @AutoMap()
  googleId: string;

  @AutoMap()
  imageUrl: string | null;

  @AutoMap()
  createdAt: Date;

  @AutoMap()
  updatedAt: Date;

  static fromPersistence(user: PrismaUser) {
    return new User(user);
  }
}
```

### Expected behavior

To get the url string without using map-from, and when using map-from not having to do hacky stuff like this.URL

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

6.3.1

### Additional context

Linux,
Node v16

**Comment by nartc** [comment]
Hi @donnyroufs , thank you for opening an issue. Depending on your strict mode, using `union` type like `string | null` like that makes Reflection freak out. I'd suggest providing the correct `typeFn` for `@AutoMap` like:

```ts
@AutoMap({ typeFn: () => String })
stringOrNull: string | null;
```

now the metadata will know that it's a String for sure.

**Comment by micalevisk** [comment]
this is stated here https://automapperts.netlify.app/docs/plugins-system/classes-limitations/#strict-mode btw

![image](https://user-images.githubusercontent.com/13461315/140417217-b43ba877-dc08-4006-ac0d-9aabfbe817ba.png)

**Comment by donnyroufs** [comment]
> Hi @donnyroufs , thank you for opening an issue. Depending on your strict mode, using `union` type like `string | null` like that makes Reflection freak out. I'd suggest providing the correct `typeFn` for `@AutoMap` like:
> 
> ```ts
> @AutoMap({ typeFn: () => String })
> stringOrNull: string | null;
> ```
> 
> now the metadata will know that it's a String for sure.

Ah that idd fixed it! Can't believe I missed it in the docs haha, thanks for the quick reply!

**Comment by nartc** [comment]
@micalevisk Thanks man!
@donnyroufs No worries! I don't even remember I wrote that in the docs LOL
