### ISSUE TITLE
[feature] Automapper plugin for MikroORM

### ISSUE THREAD

**Issue by calvinwyoung** [nartc/mapper#387]
### Is your feature request related to a problem? Please describe.

[MikroORM[(https://mikro-orm.io/) is increasing in popularity. Automapper currently supports an official plugin for `sequelize`. I'd love to see an official plugin for MikroORM that'd allow us to automap nested references like this:

```typescript
@AutoMap({ typeFn: () => ChildDto })
child: ChildDto;
```

### Describe the solution you'd like

Official plugin to support MikroORM nested references.

**Comment by nartc** [comment]
How is AutoMapper being used with MikroORM right now if you are using them together?

**Comment by calvinwyoung** [comment]
To clarify, I'd love to see improved handling of automapping nested references with MikroORM models. It *appears* that the sequelize plugin handles this, but tbh I haven't spent enough time studying it to understand everything it does.

To illustrate, let's suppose we have the following MikroORM models:

```typescript
@Entity()
export class Author {
  @Property()
  @AutoMap()
  name: string;
}

@Entity()
export class Book {
  @ManyToOne(() => Author, { wrappedReference: true })
  @AutoMap()
  author: IdentifiedReference<Author>;
}
```

And suppose we have these correpsonding DTOs which will be mapped by automapper:

```ts
export class AuthorDto {
  @AutoMap()
  name: string;
}

export class BookDto {
  @AutoMap({ typeFn: () => AuthorDto })
  author: AuthorDto;
}
```

Fetching and mapping an `Author` instance works out of the box:

```ts
const author = await em.findOne(Author, { id });

mapper.map(author, AuthorDto, Author);
```

But reference fields must be manually dereferenced:

```ts
const book = await em.findOne(Book, { id }, ['author']);

mapper.map(
  {
    author: book.author.getEntity(),
  },
  BookDto,
  Book
);
```

If we tried mapping the `book` object directly with `mapper.map(book, BookDto, Book)`, then the `author` property would evaluate to an empty object `{}`. There's some complexity wrangling the different ways MikroORM represents references, and it'd be amazing if some of that could be abstracted away from the application code.

Hope this makes sense — let me know if any other information would be useful! Thank you!

**Comment by nartc** [comment]
```ts
@Entity()
export class Book {
  @ManyToOne(() => Author, { wrappedReference: true })
  @AutoMap({ typeFn: () => Author })
  author: IdentifiedReference<Author>;
}
```

I'm sure if you let `AutoMapper` knows that `author` is actually an `Author` type when mapped, then it will work without `getEntity()` manually since you've already specified the populate field `['author']` in book query

**Comment by paulyea** [comment]
Hello, I've  similar use case as above except I've defined a one to one relationship:

```ts
@Entity()
export class Author {
  @OneToONe(() => Book, (book) => book.author, {
    wrappedReference: true,
    orphanRemoval: true,
  }
  @AutoMap({ typeFn: () => Book })
  book: IdentifiedReference<Book>;
}

@Entity()
export class Book {
  @OneToOne(() => Author, (author) => author.book, {
    owner: true,
    wrappedReference: true,
  })
  @AutoMap({ typeFn: () => Author })
  author: IdentifiedReference<Author>;
}

export class AuthorDto {
  @AutoMap({ typeFn: () => BookDto })
  book: BookDto;
}

export class BookDto {
  @AutoMap({ typeFn: () => AuthorDto })
  author: AuthorDto;
}

const author = await em.findOne(Author, { id });
mapper.map(author, AuthorDto, Author);
```

the code snippet above errors out with the following stack trace:

```
/Users/paul/code/weekend-root/node_modules/@mikro-orm/core/entity/Reference.js:11
        meta.primaryKeys.forEach(primaryKey => {
             ^
TypeError: Cannot read property 'primaryKeys' of undefined
    at new Reference (/Users/paul/code/weekend-root/node_modules/@mikro-orm/core/entity/Reference.js:11:14)
    at Function.create (/Users/paul/code/weekend-root/node_modules/@mikro-orm/core/entity/Reference.js:30:16)
    at Function.wrapReference (/Users/paul/code/weekend-root/node_modules/@mikro-orm/core/entity/Reference.js:43:30)
    at ClinicData.set [as member] (/Users/paul/code/weekend-root/node_modules/@mikro-orm/core/entity/EntityHelper.js:105:64)
    at setMutate (/Users/paul/code/weekend-root/packages/core/src/lib/utils/set.util.ts:51:4)
    at instantiate (/Users/paul/code/weekend-root/packages/classes/src/lib/utils/instantiate.util.ts:120:5)
    at Object.instantiate (/Users/paul/code/weekend-root/packages/classes/src/lib/classes.ts:32:25)
    at Object.preMap (/Users/paul/code/weekend-root/packages/classes/src/lib/classes.ts:123:37)
    at Object.map (/Users/paul/code/weekend-root/packages/core/src/lib/create-mapper/create-mapper.ts:110:7)
    at test (/Users/paul/code/weekend-root/packages/scripts/src/local/test.ts:24:22)
```

the TLDR of the stack trace I think (not too familiar with the mikro orm code base) is automapper's classes plugin doesn't play nice with mikro orm; mikro orm have their own custom setter on their Models and said custom setter require some mikro orm related metadata that gets lost somehow when `setMutate` is called.

I realize that this feels like a mikro orm specific problem, but wondering if there is any interest in adding support for mikrorm in the vain of sequelize (official plugin), such that using mikrorm with auto mapper has first class support.

Thanks

**Comment by calvinwyoung** [comment]
@nartc Do you have a sense for how we might be able to get this resolved? We'd love to get tighter interop between mikro-orm <-> automapper 🙃

**Comment by nartc** [comment]
@calvinwyoung can someone provide me a running sample repo with MikroORM, ideally, with Nest I guess?

**Comment by paulyea** [comment]
Didn't end up setting up a Nest project (mostly cause I was running against a time constraint), but I believe this repo should suffice: https://github.com/paulyea/auto-mapper-mikro-orm-sample

**Comment by nartc** [comment]
@paulyea thank you. I'll give that a look as soon as I have some time.

**Comment by nartc** [comment]
I think I have an idea to come up with some rudimentary support for MikroORM. Look out for the next minor version. Thank you @paulyea again for the repo, cc @calvinwyoung

**Comment by calvinwyoung** [comment]
Awesome thanks for the help @nartc!

**Comment by nartc** [comment]
Don’t try out the latest version just yet. It has bugs but I feel like I’m very close

**Comment by calvinwyoung** [comment]
Amazing, thanks for the update! Happy to test out the next release

**Comment by nartc** [comment]
@paulyea I've pushed to a branch with a new `mikro` plugin (https://github.com/nartc/auto-mapper-mikro-orm-sample/tree/nartc-mikro-plugin)

I've also been playing around with Mikro (and MongoDB) on this repo: https://github.com/nartc/nx-post-mikro

Keep in mind that this is still experimental as Mikro's Entity is quite complex. Also, as #319 stated, you CANNOT build your Entity with `constructor`.
