### ISSUE TITLE
Transformer Plugin breaks over custom types

### ISSUE THREAD

**Issue by PieterBoeren** [nartc/mapper#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When I define a custom type in a shared file (`types.ts` or something) and importing a type from that file in my DTO, compilation breaks when using the Transformer Plugin. I can compile the code with just `tsc`, but the webpack build fails with:
`Attempted import error: 'GeoJSONWithCRS' is not exported from '../types'.`.

It might have something to do with [type-only-imports-exports](https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports), but when I try that (`import type { GeoJSONWithCRS } from "../types";`) I get:

![image](https://user-images.githubusercontent.com/43775697/147335190-18102ee6-9089-404d-9ab0-1d2d5dd6e013.png)

Both errors go away if I disable the custom transformer.

### Models/DTOs/VMs

```TypeScript
import { GeoJSONWithCRS } from "../types";

class TestDto {
    public id!: number;
    public someGeometry!: GeoJSONWithCRS;
}

export { TestDto };
```

types.ts:

```TypeScript
import { GeoJSON } from "geojson";

// Extend the GeoJSON type with a crs, definition of the crs is taken from the proj4leaflet declarations
type GeoJSONWithCRS = GeoJSON & { crs?: { type: string; properties: { name: string } } };

export type { GeoJSONWithCRS };
```

### Steps to reproduce

1. Clone https://github.com/PieterBoeren/cra-automapper
2. `yarn install`
3. `yarn build` (observe the error)
4. Edit the `craco.config.js` file and remove the custom transformer
5. `yarn build`

### Expected behavior

No build errors

### Minimum reproduction code

https://github.com/PieterBoeren/cra-automapper

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

7.1.1

**Comment by PieterBoeren** [comment]
Another observation: things like:

```TypeScript
import { GeoJSON } from "geojson";

// Extend the GeoJSON type with a crs, definition of the crs is taken from the proj4leaflet declarations
type GeoJSONWithCRS = GeoJSON & { crs?: { type: string; properties: { name: string } } };

class TestDto {
    public id!: number;
    public someGeometry!: GeoJSONWithCRS;
}

export { TestDto };
```

Do compile, but don't work during runtime:

![image](https://user-images.githubusercontent.com/43775697/147337310-d6f7685f-ce28-406a-b7bc-40286d4e2c89.png)

Workaround would be to declare `someGeometry` as (but that is far from ideal if you have quite some properties with a custom type):

`public someGeometry!: GeoJSON & { crs?: { type: string; properties: { name: string } } };`

**Comment by nartc** [comment]
I just checked this out and noticed that there are two issues:
- Transformer Plugin does not handle Type Alias correctly. This maybe a non-issue because I would suggest to use `@AutoMap()` explicitly on these properties anyway. It is tricky to determine type-alias with the AST unfortunately
- `ts-loader` setup. There's something weird with your `ts-loader` setup w/ all the `isolatedModule` and `transpileOnly` etc... I'm not good enough w/ webpack to tell for sure what happens. If I take out the transformer plugin, there's still the error with `Attempted import error: 'GeoJSONWithCRS' is not exported from '../types'.` and if I use `import type {...}`, then this error:
```
./src/models/models.dto.ts 11:12
Module parse failed: Unexpected token (11:12)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| };
| import { AutoMap } from "@automapper/classes";
> import type { GeoJSONWithCRS } from "../types";
| var TestDto = /** @class */ (function () {
|     function TestDto() {
```

For now, a workaround maybe this:

```ts
import { AutoMap } from "@automapper/classes";

class TestDto {
    public id!: number;
    @AutoMap()
    public someGeometry!: import('../types').GeoJSONWithCRS;
}

export { TestDto };

```

**Comment by PieterBoeren** [comment]
Thanks for the workaround, that works.

However, I'm still confused. Is the decorator needed when I use the transformer plugin *and* a `forMember`?

The `ts-loader` config is the [default example](https://github.com/gsoft-inc/craco/tree/master/recipes/use-ts-loader) of using craco.

**Comment by nartc** [comment]
@PieterBoeren That is one confusing point for sure. The Transformer Plugin will add the property name to the `__AUTOMAP_METADATA__` with the metadata (in a similar manner to `@AutoMap()`)

```ts
export class Foo {
   @AutoMap()
   foo!: string;
   @AutoMap()
   bar!: number;
}
// this produces: [['foo', {typeFn: () => String}], ['bar', {typeFn: () => Number}]] at runtime

export class Foo {
   foo!: string;
   bar!: number;
}
// this produces

class Foo {
   static __AUTOMAPPER_METADATA_FACTORY__() {
      return [['foo', {typeFn: () => String}], ['bar', {typeFn: () => Number}]];
   }
}

```

There is no way for the Transformer Plugin to know if a field WILL BE manually configured with `forMember()`. I guess the rule of thumb is if you're using the Transformer Plugin and the metadata acts weird, then try putting `@AutoMap()` on the fields. Sorry for the inconvenience. 

If you have any ideas/suggestions, I'm all ears. And please open a new issue/feature request then. I'll be closing this.

**Comment by LaysDragon** [comment]
Well,I bump into this problem too. 
It seems that transformer won't respect the metadata from the `@AutoMap()` and still generating its own metadata base on the code. It's will still cause the import error unless use ` @autoMapIgnore` to force transformer skip that property.

I thinks it should be better for transformer to skip these pure type in typescript world and warning the programmer to use `@AutoMap` instead. Interface are also affected by this behaviour. Or at least respect the type config in the `@AutoMap` to avoid unnecessary ` @autoMapIgnore` comment.

And under ES2020 module ,transformer will also affected every import statement(these should be remove after compiled are all back)in the target file and cause other unexported member error on these pure type import. :( 
I have to split the file to avoid these bug for now.
