### ISSUE TITLE
Unmapped properties error when inheriting class

### ISSUE THREAD

**Issue by Morb0** [nartc/mapper#394]
### Is your feature request related to a problem? Please describe.

I use MikroORM and have entity that inherits from the base entity.
```typescript
class abstract BaseEntity {
  @PrimaryKey()
  id: string = v4();
}

class ItemEntity extends BaseEntity {
  @Property()
  prop: string;
}
```

And when i try map `CreateItemDto` to `ItemEntity` I got error about unmapped fields in base classes (like `id`).
Base entity not have any AutoMapping decorators.

### Describe the solution you'd like

It's not really bug, I saw you answer in another issue that you can make something to handle that behavior.

**Comment by nartc** [comment]
Hi @Morb0, thank you for reporting. This sounds like it is expected. Can I see your mapping configuration between `CreateItemDto` and `ItemEntity`?

**Comment by Morb0** [comment]
I made repo that reproduce it - https://github.com/Morb0/automapper-issue-394
It works as expected only errors are sent to the console. I also tried adding `ignore()` to the properties of the base class when mapping, however then they are not initialised and are always undefined.

**Comment by nartc** [comment]
@Morb0 Check out 7.2.0 I added an additional logic to check for the value before determining it is `unmapped` since you can have default values on a Destination model.
