### ISSUE TITLE
Decorator to disable AutoMap

### ISSUE THREAD

**Issue by Morb0** [nartc/mapper#395]
### Is your feature request related to a problem? Please describe.

In case when I using plugin that automatically mark all properties as `@AutoMap` I can have a scenario where I don't want `AutoMap` property to just ignore them or to fix problem like `Circular Dependencies`.

### Describe the solution you'd like

Add decorator that override `AutoMap` like `AutoMapDisable` and disable him.

**Comment by nartc** [comment]
https://automapperts.netlify.app/docs/plugins-system/classes-transformer-plugin#ignore-a-property
