### ISSUE TITLE
"Invalid Date" result for Date[] mappings

### ISSUE THREAD

**Issue by roblopz** [nartc/mapper#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

It seems there's a bug on the classes plugin when mapping properties of type _Date[]_. Date[] properties are mapped to 'Invalid Date' instead of the expected array of date objects. 

### Models/DTOs/VMs

export class Invite {
  @AutoMap({ typeFn: () => String })
  _id: string;

  @AutoMap({ typeFn: () => String })
  main: string;

  @AutoMap({ typeFn: () => Date })
  logins?: Date[];

  @AutoMap({ typeFn: () => Date })
  sentAt: Date;
}

export class InviteDTO {
  @AutoMap({ typeFn: () => String })
  _id: string;

  @AutoMap({ typeFn: () => String })
  main: string;

  @AutoMap({ typeFn: () => Date })
  logins?: Date[];

  @AutoMap({ typeFn: () => Date })
  sentAt: Date;
}

### Mapping configuration

import { createMapper } from '@automapper/core';
import { classes } from '@automapper/classes';

export const mapper = createMapper({
  name: 'appMapper',
  pluginInitializer: classes
});

### Steps to reproduce

 /*
    Using above described classes and mapping config...
  */

function inviteFactory() {
  const invite = new Invite();
  invite._id = 'SomeId';
  invite.main = 'SomeString';
  invite.sentAt = new Date();
  invite.logins = [new Date(), new Date(), new Date()];
  return invite;
}

const invite = inviteFactory();
const dto = this.mapper.map(invite, InviteDTO, Invite);

// OK, Date-type is correctly being mapped
expect(dto.sentAt).toBeValidDate();

// FAIL, Date[]-type is being mapped to an invalid date object
expect(dto.logins).toBeAnArray();

// FAIL, dto.logins is NOT an array here as it should be, it's an invalid date object
dto.logins.forEach(date => expect(date).toBeValidDate);

### Expected behavior

Date[] properties are correctly mapped. 

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

6.2.1

**Comment by micalevisk** [comment]
I guess this is due to this limitation: https://automapperts.netlify.app/docs/misc/limitations#date-time

**Comment by roblopz** [comment]
> I guess this is due to this limitation: https://automapperts.netlify.app/docs/misc/limitations#date-time

The thing is, even when providing a custom mapFrom function on the configuration, I'm getting my source object with this 'Invalid Date' value instead of the Date[] value.. any workaround you can think of?

**Comment by nartc** [comment]
@roblopz I'll take a look tomorrow. Thank you for reporting

**Comment by roblopz** [comment]
I've created a quite simple PR #398 that I think shouldn't break anything else.

Thanks @nartc, @micalevisk.

**Comment by roblopz** [comment]
New and corrected PR #399 

Thanks!
