### ISSUE TITLE
NestJS Initialization Failing when running in cloud after adding AutoMapper Module.

### ISSUE THREAD

**Issue by BeyondBelief96** [nartc/mapper#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm not exactly sure how to explain this issue, but I've added Automapper to my NestJS project using the NestJS docs section. All seems fine locally, and using serverless-offline I'm able to use postman to hit all my endpoints with no issues. When we deploy the NestJS app to a lambda, we start hitting some issues after introducing automapper. I've gone back and incrementally added in changes to find the source of the issues and it seems that the issue happens after registering Automapper in my app.module.ts file. 

`import { Module } from '@nestjs/common';
import { LoanModule } from './loan/loan.module';
import { ConfigModule } from '@nestjs/config';
import { TypeOrmModule } from '@nestjs/typeorm';
import { AuthenticationModule } from './authentication/authentication.module';
import { AutomapperModule } from '@automapper/nestjs';
import { classes } from '@automapper/classes';
import { LoanExtensionModule } from './loan-extension/loan.module';

const ignoreEnvFile = process.env.ENV !== 'local';

@Module({
  imports: [
    LoanModule,
    LoanExtensionModule,
    ConfigModule.forRoot({
      ignoreEnvFile: ignoreEnvFile,
      isGlobal: true,
    }),
    AutomapperModule.forRoot({
      options: [{ name: 'mapper', pluginInitializer: classes }],
      singular: true,
    }),
    TypeOrmModule.forRoot({
      type: 'postgres',
      host: process.env.DB_HOST,
      port: 5432,
      username: process.env.POSTGRES_USER,
      password: process.env.POSTGRES_PASSWORD,
      database: process.env.POSTGRES_DB,
      autoLoadEntities: true,
      synchronize: true,
    }),
    AuthenticationModule,
  ],
})
export class AppModule {}`

The error i'm seeing is pretty cryptic but here are the logs: 

`

START RequestId: 44669238-3d15-4c6a-b9cf-61a4848439f5 Version: $LATEST
--
[32m[Nest] 9  - [39m02/22/2022, 3:23:03 PM [32m    LOG[39m [38;5;3m[NestFactory] [39m[32mStarting Nest application...[39m
[32m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mc dependencies initialized[39m[38;5;3m +137ms[39m
[32m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mAutomapperModule dependencies initialized[39m[38;5;3m +1ms[39m
[32m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mTypeOrmModule dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32ml dependencies initialized[39m[38;5;3m +0ms[39m
[32m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [32m    LOG[39m [38;5;3m[InstanceLoader] [39m[32mPassportModule dependencies initialized[39m[38;5;3m +0ms[39m
[31m[Nest] 9  - [39m02/22/2022, 3:23:04 PM [31m  ERROR[39m [38;5;3m[ExceptionHandler] [39m[31mNest can't resolve dependencies of the d (?). Please make sure that the argument s at index [0] is available in the d context.
Potential solutions:
- If s is a provider, is it part of the current d?
- If s is exported from a separate @Module, is that module imported within d?
@Module({
imports: [ /* the Module containing s */ ]
})
[39m
Error: Nest can't resolve dependencies of the d (?). Please make sure that the argument s at index [0] is available in the d context.
Potential solutions:
- If s is a provider, is it part of the current d?
- If s is exported from a separate @Module, is that module imported within d?
@Module({
imports: [ /* the Module containing s */ ]
})
at Injector.lookupComponentInParentModules (/var/task/node_modules/@nestjs/core/injector/injector.js:202:19)
at Injector.resolveComponentInstance (/var/task/node_modules/@nestjs/core/injector/injector.js:157:33)
at resolveParam (/var/task/node_modules/@nestjs/core/injector/injector.js:108:38)
at async Promise.all (index 0)
at Injector.resolveConstructorParams (/var/task/node_modules/@nestjs/core/injector/injector.js:123:27)
at Injector.loadInstance (/var/task/node_modules/@nestjs/core/injector/injector.js:52:9)
at Injector.loadProvider (/var/task/node_modules/@nestjs/core/injector/injector.js:74:9)
at async Promise.all (index 3)
at InstanceLoader.createInstancesOfProviders (/var/task/node_modules/@nestjs/core/injector/instance-loader.js:44:9)
at /var/task/node_modules/@nestjs/core/injector/instance-loader.js:29:13
END RequestId: 44669238-3d15-4c6a-b9cf-61a4848439f5
REPORT RequestId: 44669238-3d15-4c6a-b9cf-61a4848439f5	Duration: 160.50 ms	Billed Duration: 161 ms	Memory Size: 1024 MB	Max Memory Used: 151 MB	Init Duration: 2018.68 ms
RequestId: 44669238-3d15-4c6a-b9cf-61a4848439f5 Error: Runtime exited with error: exit status 1Runtime.ExitError
`
Not really sure what the deal is as everything seems to be fine locally. It could be that I'm just completely missing something here. I have verified that this is only happening after introducing the Autmapper module in the App.module.ts file. Any help or insight would be greatly appreciated. I know its not much to go off on, but that's about all the info I have. For reference I have no mappings setup in the branch I'm on. The "get" endpoint I have literally just returns nothing. I'm using a test branch slowly introducing code until it broke to debug. So it's pretty minimal stuff at the moment. 

### Expected behavior

Expect NestJS application to startup and initialize properly. 

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### AutoMapper version

7.2.1

**Comment by nartc** [comment]
Oh no :( bugs in production is horrible. Can you show me where you use `InjectMapper`?

**Comment by BeyondBelief96** [comment]
> 

I have not yet introduced InjectMapper in my current test branch. My approach was to have a fresh branch and slowly introduce Automapper to it and deploy the changes and test etc until is saw the issue. So all I have so far is my entity file with the automap decorators like so: 

`import { AutoMap } from '@automapper/classes';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';
import { ILoanExtension } from '../loanExtension.interface';

@Entity({ name: 'loanExtension' })
export class LoanExtension implements ILoanExtension {
  @PrimaryGeneratedColumn('uuid')
  @AutoMap()
  loan_extension_id?: string;

  @Column({ nullable: true })
  @AutoMap()
  name?: string;

  @Column({ nullable: true })
  @AutoMap()
  created_by?: string;

  @Column({ nullable: true })
  @AutoMap()
  created_at?: string;

  @Column({ nullable: true }) 
  @AutoMap()
  updated_at?: string;

  @Column({ nullable: true })
  @AutoMap()
  updated_by?: string;

  @Column({ nullable: true })
  @AutoMap()
  deleted_at?: string;

  @Column({ nullable: true })
  @AutoMap()
  deleted_by?: string;

  @Column({ nullable: true })
  @AutoMap()
  loan_id?: string;

  @Column({ nullable: true })
  @AutoMap()
  loan_term_id?: string;

  @Column({ nullable: true })
  @AutoMap()
  proof_of_current_re_property_taxes?: string;

  @Column({ nullable: true })
  @AutoMap()
  status_reason_id?: string;

  @Column({ nullable: true })
  @AutoMap()
  certificate_of_insurance?: string;
}
`

I have the Automapper module registered, but I have not yet created the mappings using profiles and I'm not actually using the mapper yet. I just have it imported in my app module. The endpoint I created is straightforward: 

@Controller(LOAN_EXTENSIONS_BASE_URL)
export class LoanExtensionController {
    constructor(@Inject(LoanExtensionService) private readonly loanExtensionsService: LoanExtensionService) {
    }
    
    @Get()
    async getAllLoanExtensionsAsync(): Promise<LoanExtensionResponseDto[]> {
        const loanExtensions = await this.loanExtensionsService.getAllLoanExtensionsAsync();
        return loanExtensions;
    }

}

@Injectable()
export class LoanExtensionService {
    constructor(@InjectRepository(LoanExtensionRepository) private readonly loanExtensionRepository: LoanExtensionRepository)
    {}

    async getAllLoanExtensionsAsync(): Promise<LoanExtensionResponseDto[]> {
        const loanExtensions = await this.loanExtensionRepository.createQueryBuilder('LoanExtension').getMany();
        return;
    }
}

**Comment by BeyondBelief96** [comment]
I have a branch with ALL my actual changes where I fully implemented automapper but I thought my test branch would help narrow down the problem.

**Comment by BeyondBelief96** [comment]
Sure, I've actually been working on that myself while waiting for a response, and it seems that maybe the AutmapperModule isinn't the issue. I removed it from app.module.ts and seem to have the issue still....does the ordering of the AutoMap() decorators matter when use with other decorators?

**Comment by nartc** [comment]
@BeyondBelief96 I'd like to think that it doesn't 😅. Removing all `AutoMap` still outputs the error? Can I have the minimal reproduce?

**Comment by BeyondBelief96** [comment]
I haven't removed ALL AutoMap stuff yet. The only stuff I related to automapper I have now is my entity file with the decorators on it. I'm going to try removing those too verify if that's the issue or not.

**Comment by BeyondBelief96** [comment]
The issue would be hard to reproduce for someone else unfortunately since it's only happening in our AWS Lambda environment.
