### ISSUE TITLE
Add a new transformation to map `undefined` values

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#437]
### Is your feature request related to a problem? Please describe.

I want to avoid the following pattern:

```js
.forMember(
  (d) => d.someField, // number | null
  mapFrom((s) =>
    s.someField // number | undefined
    ?? null),
)
```

### Describe the solution you'd like

Same as the [`nullSubstitution`](https://github.com/nartc/mapper/blob/f49bff2db57e32d8e21c6d4a3610a0265d178beb/docs-site/docs/mapping-configuration/null-substitution.md) transformation. Thus would be `undefinedSubstitution`

```js
.forMember(
  (d) => d.someField,
  undefinedSubstitution(null),
)
```

If you believe this doesn't make sense or if you want to add this in v8 only, I'll be fine

### Describe alternatives you've considered

just the manual mapping using the [nullish coalescing operator](https://www.proposals.es/proposals/Nullish%20coalescing%20Operator)

**Comment by nartc** [comment]
If you'd like to open a PR to add to v7, I'm fine with it (especially if you would want it early). If not, then I'll make some time during the week to add it to v7. Thank you

**Comment by micalevisk** [comment]
actually to me this isn't urgent _(but I'd like to use in v7)_ so feel free to add it to v7 any time. Thanks.

**Comment by micalevisk** [comment]
I believe we should not add new features in v7.

Thanks for adding this in v8.
