### ISSUE TITLE
The injected AutoMapper is empty in NestJS

### ISSUE THREAD

**Issue by Alwinator** [nartc/mapper#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

A want an AutoMapper object (that offers functions such as .map), but instead I am getting an empty object.,

### Models/DTOs/VMs

None

### Mapping configuration

None

### Steps to reproduce

npm run start:dev

### Expected behavior

A functioning injected AutoMapper instance

### Minimum reproduction code

https://github.com/Alwinator/automapper-nestjs-inject-bug

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.2.3

### Additional context

Ubuntu 21.10
Node v16.13.1

**Comment by micalevisk** [comment]
this is because `createMapper` returns a [JS Proxy](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Proxy). But this is fine.

https://github.com/nartc/mapper/blob/85060cd8143eddfd8bf08ea8c1ae67fbd7108344/packages/core/src/lib/core.ts#L53-L54

**Comment by nartc** [comment]
Micael is correct. Mapper is a Proxy and it starts as an empty object. NodeJs should at least shows "Proxy {}" though
