### ISSUE TITLE
Cannot use Transformer Plugin with NestJS CLI, module not found

### ISSUE THREAD

**Issue by dgradwell-ams** [nartc/mapper#457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

When attempting to use the Transformer Plugin with NestJS CLI, the package `@automapper/classes/transformer-plugin` fails to import with the message: `Error  "@automapper/classes/transformer-plugin" plugin could not be found!`

I have confirmed that `node_modules/@automapper/classes/transformer-plugin` exists.

See the attached reproduction repo.

### Mapping configuration

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": [
      {
        "name": "@automapper/classes/transformer-plugin",
        "options": {
          "modelFileNameSuffix": [
            ".dto.ts",
            ".model.ts"
          ]
        }
      }
    ]
  }
}
```

### Steps to reproduce

1. run `git clone git@github.com:dgradwell-ams/automapper-nest-cli-test.git` 
2. run `npm i`
3. run `npm run build`

### Expected behavior

The project should build/run 

### Screenshots

![image](https://user-images.githubusercontent.com/78749369/162769303-e9a05c69-93c9-4f07-8c3d-f964ba3787e6.png)

### Minimum reproduction code

[https://github.com/dgradwell-ams/automapper-nest-cli-test](https://github.com/dgradwell-ams/automapper-nest-cli-test)

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.0

### Additional context

macOS 12.3 Monterey
NodeJS v16.14.2
NestJS v8.4.4
Typescript v4.6.3

**Comment by nartc** [comment]
Thanks for reporting. Fixed in 8.3.1
