### ISSUE TITLE
AutoMapper ignores array instead of mapping it to MikroORM Collection

### ISSUE THREAD

**Issue by Alwinator** [nartc/mapper#458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am using AutoMapper with MikroORM which uses collections instead of arrays. AutoMapper usually maps arrays to collections. However, I have one use case in my project where AutoMapper just ignores one array.

Expected:
```js
Role {
  permissions: Collection<Permission> {
    '0': Permission { roles: [Collection<Role>], id: 0, name: 'WRITE_RECIPE' },
    initialized: true,
    dirty: true
  },
  id: 8,
  name: 'Writer'
}
```

Actual:
```js
Role {
  permissions: [
    Permission { roles: [Collection<Role>], name: 'WRITE_RECIPE', id: 0 }
  ],
  name: 'Writer',
  id: 8
}
```

The permission array is not mapped.

### Steps to reproduce

npm run start:dev

### Expected behavior

That all arrays are mapped to MikroORM collections.

### Minimum reproduction code

https://github.com/Alwinator/automapper-mikro-orm-bug

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [X] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.2.3

### Additional context

Linux, Ubuntu 21.10
Node v16.13.1

**Comment by nartc** [comment]
Hi @Alwinator, thank you for reporting. It's not that AutoMapper is "ignoring" the Collection, it simply does not **MAKE** a new Collection when mapping `RoleDto#permissions -> Role#permissions`.

```js
Role {
  permissions: [ // 👇 this is actually populated due to "new Permission()", not by AutoMapper
    Permission { roles: [Collection<Role>], name: 'WRITE_RECIPE', id: 0 }
  ],
  name: 'Writer',
  id: 8
}
```

The idea of AutoMapper with MikroORM has always been mapping from your Entities to DTOs, not the other way around. Mapping from a DTO to your Entity is probably better with using MikroORM utilities like `EntityManager#create` or `Repository#create`. You can also create an intermediate model to map your DTO to, then call `create()` on that intermediate model (Eg: DTO -> IntermediaModel -> Entity, you shouldn't do DTO -> Entity with AutoMapper). 

That said, there are a couple of workarounds that you can make it work:
- `afterMap()`

```ts
createMap(
  mapper,
  RoleDto,
  Role,
  afterMap((source, destination) => {
    // here, we're explicitly create a Collection from "permissions"
    // the type of Role#permissions is Collection<Permission>, but here it is actually just a Permission[]
    destination.permissions = Collection.create(
      destination,
      'permissions',
      destination.permissions as unknown as Permission[],
      true,
    ) as Collection<Permission>;
  }),
);
```

This whole `afterMap()` thing can be extracted into a utility function so you don't have to deal with all those type assertion.

- Use `wrap()` from MikroORM

```ts
const entity = mapper.map(dto, RoleDto, Role);
repo.create(wrap(entity).toJSON());
```

**Comment by Alwinator** [comment]
Thank you for the advice! I fixed the problem by simply converting my DTO to an object and passing it to MikroORM instead of using AutoMapper and it works perfectly. However, I would still enjoy it if this would work directly with AutoMapper ;)

```ts
private toObjectRecursive(cls: any): object{
    const out = {...cls}

    for(const key in out){
      if(out[key] instanceof CrudDto){
        out[key] = this.toObjectRecursive(out[key])
      }else if(out[key] instanceof Array){
        out[key] = out[key].map((e) => this.toObjectRecursive(e))
      }
    }
    return out
  }
```

**Comment by nartc** [comment]
If you can think of a reasonable public API for automapper/mikro to work, I'm happy to hear. Just one constraint:
- I don't want automapper/core to have mikroorm as a dependency. 

Right now, automapper/mikro is just an extension of automapper/classes (eg: AutoMap decorator) and it doesn't have to be that way.
