### ISSUE TITLE
Is that possible that the mapper can base on the source type to map?

### ISSUE THREAD

**Issue by vip30** [nartc/mapper#47]
I used AutoMapper (and mediatr which is also developed by Jimmy Bogard) in dotnet core before. It's pretty nice that see it again in typescript. 

However, the code base currently use the destination class to found out the source class is pretty strange.

Thats mean if we have two different source class to project to same vm model will get wrong.

Here is the example that
```ts
class User {
  @Expose()
  firstName!: string;
  @Expose()
  lastName!: string;
  @ExposedType(() => Profile)
  profile!: Profile;
}

class User2 {
  @Expose()
  firstName!: string;
  @Expose()
  lastName!: string;
  @ExposedType(() => Profile)
  profile!: Profile;
}

    mapper
      .createMap(User, UserVm)
      .forMember(d => d.first, opts => opts.mapFrom(s => "Khang"))
      .forMember(d => d.last, opts => opts.mapFrom(s => s.lastName))
      .forMember(
        d => d.full,
        opts => opts.mapFrom(s => s.firstName + " " + s.lastName)
      );
    mapper
      .createMap(User2, UserVm)
      .forMember(d => d.first, opts => opts.fromValue("a"))
      .forMember(d => d.last, opts => opts.fromValue("B"))
      .forMember(
        d => d.full,
        opts => opts.mapFrom(s => s.firstName + " " + s.lastName)
      );
```

Now if we project a User2 obj to UserVm it will still keep using the first mapping 

refs:
https://codesandbox.io/s/automapper-demo-b3d7p

**Comment by vip30** [comment]
I submit a pull request for this case, can you please check if it is correct or not?

Thanks

**Comment by nartc** [comment]
Thanks for reporting the issue.

**Comment by nartc** [comment]
@vip30 check out the latest release to see if it works for your case. Let me know if you have any suggestions. And as always, PRs are welcomed :) Thanks again for reporting the issue.

**Comment by vip30** [comment]
Thank you I will try it now

**Comment by nartc** [comment]
@vip30 `nestjsx-automapper` 2.0.6 has been released.

**Comment by nartc** [comment]
@vip30 `nestjsx-automapper` 2.0.7 has been released.
