### ISSUE TITLE
Async `afterMap` is not awaited by `mapAsync`

### ISSUE THREAD

**Issue by LennartH** [nartc/mapper#474]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I added an async `afterMap` to a mapping configuration according to the [documentation](https://automapperts.netlify.app/docs/mapping-configuration/after-map/), but the values applied in the `afterMap` handler aren't set when using `const dto = mapper.mapAsync(...)`. 

### Steps to reproduce

I adjusted the integration test for `mapAsync`:

```ts
describe('Map Async Classes', () => {
    const mapper = createMapper({ strategyInitializer: classes() });

    it('should map', async () => {
        createMap(
            mapper,
            SimpleUser,
            SimpleUserDto,
            forMember((d) => d.fullName, ignore()),
            afterMap(async (_, destination) => {
                // Forcing a real delay instead of resolving the promise immediately
                await new Promise((resolve) => setTimeout(resolve, 500));
                const fullName = 'Tran Chau';
                Object.assign(destination, { fullName });
            })
        );

        const dto = await mapper.mapAsync(
            new SimpleUser('Chau', 'Tran'),
            SimpleUser,
            SimpleUserDto
        );
        // When this is enabled the test succeeds
        // await new Promise((resolve) => setTimeout(resolve, 1000));
        expect(dto.fullName).toEqual('Tran Chau');
    });
});
```

When commented timeout isn't enabled `dto.fullName` is `undefined`, so I assume that `afterMap` is called in a way that if it returns a promise it isn't awaited.

### Expected behavior

Modifications of `destination` in an async `afterMap` should be applied when `mapAsync` is resolved.

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.6

**Comment by nartc** [comment]
Async in AutoMapper has always been funky. I just thought of a way to maybe utilize Async Generator to make it work more conssitently

**Comment by nartc** [comment]
@LennartH update on this. I've tried different ways to support async but I think the core of AutoMapper isn't built to support this kind of operation. I also think that "resolving" something is app logic, not mapping logic. (https://github.com/AutoMapper/AutoMapper/issues/991)

That said, a better approach is to resolve the async value then use `extraArguments` instead of `afterMap()` for async operations. I'll try to update docs as soon as possible on this.

**Comment by faradoxuzb** [comment]
why do we need afterMap then?

**Comment by ajfranzoia** [comment]
@nartc doc seems to be still outdated https://automapperts.netlify.app/docs/mapping-configuration/after-map, right?
