### ISSUE TITLE
Manual mappings doesn't overwritte extended ones

### ISSUE THREAD

**Issue by micalevisk** [nartc/mapper#477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

when using `extend` (with 1 one level), all the `forMember` from the source side of `extend` are being evaluated even tho they won't be used in the end

I'm not sure if this is a limitation, a bug or a feature request (to improve the performance) tbh

### Models/DTOs/VMs

```ts
class S1 {
  foo: number
}
class D {
  foo: number
}

class S2 extends S1 {}
```

### Mapping configuration

```ts
const mapper = createMapper({
  strategyInitializer: classes(),
});

createMap(mapper,
  S1, D,
  forMember(d => d.foo,
    mapFrom(s => (console.log('should not evaluate'), 1))
  )
)

createMap(mapper,
  S2, D,
  extend(S1, D),
  forMember(d => d.foo,
    mapFrom(s => (console.log('shoud evaluate only this one'), 2))
  )
)
```

### Steps to reproduce

just run the above like so:

```ts
const bar = new S2()
console.log(
  mapper.map(bar, S2, D),
)
```

and you'll get this output:

```
should not evaluate
shoud evaluate only this one
D { foo: 2 }
```

And if we have the `extraArgs` function, it will be evaluated twice!

### Expected behavior

that code should outputs:

```
shoud evaluate only this one
D { foo: 2 }
```

because the first `forMember` defined should not be evaluated as it's overwritten by the latter

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.6

**Comment by nartc** [comment]
This is probably a limitation + feature request. Currently, there's no way for the 2nd `createMap()` to halt the first `createMap()`. JavaScript is evaluated top-down so the first `createMap()` will run regardless. In order to achieve this, we'll probably need a Compiler in between so we can do some Static Analysis.

**Comment by micalevisk** [comment]
this limitation causes the following issue:

```ts
import { PartialType } from '@nestjs/swagger';

class S1 {
  foo: number[]
}
class D {
  fooDoubled?: number[]
}

class S2 extends PartialType(S1) {}

createMap(mapper,
  S1, D,
  forMember(d => d.fooDoubled,
    mapFrom(s => s.foo.map(n => n*2))
  )
)

createMap(mapper,
  S2, D,
  extend(S1, D),
  forMember(d => d.fooDoubled,
    mapFrom(s => s.foo?.map(n => n*2))
  )
)
```

as the callback of first `mapFrom` will be invoked when mapping from `S2` to `D` when ``, we will get  `TypeError: Cannot read properties of undefined (reading 'map')`

:disappointed:

**Comment by micalevisk** [comment]
looks like we can use `preCondition` as a workaround to the above issue

**Comment by micalevisk** [comment]
I notice that adding `preCondition(s => !!s.foo, undefined)` to the first mapping prevents it from being run (when mapping  from `S2`) lol @nartc is this a bug or the expected behavior of `preCondition`?
