### ISSUE TITLE
Cannot require transformer-plugin

### ISSUE THREAD

**Issue by mortenokeefe** [nartc/mapper#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm trying to use automapper in a vue project and since the last update I cannot require the transformer plugin.
I get this error:
![image](https://user-images.githubusercontent.com/57749927/176845192-093be222-cdaf-448a-b027-a317ba061cb7.png)

My webpack config looks like this:
![image](https://user-images.githubusercontent.com/57749927/176845383-aa4f18ab-4552-4e0b-8de0-ca0859176bdd.png)

Works fine if i downgrade to version 8.3.7

### Expected behavior

Be able to require the tranformer plugin for my webpack config.

### Screenshots

![image](https://user-images.githubusercontent.com/57749927/176845192-093be222-cdaf-448a-b027-a317ba061cb7.png)
![image](https://user-images.githubusercontent.com/57749927/176845497-2812c18f-dd61-4df6-a559-1bce6ecf2931.png)

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.4.0

**Comment by nartc** [comment]
Please give this another try with the latest
