### ISSUE TITLE
Transformer plugin doesnt automap array types

### ISSUE THREAD

**Issue by mortenokeefe** [nartc/mapper#484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Im trying to use the transformer plugin and i works fine for simple types and objects but not for arrays.

I'm mapping from class ProjectFolderModel:
![image](https://user-images.githubusercontent.com/57749927/176847473-be32cb6e-ee4d-423a-a05f-46e40afa975c.png)

To class ProjectFolderDto:
![image](https://user-images.githubusercontent.com/57749927/176847589-a47ad295-1721-4614-92c4-854577d046ee.png)

My object before mapping:
![image](https://user-images.githubusercontent.com/57749927/176847807-e5e7f78d-5178-446e-a8c8-7f67a86b8653.png)

And after mapping:
![image](https://user-images.githubusercontent.com/57749927/176847940-001c6f27-4f8d-41c9-9daa-599057e68ce2.png)

If i comment in the automap statements in ProjectFolderDto and explicitly tell automapper to do the mapping it works.

If i console log the __AUTOMAPPER_METADATA_FACTORY__ property on the ProjectFolderDto I can see it is missing definitions for properties "children" and "ints":
![image](https://user-images.githubusercontent.com/57749927/176849033-ae344242-6575-4391-8fef-13c2d86aebe8.png)

### Expected behavior

That the tranformer plugin can work with array types like it works with simple types and objects.

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.3.7

**Comment by nartc** [comment]
The plugin is definitely handling array (check the test model here https://github.com/nartc/mapper/blob/main/packages/integration-test/src/transformer-plugin/model.ts). Can you please share with me a reproduce?

**Comment by mortenokeefe** [comment]
@nartc I have tried to setup a repo here https://github.com/mortenokeefe/automapper-test/tree/main/src
I'm using the User class from your link as test data and console logging the AUTOMAPPER_METADATA_FACTORY property it which looks than comes out different than in your example though.
![image](https://user-images.githubusercontent.com/57749927/177947283-737dd7ab-5323-47ee-982d-6949af70bcf3.png)
Hope you can help.

**Comment by nartc** [comment]
@mortenokeefe thank you for the link. I found the issue but not entirely sure why. Apparently in your setup with `vue.config.js`, `string[]` and `Array<string>` are interpreted differently by TypeScript. The workaround now is to use `Array<string>`. I'm still looking for a fix

**Comment by mortenokeefe** [comment]
@nartc thanks for the reply. The problem with using Array<ClassName> is that is doesnt completely solve my problem. My children arrray now gets included but doesnt get mapped
![image](https://user-images.githubusercontent.com/57749927/178263482-ffc39972-3791-491a-b444-09b422320e48.png)
It is as if the automapper dosent recognize the children as being of the class ProjectFolderModel and therefore doent apply the correct mapping?

**Comment by nartc** [comment]
@mortenokeefe yeah, I'm not exactly sure what's going on with the setup with `vue.config.js` (not saying that it's wrong) but the way it parses the AST is a bit different than what I normally see. The fix that I currently have (not released yet) doesn't seem to fix the issue you're running into with `Array<Type>` either 🥲

**Comment by nartc** [comment]
@mortenokeefe please try 8.5.1 out
