### ISSUE TITLE
Transformer plugin has unexpected behavior with NestJS

### ISSUE THREAD

**Issue by sulsDotK** [nartc/mapper#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am trying to AutoMap properties using the transformer plugin as described here:

[(https://automapperts.netlify.app/docs/misc/transformer-plugin#nestjs-cli)]

nest-cli.json
```
{
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "plugins": ["@automapper/classes/transformer-plugin"]
  }
}
```

Output:

![image](https://user-images.githubusercontent.com/40224671/177544080-82fe53f7-89e8-45a7-aec2-180e7111260f.png)

As you can see, no field is mapped from source to destination

### Models/DTOs/VMs

Source:

```
import { IsDefined, IsString } from 'class-validator'

export class CreateThemeRequestDto {
  @IsString()
  @IsDefined()
  readonly label: string

  @IsString()
  @IsDefined()
  readonly value: string
}
```

Destination: 

```
import { Column, Entity } from 'typeorm'
import QBaseEntity from './qBase.entity'

@Entity({ name: 'themes' })
export default class ThemeEntity extends QBaseEntity {
  public constructor(theme?: Partial<ThemeEntity>) {
    super()
    Object.assign(this, theme)
  }

  @Column()
  label: string

  @Column()
  value: string
}
```

### Mapping configuration

theme.profile.ts

```
import { AutomapperProfile, InjectMapper } from '@automapper/nestjs'
import { createMap, Mapper, MappingProfile } from '@automapper/core'
import { Injectable } from '@nestjs/common'
import ThemeEntity from '@database/entity/theme.entity'
import { CreateThemeRequestDto } from '@domain/theme/dto/request/create-theme.request.dto'
import { UpdateThemeRequestDto } from '@domain/theme/dto/request/update-theme.request.dto'

@Injectable()
export class ThemeProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper)
  }

  override get profile(): MappingProfile {
    return (mapper) => {
      createMap(mapper, CreateThemeRequestDto, ThemeEntity)
      createMap(mapper, UpdateThemeRequestDto, ThemeEntity)
    }
  }
}

```

### Steps to reproduce

I execute an endpoint to run this service function, as shown in screenshot

```
async createTheme(dto: CreateThemeRequestDto) {
    try {
      const mappedEntity = this.mapper.map(
        dto,
        CreateThemeRequestDto,
        ThemeEntity
      )
      await this.themeRepository.save(mappedEntity)
    } catch (e) {
      this.logger.error(e)
      throw e
    }
  }
```

### Expected behavior

Values to be correctly mapped into destination object

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.5.0

### Additional context

Windows 10
Node v16

**Comment by sulsDotK** [comment]
Hey, thanks for taking the time to respond. Really appreciate it.

The DTO ends with `.request.dto.ts` and entity ends with `.entity.ts`
But i've also tried with `.dto.ts` ... No difference

One observation though, I added an ignore clause and got this ... seems the ignore is working?

![image](https://user-images.githubusercontent.com/40224671/177601349-3e515bdd-84df-4c7a-9b2a-412d3f1fb84d.png)


```
@Injectable()
export class SkillProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper)
  }

  override get profile(): MappingProfile {
    return (mapper) => {
      createMap(mapper, CreateSkillRequestDto, SkillEntity)
      createMap(mapper, UpdateSkillRequestDto, SkillEntity)
    }
  }

  protected get mappingConfigurations(): MappingConfiguration[] {
    // the 3 createMap() above will get this `extend()`
    return [
      typeConverter(String, ObjectID, (id) => new ObjectID(id)),
      typeConverter(String, Date, (id) => new Date(id)),
      forMember((dest) => dest.categories, ignore())
    ]
  }
}
```

Also something weird is happening, since sometimes it has actually worked but then it goes back to not working. Any ideas?

**Comment by nartc** [comment]
Hm...at this point, I'd love a reproduce.

**Comment by sulsDotK** [comment]
Not able to reproduce in another project... Any ideas ?

**Comment by nartc** [comment]
Can you share with me your models (entities and dtos)?

**Comment by sulsDotK** [comment]
Here you go

[files.zip](https://github.com/nartc/mapper/files/9057341/files.zip)

**Comment by nartc** [comment]
I can't seem to reproduce this. If you can provide a sample reproduce, I'm happy to take a look further.
