### ISSUE TITLE
Autmapper/Profile/UnitTest: map not found

### ISSUE THREAD

**Issue by ReginaldBull** [nartc/mapper#495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

There is a profile:
```typescript

@Injectable()
export class SceneConfigurationProfile extends AutomapperProfile {
  constructor(@InjectMapper() mapper: Mapper) {
    super(mapper);
  }

  get profile(): MappingProfile {
    return (mapper: Mapper) => {
        createMap(
          mapper,
          SceneConfigurationModel,
          SceneConfigurationResponseDto);
  };
}
```

I use that profile in app.module.ts:

```typescript
const profiles=  [/*some other profiles*/, SceneConfigurationProfile];

@Module({
providers: [...profiles]
})
```

Inside my service, I do the following: 
```typescript
const result = this.context.find();
return this.mapper.map(result, SceneConfigurationModel, SceneConfigurationResponseDto)
```

While running the service, everything works as expected.

As soon as I start the unit tests, I get following error:
```bash
Error: Mapping is not found for class SceneConfigurationModel extends sequelize_typescript_1.Model {
} and class SceneConfigurationResponseDto {
}
```

My unit test setup looks like that:
```typescript
const module: TestingModule = await Test.createTestingModule({
      imports: [...TestDataFactory.imports()],
      providers: [
        SceneConfigurationsService,
        {
          provide: Sequelize,
          useValue: new SequelizeMock(sequelize)
        },
        {
          provide: getModelToken(SceneConfigurationModel),
          useValue: {
            create: jest.fn(async () => testDataCreation.createEntity()),
            findAll: jest.fn(() => [testDataCreation.createEntity()]),
            findOne: jest.fn(() => testDataCreation.createEntity()),
            findAndCountAll: jest.fn(() => ({
              rows: [testDataCreation.createEntity()],
              count: 1
            })),
          },
        },
        ...profiles
      ],
    }).compile();
```
Fun fact, in other unit tests, everything works perfectly. I checked if I had made a spelling mistake -> nope
Checked if I used a wrong reference -> nope, same references

### Models/DTOs/VMs
```typescript
export class SceneConfigurationResponseDto {
  @ApiProperty()
  @AutoMap()
  id: string;

  @ApiProperty()
  @AutoMap()
  code: string;

  @ApiProperty()
  @AutoMap()
  description?: string;
}

export class SceneConfigurationModel {
  @AutoMap()
  id: string;

  clientId: string;

  customerId: string;

  @AutoMap()
  code!: string;

  @AutoMap()
  description?: string;
}
```

### Expected behavior

UnitTest and normal service run should behave similar.

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [ ] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.5.0

### Additional context

Node 16.11.11
nestjs

**Comment by nartc** [comment]
@ReginaldBull thank you for reporting. Unit testing bugs seem to be one of the harder ones to track. Can you provide a sample reproduce?

**Comment by ReginaldBull** [comment]
Sorry, I cannot provide the repository. As additional information I can say, that there are in total 13 profiles.

**Comment by nartc** [comment]
Can you create a sample application that has this bug reproduced?

**Comment by ReginaldBull** [comment]
I will try to reproduce it in another repository.Thank you for your answers!

**Comment by ReginaldBull** [comment]
I have tested today again. Didn't change anything on the profile, but it started to work magically.
