### ISSUE TITLE
No transformer-plugin bundled in the 8.7.2 version

### ISSUE THREAD

**Issue by omihaz** [nartc/mapper#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Cannot find module '@automapper/classes/transformer-plugin'

### Expected behavior

The `classes` package contains `transformer-plugin` folder.

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.7.2

**Comment by nartc** [comment]
Sorry. The new Nx target defaults messed up the build a bit. 8.7.4 (8.7.3 is still broken :() fixed the issue
