### ISSUE TITLE
Transformer plugin doesn't work for derived classes

### ISSUE THREAD

**Issue by thaindq** [nartc/mapper#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Transformer plugin doesn't work for derived classes

### Models/DTOs/VMs

```
class ObjectEntity {
    id!: number;
    name!: string;
    description!: string; 
}

class ObjectDto {
    id!: number;
    name!: string;
}

class ObjectDetailsDto extends ObjectDto {
    description!: string;
}
```

### Mapping configuration

```
export class MappingProfile extends AutomapperProfile {
    constructor(@InjectMapper() mapper: Mapper) {
        super(mapper);
    }

    override get profile() {
        return (mapper: Mapper) => {
            createMap(mapper, ObjectEntity, ObjectDto);
            createMap(mapper, ObjectEntity, ObjectDetailsDto);
        };
    }
}
```

### Steps to reproduce
```
this.mapper.map(entity, ObjectEntity, ObjectDetailsDto);
```

### Expected behavior

The metadata for `ObjectDetailsDto` generated by the plugin would be:
```
static __AUTOMAPPER_METADATA_FACTORY__() {
    return [
            ["description", { type: () => String, depth: 1 }],     
    }
}
```
while it should have been
```
static __AUTOMAPPER_METADATA_FACTORY__() {
    return [
            ["id", { type: () => Number, depth: 1 }],     
            ["name", { type: () => String, depth: 1 }],     
            ["description", { type: () => String, depth: 1 }],     
    }
}
```
So the result of the mapping is missing `id` and `name` from the `ObjectEntity`. It works fine for `ObjectDto` (base class)

Also, it would be great if the plugin supports model file name path with regex instead of just suffix as my naming convention doesn't have any `.entity` or `.dto` at the end. I would have to change all the entities and dtos in my project to be able to use it.

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.7.6

**Comment by nartc** [comment]
Hi @thaindq, thank you for reporting (and sorry for the late response as I was on vacation).

Personally, I'm not sure if this is a bug or a feature request because the use-case you represented can be fixed easily with `extend()`.

```ts
export class MappingProfile extends AutomapperProfile {
    constructor(@InjectMapper() mapper: Mapper) {
        super(mapper);
    }

    override get profile() {
        return (mapper: Mapper) => {
            const objectDtoMapping = createMap(mapper, ObjectEntity, ObjectDto);
            createMap(mapper, ObjectEntity, ObjectDetailsDto, extend(objectDtoMapping));
        };
    }
}
```

**Comment by thaindq** [comment]
Hi @nartc, thank you, I didn't think about extending an existing mapping, however I think it would be great if the lib could do it automatically so we don't need to `extend` twice which could easily be forgotten. Thanks for your help and yeah you're right, it's more like a feature request. I'll close the issue.
