### ISSUE TITLE
Can this work with getter/setter?

### ISSUE THREAD

**Issue by krukru** [nartc/mapper#51]
Hi! :)

I was wondering, can this mapper work by mapping public attributes to their appropriate setter or getter (depending on the map direction).

Consider this example
```
class User {
  private _firstname: string;
  public set firstname(value: string) { this._firstname = value; }
  public get firstname(value: string) { return this._firstname; }
}

class UserVm {
  @AutoMap()
  public firstname: string;
}
```

My questoini is how to get a bi-directional map between User and UserVm? Hopefully not by manually assigning every public property to a setter/getter :)

Thanks!

**Comment by nartc** [comment]
Hi @krukru ,

Thanks for submitting an issue. Apparently, this is not currently supported because I didn't really think of this use-case. But I can see that it makes sense to support it. 

The current code checks for if `source.hasOwnProperty()` without checking recursively on its `prototype` which is causing getter/setter to not work.

I'll push a fix soon.

**Comment by nartc** [comment]
Reopening for `reverseMap` doesn't quite work.

**Comment by nartc** [comment]
@krukru let me know if 3.0.2 works out for you. Create a new issue if you find one. Thanks

**Comment by krukru** [comment]
Hey @nartc, thanks for the quick reply! 
Unfortunately, looking at the example you added to the README, I could not get the mapper to work. I am trying to map DTO (or ViewModels, from your example) to domain models.

These are my files used to test the mapper
```typescript
import {AutoMap} from "@nartc/automapper";

export class Foo {
    @AutoMap()
    public get foo(): string {
        return this._foo;
    }

    public set foo(value: string) {
        this._foo = value;
    }

    private _foo: string;
}

export class FooDTO {
    public foo: string;
}
````
I initialise the mapper using

```js
        this._mapper.initialize((config: AutoMapperConfiguration) => {
            config.createMap(FooDTO, Foo);
        });
```
And call the map with 
```const foo: Foo = this._mapper.map({foo: "bar"}, Foo, FooDTO);```

I receive the following error when calling `.map` 
```
Error: The following keys are unmapped on Foo:
      ----------------------------
      _foo
      
```

**Comment by nartc** [comment]
@krukru are you sure you're on version 3.0.2?

**Comment by krukru** [comment]
Yes, I checked by looking at your package.json in my node_modules. I will
try a clean install in a couple of hours, maybe I made some mistake :)

**Comment by nartc** [comment]
@krukru https://codesandbox.io/s/inspiring-cherry-k5m2d check this sandbox if you have time

**Comment by nartc** [comment]
```typescript
export class FooDTO {
   @AutoMap() // <-- and also make sure you have this
    public foo: string;
}
```

**Comment by nartc** [comment]
Check the latest version (3.0.5) and let me know if you still have issue.

**Comment by krukru** [comment]
Hey @nartc 
After updating to the latest version (3.1.0) the issue is resolved and everything works like a charm :)
Thanks!
