### ISSUE TITLE
@AutoMap not working with extended class

### ISSUE THREAD

**Issue by tannguyen208** [nartc/mapper#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

mappedUser = {
  username: 'yyyy'
}

### Models/DTOs/VMs

import {createMap} from '@automapper/core'
import {AutoMap} from '@automapper/classes'

export class Entity {
  @AutoMap()
  _id!: string
}

export class User extends Entity {
  @AutoMap()
  username!: string

  // we don't want to map "password"
  password!: string
}

export class UserDto extends Entity {
  @AutoMap()
  username!: string
}

createMap(mapper, User, UserDto)

const dataUser = new User()
dataUser._id = 'xxxx-xxxx-xxxx-xxxx'
dataUser.username = 'yyyy'
dataUser.password = 'zzzz'

const mappedUser = mapper.map(dataUser, User, UserDto)

### Expected behavior

mappedUser = {
  _id: 'xxxx-xxxx-xxxx-xxxx',
  username: 'yyyy'
}

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.0.0

### Additional context

Node: v16.17.0

"@automapper/classes": "^8.7.6",
"@automapper/core": "^8.7.6",

**Comment by nartc** [comment]
@tannguyen208 thank you for reporting. You'd still have to create a Mapping for the base classes (https://automapperts.netlify.app/docs/mapping-configuration/extend)
