### ISSUE TITLE
@UseInterceptors(MapInterceptor(ClassType, InterfaceType)) doesn't work to map class to an object

### ISSUE THREAD

**Issue by Manik-Jain** [nartc/mapper#513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I'm working with nestjs and trying to use [Map interceptor](https://automapperts.netlify.app/docs/nestjs#mapinterceptor) to map a class to an interface, and MapInterceptor cannot determine type Interface with the error:

```<InterfaceName> only refers to a type, but is being used as a value here```

### Expected behavior

Map interceptor shall be able to map class to interface types

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [X] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.0.0

**Comment by zgid123** [comment]
interface is only for typescript, the runtime still use javascript, so you must define a class instead of using typescript's interface
