### ISSUE TITLE
Compilation fails if property name is start (substring) of another property

### ISSUE THREAD

**Issue by MasterPG5** [nartc/mapper#525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I faced a very strange bug (I think). I have two classes, OrderDto and Order. These classes have 2 properties (among others), of which one is a starting substring of the other: shippingFee and shippingFeePerPallet, both nullable numbers.
I have a mapping profile to map from the former to the latter. First, I didn't specify these in the mapping profile explicitely, but when I tried to build the project, it failed with the following error (at the addProfile function):
```
.../server/node_modules/@automapper/core/index.cjs:1092
  return Object.prototype.hasOwnProperty.call(obj, property);
                                         ^
[2022.12.19 10:44:47] [error] -  TypeError: Cannot convert undefined or null to object

[...]

at addProfile (.../server/node_modules/@automapper/core/index.cjs:1373:11)
```

I narrowed down the problem to the shippingFee property. I tried adding both properties to the profile explicitely, as follows:

```
createMap(
    mapper,
    OrderDto,
    Order,
    forMember(
      (dest) => dest.shippingFee,
      mapFrom((source) => source.shippingFee)
    ),
    forMember(
      (dest) => dest.shippingFeePerPallet,
      mapFrom((source) => source.shippingFeePerPallet)
    )
  );
```

But it still doesn't work. The way I got it working is that I deleted shippingFee from both the profile and the OrderDto class (not a good solution, but it confirms the source of the issue). Another workaround was that I renamed shippingFee to **shipiingFee** (yes, with a typo) in both classes, in which case it _magically_ worked.

The strange thing is, that other properties also have this kind of same-starting-substring, but they work without errors (like status and statusEn) - even the workaround has the same substring: shipiingFee and shippingFeePerPallet also start with "ship".

### Models/DTOs/VMs

```
export class OrderDto {
...
  @AutoMap() @Expose() shippingFee?: number;
  @AutoMap() @Expose() shippingFeePerPallet?: number;
...
}

export class Order {
...
  @AutoMap() @Expose() shippingFee?: number;
  @AutoMap() @Expose() shippingFeePerPallet?: number;
...
}
```

### Mapping configuration

```
createMap(
    mapper,
    OrderDto,
    Order,
    forMember(
      (dest) => dest.shippingFee,
      mapFrom((source) => source.shippingFee)
    ),
    forMember(
      (dest) => dest.shippingFeePerPallet,
      mapFrom((source) => source.shippingFeePerPallet)
    )
  );
```

### Steps to reproduce

1. Implement the following classes and mapping
2. Add the profile
3. Try to build

### Expected behavior

Should map the properties to their counterparts as expected.

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.7.6

**Comment by Balint98** [comment]
I have run into the same issue, when I used `namingConventions` option in your case `CamelCaseNamingConvention`.
```typescript
const mapper = createMapper({
    strategyInitializer: classes(),
    namingConventions: new CamelCaseNamingConvention(), // <---
});
```
If you use `namingConventions` you enable the autoflattening feature (see: https://automapperts.netlify.app/docs/fundamentals/auto-flattening)
Now Automapper expects your classes to look like this:
``` typescript
export class ShippingFee {
   @AutoMap() @Expose() perPallet?: number;
}

export class OrderDto {
...
  @AutoMap() @Expose() shippingFee?: ShippingFee;
...
}

export class Order {
...
  @AutoMap() @Expose() shippingFeePerPallet?: number;
...
}
```

And now when you map an `OrderDto` to `Order` Automapper will map `orderDto.shippingFee.perPallet` into `order.shippingFeePerPallet`
``` typescript
const orderDto = new OrderDto();
const shippingFee = new ShippingFee();
shippingFee.perPallet = 10;
orderDto.shippingFee = shippingFee;

console.log('orderDto', orderDto); // orderDto OrderDto { shippingFee: ShippingFee { perPallet: 10 } }
const order = mapper.map(orderDto, OrderDto, Order);
console.log('order', order); // order Order { shippingFeePerPallet: 10 }
```

Without the `namingConventions`  it works just fine.
```typescript
const mapper = createMapper({
    strategyInitializer: classes()
});
```

**Comment by MasterPG5** [comment]
Thank you, @Balint98 , it works for me, too!

Closing the issue.
