### ISSUE TITLE
AutoMap()not working with vue3

### ISSUE THREAD

**Issue by luckyluggi** [nartc/mapper#531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

If i run this code in a default vue3 app:
``` javascript
export const mapper = createMapper({
  strategyInitializer: classes()
});

export class Bio {
  @AutoMap()
  name: string;
}

export class BioDto {
  @AutoMap()
  name: string;
}

createMap(mapper, Bio, BioDto);

const bio = new Bio();
bio.name = "John Doe";

const dto = mapper.map(bio, Bio, BioDto);

console.log(dto);
```
`name` in the resulting model is always undefined.
See console log:

``` javascript
BioDto {name: undefined}
```
I am using these versions:

``` javascript
    "@automapper/classes": "^8.7.7",
    "@automapper/core": "^8.7.7",
    "reflect-metadata": "^0.1.13",
```
If i add this to createMap it works and im getting BioDto {name: "John Doe"} correctly

``` javascript
    forMember(
      (dest) => dest.name,
      mapFrom((src) => src.name)
    )
```
But i dont want to add this for every property.

### Models/DTOs/VMs

``` javascript
export class Bio {
  @AutoMap()
  name: string;
}

export class BioDto {
  @AutoMap()
  name: string;
}
```

### Mapping configuration

``` javascript
createMap(mapper, Bio, BioDto);
```

### Steps to reproduce

You can see the problem here:
https://stackblitz.com/edit/vitejs-vite-wgn9qm?file=src%2FApp.vue

I've also tried with a standard typescript app. there it works:
https://stackblitz.com/edit/typescript-d3vwm1?file=index.ts

### Expected behavior

Properties with `Automap()` should not be `undefined`.

### Minimum reproduction code

https://stackblitz.com/edit/vitejs-vite-wgn9qm?file=src%2FApp.vue

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### Other package and its version

vue@3.2.45

### AutoMapper version

8.7.7

**Comment by nartc** [comment]
Unfortunately, Vue3 uses Vite and Vite uses esbuild which doesn't support `emitDecoratorMetadata`. I know this isn't the resolution you're hoping for but there's really nothing I can do on my end :(
