### ISSUE TITLE
[Feature request] can preCondition have option to provide default value aside from null?

### ISSUE THREAD

**Issue by ymchun** [nartc/mapper#54]
Now the `preCondition` can check and map the property to `null` when checking result is falsely. Can this function provide a way to set the default value aside from `null` ?

**Comment by nartc** [comment]
@ymchun Thanks for the request. `preCondition` with `defaultValue` has been added in version 3.1. I also added `defaultValue` to `condition()` as well since I think it should be supported. 

```typescript
Mapper.createMap(Model, ViewModel)
   .forMember(d => d.destination)
   .preCondition(s => s.source_expression, defaultValue)
```

**Comment by ymchun** [comment]
@nartc thank you for your quick response 👏

**Comment by ymchun** [comment]
@nartc should this line https://github.com/nartc/mapper/commit/1fd8ca2afe236ddbdf60c2ccfc051b5d08285eef#diff-534cd9b078fed96a297e9c5b3cf8cc35R157

change from `set(destinationObj, destinationMemberPath, preCondition.defaultValue);`
to `set(destinationObj, destinationMemberPath, preCondition.defaultValue || null);`

so that users can omit the default value and get `null` instead of `undefined`

**Comment by ymchun** [comment]
@nartc I've submitted PR, plz check
