### ISSUE TITLE
Transformer Plugin in swc

### ISSUE THREAD

**Issue by thk-powertask** [nartc/mapper#602]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am using nestjs in my personal project and I am using swc compiler. Transformer Plugin
I'm trying to use , but the function of `__AUTOMAPPER_METADATA_FACTORY__` is not created during the build process. Can you tell me why?

### Mapping configuration

```json
{
  "$schema": "https://json.schemastore.org/nest-cli",
  "collection": "@nestjs/schematics",
  "sourceRoot": "src",
  "compilerOptions": {
    "deleteOutDir": true,
    "builder": "swc",
    "typeCheck": true,
    "plugins": [
      {
        "name": "@automapper/classes/transformer-plugin",
        "options": {
          "modelFileNameSuffix": [
            ".info.ts",
            ".dto.ts",
            ".entity.ts"
          ]
        }
      }
    ]
  }
}

```

### Expected behavior

**in dist folder**
```js
class UserMain {
    static __AUTOMAPPER_METADATA_FACTORY__() {
        return [
            ["email", { type: () => String, depth: 1 }],
            ["createdDt", { type: () => String, depth: 1 }]
        ];
    }
}
```

### Package

- [ ] I don't know.
- [ ] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [ ] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/mikro</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] Other (see below)

### AutoMapper version

8.0.0

**Comment by alejandro-pena1** [comment]
@thk-powertask did you find any solution?
