### ISSUE TITLE
Any plan for mapping inheritance?

### ISSUE THREAD

**Issue by vip30** [nartc/mapper#68]
Currently we need to copy and paste the profile if the model mapping is similar but just few of the properties are different

ref: http://docs.automapper.org/en/stable/Mapping-inheritance.html

Thanks

**Comment by nartc** [comment]
@vip30 Hi

Thanks for opening the issue. Since this is likely going to be a **feature request**, can you please provide some real use-cases? And possibly, if you can, some implementation suggestions? That would be nice because I, certainly, don't really run into as many use-cases as others.

**Comment by vip30** [comment]
@nartc Hi 

The usage is basically in extending model.
For example, I have a base model
```ts
class BaseUser {
    name: string
    age: Number
}

class OnlineUser extends BaseUser {
    creditCardNumber: string
}

class ShopUser extends BaseUser {
    shopNumber: string
}

class OnlineUserVM {
    name: string
    age: Number
    creditCardNumber: string
}

class ShopUserVM {
    name: string
    age: Number
    shopNumber: string
}

// Profile
// Currently
    mapper
      .createMap(OnlineUser , OnlineUserVM)
      // Although same name will be mapping but that is just an example
      .forMember(
        destination => destination.name,
        opts => opts.mapFrom(source => source.name),
      )
      .
      .
      .
    mapper
      .createMap(ShopUser, ShopUserVM )
      // Although same name will be mapping but that is just an example
      .forMember(
        destination => destination.name,
        opts => opts.mapFrom(source => source.name),
      )

// Expected
    mapper
      .createMap(BaseUser, BaseUserVM)
      .forMember(
        destination => destination.name,
        opts => opts.mapFrom(source => source.name),
      )
      .
      .
      .
    mapper
      .createMap(ShopUser, ShopUserVM )
      .includeBase(BaseUser, BaseUserVM)
      // Although same name will be mapping but that is just an example
      .forMember(
        destination => destination.shopNumber,
        opts => opts.fromValue('1234'),
      )
```

**Comment by nartc** [comment]
I'll look into that more. I've been always under the impression that derived classes were always working. Turns out that I'm wrong. 

However, I might be slow on working on this feature as I'm working on a Transformer Plugin to automate the `@AutoMap()` process. Again, thanks for the request.

**Comment by nartc** [comment]
@vip30 Check the latest release out to see if it works out for you.

**Comment by nartc** [comment]
@vip30 I just released another version with a change to `includeBase` https://github.com/nartc/mapper/releases/tag/v4.0.0 please update accordingly.

**Comment by vip30** [comment]
Yep, I updated and it work as expected. Thank you very much @nartc

**Comment by manuelnucci** [comment]
I'm implementing an inheritance similar to the one @vip30 proposed, using the { includeBase: [sourceParentEntity, destinationParentEntity] } object options. However, the properties mapped from one class to the other are just simply ommited once the mapping finishes.

Here are the classes and profile involved:

```
export class BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @CreateDateColumn({ name: 'create_date' })
  createDate!: Date;

  @UpdateDateColumn({ name: 'update_date' })
  updateDate!: Date;

  @DeleteDateColumn({ name: 'delete_date' })
  deleteDate?: Date;

  @VersionColumn()
  version!: number;
}

export class ResponseBaseEntity {
  @ApiProperty({ description: 'UUID' })
  id!: string;
}

@Profile()
export class BaseEntityProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(BaseEntity, ResponseBaseEntity);
  }
}
```

```
@Entity()
export class Career extends BaseEntity {
  name!: string;
}

@Exclude()
export class ResponseCareerDto extends ResponseBaseEntity {
  @Expose()
  @ApiProperty({ description: 'Name of career' })
  name!: string;
}

@Profile()
export class CareerProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(Career, ResponseCareerDto, { includeBase: [BaseEntity, ResponseBaseEntity] });
  }
}
```

All profiles were imported in a module (not the same but doesn't matter).

Before mapping: 

```
Career {
  id: 'f0d7ac18-9ecd-4667-819a-c00136421c20',
  createDate: 2020-08-15T22:23:39.265Z,
  updateDate: 2020-08-15T22:23:39.265Z,
  deleteDate: null,
  version: 1,
  name: 'Systems Engineering'
}
```

After mapping:

`ResponseCareerDto { name: 'Systems Engineering' }`

The _id_ property should be in the final object.

**Comment by nartc** [comment]
@manuelnucci You'd need to decorate the fields with `AutoMap`, otherwise, TypeScript will not see the fields in the class. 

```ts
export class BaseEntity {
  @PrimaryGeneratedColumn('uuid')
  @AutoMap()
  id!: string;

  @CreateDateColumn({ name: 'create_date' })
  createDate!: Date;

  @UpdateDateColumn({ name: 'update_date' })
  updateDate!: Date;

  @DeleteDateColumn({ name: 'delete_date' })
  deleteDate?: Date;

  @VersionColumn()
  version!: number;
}

export class ResponseBaseEntity {
  @ApiProperty({ description: 'UUID' })
  @AutoMap()
  id!: string;
}

@Profile()
export class BaseEntityProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(BaseEntity, ResponseBaseEntity);
  }
}
```
Now `id` will be mapped automatically. Also, I noticed you use `Expose` from `class-transformer`, is it related to automapper at all?

**Comment by manuelnucci** [comment]
Yes, indeed! My mistake, didn't want to complicate the example and forgot to remove them.

I forgot to mention that I'm using the _Transformer Plugin_ in a NestJS app. So, as my understanding, those decorators shouldn't be necessary. Perhaps as we're dealing with a mix of inheritante and profiles, the decorators should be necessary.

I'll try your proposal and reach out to you with the result.

**Comment by nartc** [comment]
@manuelnucci Lemme know if it works ad intended **with** the decorators. If it does, then we know it’s the plugin problem. When that’s the case, would you please open an issue on the transformer plugin repo so we can properly track the issue? Thank you in advance

**Comment by manuelnucci** [comment]
@nartc Ok, I proceed to add the decorator @AutoMap to **both** classes, _BaseEntity_ and _ResponseBaseEntity_. It must be in both to work properly. Somehow the plugin doesn't recognize the fields in the parent classes.

I'll create a new issue to track and fix this.
