### ISSUE TITLE
_removeExtraForFunction will incorrectly parse member name if member name includes 'return' 

### ISSUE THREAD

**Issue by jmplahitko** [nartc/mapper#72]
Example: Given a member name of 'returnUrl' on a destination model: 
Calling mapper.createMap(Dest, Source).forMember(dest => dest.returnUrl, [expression]) will result in a destination object containing a 'Url' member. 

I've stepped through and found that the _removeExtraForFunction util is splitting on 'return', which will split on not only the keyword 'return', but also any other part of the stringified function that contains 'return', including 'dest => dest.returnUrl'

**Comment by nartc** [comment]
Thanks for reporting the issue.
