### ISSUE TITLE
Error when map from extended class

### ISSUE THREAD

**Issue by AliYusuf95** [nartc/mapper#81]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I cant convert to a class that extends a base class, I got this error:
```
Uncaught Error: Mapping not found for source Object
    at AutoMapper._getMappingForNestedKey (automapper.esm.js:1497)
    at AutoMapper._mapMember (automapper.esm.js:1372)
    at AutoMapper._map (automapper.esm.js:1241)
    at AutoMapper.map (automapper.esm.js:1683)
....
```

## Expected behavior
Able to map values from inheritance classes.

## Minimal reproduction of the problem with instructions
```ts
class BaseProfile {
    @AutoMap()
    bio: string;
    @AutoMap()
    age: number;
}

class Profile extends BaseProfile {
    other?: any;
}

class User {
    @AutoMap()
    firstName: string;
    @AutoMap()
    lastName: string;
    @AutoMap(() => Profile)
    profile: Profile;
}
class ProfileVm {
    @AutoMap()
    bio: string;
    @AutoMap()
    isAdult: boolean;
}
class UserVm {
    @AutoMap()
    firstName: string;
    @AutoMap()
    lastName: string;
    @AutoMap(() => ProfileVm)
    profile: ProfileVm;
}

Mapper.createMap(Profile, ProfileVm).forMember(
    dest => dest.isAdult,
    opts => opts.mapFrom(src => src.age > 18),
);
Mapper.createMap(User, UserVm);

const user: User = {
    firstName: 'firstName',
    lastName: 'lastName',
    profile: {
        bio: 'bio',
        age: 12,
    },
};

const res = Mapper.map(user, UserVm, User);
```

## What is the motivation / use case for changing the behavior?
to solve this I have to add mapping to some property in the destination:
```ts
class Profile extends BaseProfile {
    @AutoMap() // <=== This solve it
    other?: any;
}
```

## Environment

<pre><code>
Version: 5.0.8
 
For Tooling issues:
- Node version: 12.13.1
- Platform:  Mac

Others:
- Typescript: 3.8.2
- Nx: 9.0.2
- Angular: 9.0.3
- Nestjs: 6.11.8
</code></pre>

**Comment by nartc** [comment]
Thanks for reporting. I’ll take a look asap

**Comment by AliYusuf95** [comment]
The example I provide still not working. To reproduce, remove this line
https://github.com/nartc/mapper/blob/5d7d8f7b0545fdb73bc292a9ccb69d51e274614c/test/automapper.test.ts#L1435 

And add this to the test
```ts
const profile = new Profile();
profile.bio = 'dev';
profile.age = 20;

const vm = Mapper.map(profile, FooVm);
```

**Comment by AliYusuf95** [comment]
Hi @nartc , I still face this issue with the latest version `5.0.13`

```log
ERROR Error: Mapping not found for source Function and destination Function
    at AutoMapper._getMappingForDestination (automapper.esm.js:1412)
    at AutoMapper._mapMember (automapper.esm.js:1318)
    at AutoMapper._map (automapper.esm.js:1187)
    at AutoMapper.map (automapper.esm.js:1611)
    at Comp1Component.ngOnInit (comp1.component.ts:32)
    at callHook (core.js:4686)
    at callHooks (core.js:4650)
    at executeInitAndCheckHooks (core.js:4591)
    at refreshView (core.js:11814)
    at refreshDynamicEmbeddedViews (core.js:13154)
```

To reproduce the issue: https://github.com/AliYusuf95/ng-automapper/tree/extend

As you can see, when it tries `getMetadata` to `instantiate` the `ProfileDto` property, it can't find the proper mapping for it.

![image](https://user-images.githubusercontent.com/17704100/77475523-06ccfa80-6e2a-11ea-88d3-fea57a19a72a.png)
