### ISSUE TITLE
Mapping key not unique when the code minified

### ISSUE THREAD

**Issue by AliYusuf95** [nartc/mapper#86]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
After building my angular app with `optimizing` flag, the mapper throws this error
`Uncaught Error: Mapping for source n and destination n is already existed`
It seems that the compiler change classes names https://github.com/angular/angular-cli/issues/12887

## Expected behavior
It should work in angular

## What is the motivation / use case for changing the behavior?
I think the mapping key should not rely on the class name as string.
https://github.com/nartc/mapper/blob/5d7d8f7b0545fdb73bc292a9ccb69d51e274614c/src/utils/common.utils.ts#L133-L138

Maybe using the class function it's self would solve the problem.

## Environment

Version: 5.0.9
 
For Tooling issues:
- Node version: 12.13.1
- Platform:  Mac

Others:
- Typescript: 3.8.2
- Nx: 9.0.2
- Angular: 9.0.3
- Nestjs: 6.11.8

**Comment by nartc** [comment]
I can confirm this. Thanks for the issue. I'll take a look ASAP

**Comment by nartc** [comment]
I'm leaving this open to see if the last push fixes the issue.

**Comment by nartc** [comment]
Closed due to inactivity. Please reopen if you still run into the issue.

**Comment by AliYusuf95** [comment]
I just try it now .. the issue still exists, @nartc

**Comment by nartc** [comment]
@AliYusuf95 Can you please provide a repo that reproduces the issue?

**Comment by nartc** [comment]
@AliYusuf95 please test the latest version out. If the problem still exists, please open a new issue with a repo that reproduces your issue. That would help me pinpoint the issue. Thanks!

**Comment by nartc** [comment]
@AliYusuf95  my gut tells me that the problem is going to persist. I'm working on a potential fix which will be released soon.

**Comment by AliYusuf95** [comment]
@nartc please check this repo https://github.com/AliYusuf95/ng-automapper to reproduce

**Comment by AliYusuf95** [comment]
In not sure but I think it happed from lazy loading of the modules, I just tried this and it works fine:
```ts
RouterModule.forRoot([
      {
        path: '',
        component: BaseComponent,
        children: [
          {
            path: '1',
            loadChildren: () => Comp1Module,
          },
          {
            path: '2',
            loadChildren: () => Comp2Module,
          },
          { path: '', redirectTo: '1', pathMatch: 'full' },
          { path: '**', redirectTo: '1', pathMatch: 'full' },
        ],
      },
    ])
```

**Comment by nartc** [comment]
@AliYusuf95 Confirmed 5.0.12 fixed the unique key issue. However, I needed to turn on `emitDecoratorMetadata: true` in `tsconfig.json` because `AutoMap()` decorator is trying to grab the type of the properties using `reflect-metadata`. If you don't have `emitDecoratorMetadata` turned on, you'd need to explicitly map the properties using `forMember`
![image](https://user-images.githubusercontent.com/25516557/77174807-a63b6780-6a8f-11ea-9fcd-7089d8e4cf40.png)

**Comment by AliYusuf95** [comment]
@nartc Class mapping issue solved.

However, if you dealing with `Profiles` you will face an issue that related to this one.
```log
ERROR Error: Uncaught (in promise): Error: u is already existed on the current Mapper instance
Error: u is already existed on the current Mapper instance
    at r.o.addProfile (automapper.esm.js:1556)
    at Object.SdXW (class1.model.ts:20)
    at a (bootstrap:84)
    at Module.Llyi (pages-comp1-comp1-module.js:1)
    at a (bootstrap:84)
    at l.invoke (zone-evergreen.js:364)
    at Object.onInvoke (core.js:41286)
    at l.invoke (zone-evergreen.js:363)
    at a.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at T (zone-evergreen.js:798)
    at T (zone-evergreen.js:750)
    at zone-evergreen.js:860
    at l.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41264)
    at l.invokeTask (zone-evergreen.js:398)
    at a.runTask (zone-evergreen.js:167)
    at m (zone-evergreen.js:569)
```

Do you want to create a separate issue for this? I already create reproduce for this https://github.com/AliYusuf95/ng-automapper/tree/profile

**Comment by nartc** [comment]
Please create a separate issue for this one.
