### ISSUE TITLE
Angular: Error while registering profiles from lazy loaded modules

### ISSUE THREAD

**Issue by AliYusuf95** [nartc/mapper#87]
## I'm submitting a...
<pre><code>
[ ] Regression
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
After building my angular app with optimizing flag, the mapper throws this error
`Error: u is already existed on the current Mapper instance`

## Expected behavior
It should work in angular

## Minimal reproduction of the problem with instructions
https://github.com/AliYusuf95/ng-automapper/tree/profile

## Environment

<pre><code>
Version: 5.0.10

For Tooling issues:
Node version: 12.13.1
Platform: Mac

Others:
Typescript: 3.8.2
Nx: 9.1.0
Angular: 9.0.6
Nestjs: 6.11.11
</code></pre>

**Comment by nartc** [comment]
Can you please check the latest version, which is 5.0.13, out?

**Comment by AliYusuf95** [comment]
@nartc It's working now with version 5.0.13
