### ISSUE TITLE
SnakeCaseNamingConvention not found

### ISSUE THREAD

**Issue by edu1525** [nartc/mapper#91]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ x ] Support request
</code></pre>

## Current behavior
SnakeCaseNamingConvention not found when trying to set global settings config. Where can I find it?

</code></pre>

**Comment by nartc** [comment]
Hi,

It is exported here https://github.com/nartc/mapper/blob/master/src/conventions/index.ts

If the problem persists, can you provide a reproducible repository? 

Thanks

**Comment by edu1525** [comment]
Thanks for the answear !
The real problem is: When I map an object with snake case convention, then the destination object is generated with undefined values for that fields. Is there any configuration I need to do?

**Comment by nartc** [comment]
@edu1525 Maybe not you missing something. Maybe the SnakeCaseConvention has never worked correctly. Would you mind providing a repro? So I can take a look and maybe fix a potential bug?

**Comment by edu1525** [comment]
I'm using the same model as source model and destination model:
`export default class UserRequest {
    id!: number
    external_id!: string
    gateway_id!: string
    email!: string
    first_name!: string
    last_name!: string
    phone!: Phone
    identification!: Id
    address!: Address
    description!: string
    app_id!: number
}
class Phone {
    area_code!: string
    number!: string
}
class Id {
    type!: string
    number!: string
}
class Address {
    id!: number
    zip_code!: string
    street_name!: string
    street_number!: string
    user_id!: number
}`


I have created a Mapper Profile to declare my mappers

` export class ProfileAuth extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(UserRequest, UserRequest).reverseMap()
    mapper.createMap(Address, Address).reverseMap()
    mapper.createMap(Id, Id).reverseMap()
    mapper.createMap(Phone, Phone).reverseMap()
  }
} `

and in my controller I'm using it like: 
`let request = await req.body as User;
 let result = Mapper.map(request, UserRequest, UserRequest)`

The problem is after the map the result object has all the fields with underscores undefined, so first_name, last_name, gateway_id  comes undefined for example. Fields without underscores are mapped normally.

**Comment by nartc** [comment]
I see. 

```
export class ProfileAuth extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();
    mapper.createMap(UserRequest, UserRequest).reverseMap()
    mapper.createMap(Address, Address).reverseMap()
    mapper.createMap(Id, Id).reverseMap()
    mapper.createMap(Phone, Phone).reverseMap()
  }
} 
```
This is to create the mappings for some models. And you did not configure any of the mapping (no `forMember`) manually.

You'd need to use the `@AutoMap()` decorator (or `createMapMetadata()`) to help `AutoMapper` store the metadata first on fields that you want to automap (without using `forMember()`). Or else you'd get this: 

```typescript
class Address {
    id!: number
    zip_code!: string
    street_name!: string
    street_number!: string
    user_id!: number
}
const address = new Address();
console.log(address); // log Address {}. There is no fields to be found.
```

Or, you can try to leverage the plugin: https://github.com/nartc/automapper-transformer-plugin

**Comment by nartc** [comment]
Hi, I'm closing this issue. If you still have problem with it, please open a new one. Thanks
